### ISSUE TITLE
Account Settings: Don't show the Confirm Username error banner.

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94465]
### Quick summary

Currently, the availability of the new username is checked as users type in the field. At the same time, we show an error banner below the "Confirm Username" field that says "Please re-enter your new username to confirm it".

![Screenshot 2024-09-12 at 12 03 57 PM](https://github.com/user-attachments/assets/92e8f83b-15e0-4a08-a0b0-d2caa106b091)

Since the "Save username" button is disabled until both "Username" and "Confirm Username" have the same value, there is no need to display this error banner. As an alternative, consider updating the "Confirm new username" description to indicate that they need to confirm for the save button to be enabled.

### Steps to reproduce

1. Head to /me/account.
2. Update the username field.

### What you expected to happen

Only see the error banner when I haven't confirmed my username.

### What actually happened

See the error banner while I was still typing the new username.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by okmttdhr** [comment]
I don’t think it’s a good idea to remove the error banner, especially from an accessibility standpoint. 

- https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion.html
- https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html

However, I agree that the UI feels a bit off. https://github.com/Automattic/wp-calypso/issues/94464

**Comment by taipeicoder** [comment]
The proposal is not to remove the error banner, but rather not showing it preemptively when users are still typing their new username. I think at the very least we should delay it until the user has focused out of the input field.

**Comment by Aurorum** [comment]
Hi @okmttdhr - would be curious on your views for my proposal in #94640. I agree that there needs to be some validation for a11y purposes, but I'd argue that the Notice is the wrong component for that, and that it should be something like this instead. :)

<img width="967" alt="Screenshot 2024-09-17 at 20 28 46" src="https://github.com/user-attachments/assets/b0d83ff6-903f-44ef-a111-c9374a95fd25">

**Comment by taipeicoder** [comment]
@Aurorum thanks for the improvements! @javierarce, WDYT?

**Comment by javierarce** [comment]
I agree with @Aurorum about the inadequacy of the Notice component in this case. I'll review their proposal and make suggestions to improve it if possible.

**Comment by javierarce** [comment]
Ok, here's my proposal:

First, we display the information using the form input validation under the fields, as @Aurorum suggested. 

When users write down their new username, we display the confirmation field only. At that point, the user hasn't confirmed the username, so showing them anything else would be distracting.

![image](https://github.com/user-attachments/assets/2bf2c968-d65f-4762-a60c-288410271500)

Here's a general error state:

![image](https://github.com/user-attachments/assets/c6953103-0232-4985-a5e2-1f1930f62b18)


And here's the error state we display if the user doesn't match the usernames:

![image](https://github.com/user-attachments/assets/8acd2641-8896-4db1-a0ff-8cb820ab7618)

If they do, we will give them the option to create a matching site. Here, I simplified the current UI with a toggle and made the result of their action more explicit by displaying the new URL they'll get. Also, notice that the button says "Change username" and not "Save username."

![image](https://github.com/user-attachments/assets/86de8dfe-4e91-44fc-8989-176b7b340f0d)

Finally, if the user clicks that button, we ask them to confirm the change using a modal. The text reads:

> Confirm username change
> You are about to change your username, **username**. Once changed, you will not be able to
> revert it. Changing your username will also affect your Gravatar profile and your 
> IntenseDebate profile addresses.

If you just want to update your display name, **Name Lastname**, you can do so under [My Profile].

![image](https://github.com/user-attachments/assets/89be22e7-1293-4720-9375-baf4c4e64f8d)

If they proceed with the change, we should show them a snack bar with a message indicating the change was successful. 

![image](https://github.com/user-attachments/assets/c7d5dbde-1130-4c75-9463-f75856630aa5)

Figma file with these screens: wCm5Tzb7JBaG4WNowWbjES-fi-5250_13523

**Comment by javierarce** [comment]
Regarding using a toggle in my proposal, users can currently submit the username change without selecting any radio button, which means they won't get a new site. In that case, the toggle button is a better solution because it's more compact and easier to read.

But if we wanted to make sure users pick an option, the toggle won't work. In that case, we could do something like this:

![image](https://github.com/user-attachments/assets/e8e43d8a-f205-4f2a-9156-d809ff6b05a4)

**Comment by Aurorum** [comment]
Thanks @javierarce! I've addressed your review in the PR. The only thing which I haven't changed is the toggle; it looks like that is returned from an API endpoint, which I don't have access to, so I'm afraid that I'll need to suggest that as out-of-scope for these changes. That said, I've added the confirmation modal and the success notice.

<img width="1032" alt="Screenshot 2024-09-28 at 12 43 09" src="https://github.com/user-attachments/assets/9b68808e-3238-4b2e-a1fc-92010c01459d"> 
<img width="668" alt="Screenshot 2024-09-28 at 12 43 49" src="https://github.com/user-attachments/assets/9451fb78-cf9c-4b16-8c43-4186a0ad83fd">

This should be ready for review now (#94640) - let me know what you think!

**Comment by javierarce** [comment]
> Thanks @javierarce! I've addressed your review in the PR. The only thing which I haven't changed is the toggle; it looks like that is returned from an API endpoint, which I don't have access to, so I'm afraid that I'll need to suggest that as out-of-scope for these changes. That said, I've added the confirmation modal and the success notice.

That's ok, thanks @Aurorum! I reviewed your PR and left some feedback. I'll create an issue for the toggle change.

**Comment by Addison-Stavlo** [comment]
Noting that we moved @Aurorum's PR to fix this into a new branch under this repo (https://github.com/Automattic/wp-calypso/pull/95221), and can ship it once translations are in.

**Comment by donalirl** [comment]
@javierarce Some feedback while reviewing the [doc updates](https://github.com/Automattic/en.support-docs-content/issues/2926) for these changes:

With the option to create a matching blog with the new username, one of the sentences ends in a period while the other does not. To make it consistent, can we either remove the period from the second option (or, add a period to the first)?
![Image](https://github.com/user-attachments/assets/fcc003f5-d3a5-43c1-9d6c-0c0496877a57)

A bit of a bigger question, how many users opt to create a new blog for their new username and end up actually using that blog? This seems like a strange thing to even offer, because changing the username and creating a new site are two completely different and unrelated actions. Would we consider removing this option, if the data backs it up?

**Comment by Aurorum** [comment]
Hey @donalirl! I agree that the inconsistency isn't ideal, but those strings are returned from an API endpoint which isn't open-source, so I'm afraid that there isn't much which I can do about it - I'll need to leave it for an a11n to handle!

I also can't comment on the data for removing the option, but my instinct is that it exists from a time when the WP.com username was closely linked to the site address. I guess with the shifting focus away from blogging, that's less relevant now. For what it's worth, @javierarce has proposed simplifying the option in #95071.
