### ISSUE TITLE
Account Settings: The Account Information card needs UI polish

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94464]
### Quick summary

When attempting to update the username, the card changes to the following:

![Screenshot 2024-09-12 at 12 03 57 PM](https://github.com/user-attachments/assets/c5f74b6f-9ccd-4712-b66e-1ec04cc0c406)

The "Would you like a matching blog address too?" and "Please Read Carefully" sections doesn't seem to follow the current design system.

### Steps to reproduce

1. Head to /me/account.
2. Update the username field.

### What you expected to happen

The new card state UI should feel consistent with the rest of the design.

### What actually happened

The new card state UI has a mixture of different font sizes, line heights, etc.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Aurorum** [comment]
PR in https://github.com/Automattic/wp-calypso/pull/94640. :)

**Comment by Addison-Stavlo** [comment]
Noting that we moved @Aurorum's PR to fix this into a new branch under this repo (https://github.com/Automattic/wp-calypso/pull/95221), and can ship it once translations are in.
