### ISSUE TITLE
Masterbar: Restore the position of the Atomic debug menu to the left

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#94472]
The Atomic debug bar used to be on the left. After the last WordPress update, it got "floated right":

<img width="458" alt="image" src="https://github.com/user-attachments/assets/02eeec57-6ba9-44d8-8460-bbdb8cd6e301">

(See the discussion on the original issue https://github.com/Automattic/dotcom-forge/issues/8443)

Let's bring the debug bar to the left again, to avoid the "jump" of the right admin bar icons when switching between sites and/or global view:

<img width="449" alt="image" src="https://github.com/user-attachments/assets/ef5430ab-73b0-4966-b80d-9a691f132fbb">

**Comment by davemart-in** [comment]
I agree.
