### ISSUE TITLE
Account Settings: The unsaved changes browser alert pops up even though the username input value is the same

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94474]
### Quick summary

In the Accounts Settings page (/me/account), typing in the Username field will change the Account Information card as shown below. However, if the user changes their mind and navigates away, the browser will show an "unsaved changes" warning pop-up.

![SCR-20240912-nlyl](https://github.com/user-attachments/assets/e54084d7-fea7-48d3-ae23-53ee3d7fa489)

### Steps to reproduce

0. Use a non-a11n account.
1. Head to /me/account.
2. Change the username, say from "A" to "AA". Don't save!
3. Then change the username back to "A".
4. Click on "My Profile" to navigate away.
5. Observe as the browser "unsaved changes" pops up, even though the username is still "A".

### What you expected to happen

Just be able to navigate away without any alerts.

### What actually happened

The browser showed the "unsaved changes" alert.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Addison-Stavlo** [comment]
I am a bit confused, how do you type in the username field? It seems to be disabled on my end...

**Comment by taipeicoder** [comment]
The username field seems to be disabled for a12n. I'll make a note of it in the issue description!
