### ISSUE TITLE
Masterbar: Improve the information architecture of the profile dropdown

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94470]
### Quick summary

The profile dropdown of the masterbar needs a better information architecture and copy.

![SCR-20240912-miow](https://github.com/user-attachments/assets/06b3eb13-c367-4312-83ee-534dde8788ca)

Currently, these are the links.
1. "Howdy, {display name}" links to the site's /wp-admin/profile.php.
2. "Edit Profile" links to the site's /wp-admin/profile.php.
3. "My Account" links to the global /me.

Worth noting that hovering "Edit Profile", the username is not affected by the hover state.

Also worth noticing that the dropdown follows core.
![SCR-20240912-mkiu](https://github.com/user-attachments/assets/1891b578-ee2f-4587-aa1b-a7ff190ef359)

### Steps to reproduce

Hover over the top-right area of the masterbar for the profile dropdown to show up.

### What you expected to happen

Clearer indication of where these links will take me.

### What actually happened

No clear indication that I will be taken to either the site profile page or my global account page.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by okmttdhr** [comment]
linking to the related discussion: pbxlJb-6it-p2#comment-3892
