### ISSUE TITLE
Reader: cannot unfollow RSS feed

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#945]
Raised by @alternatekev 

A long time ago, I subscribed to a Tumblr blog using our Reader. The blog is http://frakintosh.com

I have never been able to unsubscribe from it, as I'd prefer to just use Tumblr for Tumblr blogs since we can't interact with them on WordPress.com. Here's what happens when I try to unsubscribe:

1. Load up the Reader
2. See new post from this blog's RSS feed
3. Click on the ellipsis menu
4. Click unsubscribe
5. Reload the page, click ellipsis menu...
6. Still subscribed.

Video: https://cloudup.com/cmSnuS5wnuJ

This also doesn't work when viewing the blog's Reader page.

I found some closed issues/PRs that appear to fix this issue by using the blog ID vs the blog's URL, but it hasn't fixed the unfollow bug I describe above.

Another report raised by @aerych 

To reproduce:

1. Edit your following sites and follow "ma.tt", "gizmodo.com", and "arstechnica.com"
View posts for "Followed Sites"

2. Find a post from ma.tt open the menu and choose unfollow.  Refresh the list (or return to the manage subscriptions page) and confirm that you are no longer following.  Everything works as it should.

3. Return to the post list and unfollow a post from either gizmodo.com or arstechnica.com. 
The menu updates as if you were no longer following.
Refresh the list (or return to the manage subscriptions page) and confirm that you are no longer following.  The unfollow did not work. 

It looks like external feeds without Jetpack might be the only ones affected.

Notes from @blowery 

> My guess is that we're unfollowing by the blog URL, not the feed URL, and when we try to unfollow we don't find the site. We should really switch to unfollowing by feed id, not URL, as that takes all the guesswork out.
> 
> This requires modifying the API to take either a feed ID or a URL.

Related: #749

**Comment by bluefuton** [comment]
Youtube channel URLs are also affected: see #2064.

I think the universal fix here would be to add support for unsubscribing by feed ID (part of #749).

**Comment by bluefuton** [comment]
Fixed in #3059.
