### ISSUE TITLE
Ecommerce trial plan allows installing dotorg themes

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#94541]
### Quick summary

It's possible to install a dotorg theme when using the ecommerce trial plan. However according to the `WPCom_Features` system, this isn't allowed fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qsrngherf%2Spynff%2Qjcpbz%2Qsrngherf.cuc%3Se%3Q228736oq%23750-og

Installing a dotorg theme is supposed to be governed by the `WPCOM_Features::INSTALL_THEMES` feature, and when using an ecommerce trial site, access to this feature looks to be correct: `var_dump(wpcom_site_has_feature( WPCOM_Features::INSTALL_THEMES ));` returns `false`.

We should confirm what the intended behaviour is and then implement it

### Steps to reproduce

 1. Go to https://wordpress.com/ecommerce/
 2. Press Get Started and proceed all the way through the flow
 3. Go to wordpress.com/themes/:siteSlug
 4. Enter a search string and look for a community theme
 5. Notice that it displays an Upgrade badge saying you need at least a business plan
 6. Click on the theme

### What you expected to happen

 * To see a CTA like "Upgrade to activate"
 * Clicking on the CTA should go to the checkout with the ecommerce plan
 * Once purchased the theme should be installed

### What actually happened

I see an "Activate this design" button that activates the design.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by daledupreez** [comment]
The intended behaviour is that we shouldn't allow installation of external themes or plugins while on the Commerce trial plan. We set things up that way to prevent abuse of the Atomic platform.

This definitely sounds like a bug.
