### ISSUE TITLE
Activate chat in the migration flow steps, post-checkout

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#94548]
### Details

- Activate the chat in the migration flow steps, post-checkout.
- Ideally, it should be tailored to the flow, with a migration message or something.

### Checklist

- [ ] Chat is activated in the migration flow post-checkout.
- [ ] Chat contains a tailored message when opened.

**Comment by renatho** [comment]
Post to discuss the approaches: pdxWSz-1N9-p2

**Comment by renatho** [comment]
This is in stand-by since I'm focused on a different project this week. I'll return to this whenever I can.

**Comment by donnapep** [comment]
No longer a priority.
