### ISSUE TITLE
Checkout variants show introductory offers for three-year plans in an inconsistent way

### ISSUE THREAD

**Issue by DavidRothstein** [Automattic/wp-calypso#94552]
This was noticed by @renatho here: pdxWSz-1Mt-p2

Example:
![screenshot-2024-09-09-at-18 55 01](https://github.com/user-attachments/assets/92581b0b-3c9c-4b93-8c4a-df0ca3cea3c6)

It seems like maybe the checkout variant code was never updated for three year plans.

Can we relax or even partially remove the following restriction?

https://github.com/Automattic/wp-calypso/blob/ff94a7516d50064fda3323f2018bd82a60489aa4/client/my-sites/checkout/src/components/item-variation-picker/variant-dropdown-price.tsx#L80-L83

Hopefully an easy fix.

**Comment by michaeldcain** [comment]
From planning:

Moving this to the inbox to maybe get picked up as a Quick Fix. If it's not, I'll move it to the backlog tomorrow.
