### ISSUE TITLE
Simple Classic: wp-admin screens have broken font family

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#94606]
### Quick summary

On Simple Classic, wp-admin screens have the wrong font family for `<body>`. This also caused the dashicon icons to break.

|Actual|Expected|
|-|-|
|<img width="200" alt="image" src="https://github.com/user-attachments/assets/764f257f-d6ca-4d41-8cc4-5fd37a400c1b">|<img width="200" alt="image" src="https://github.com/user-attachments/assets/8dbc6ec5-0b63-47c4-adf0-adaa5c7508c6">|

### Steps to reproduce

1. Prepare a Simple Site.
2. Go to Settings -> General.
3. Change the Admin Interface Style to Classic.

### What you expected to happen

The font family should remain the same.

### What actually happened

The font family in wp-admin screens is broken.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I tried to replicate it (proxied and unproxied), and I was not able to replicate it: 

https://github.com/user-attachments/assets/a94de41f-cf82-4930-9733-c6167fdf5890

📌 ACTIONS
- Triaged
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@fushar are you still able to reproduce it?

**Comment by fushar** [comment]
Thanks for checking. I just rechecked. Seems that it's happening when the site language (Settings -> General) is set to Japanese:

<img width="453" alt="image" src="https://github.com/user-attachments/assets/528202e2-7309-4955-b52e-7f3a25d8f9d0">

**Comment by retnonindya** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate the issue
 
<img width="1472" alt="Screenshot 2024-09-18 at 4 15 27 PM" src="https://github.com/user-attachments/assets/9b3fc260-525a-407c-9d25-8e7489e1acd7">

Also, I noticed the font looks... different?

When the site uses using Japanese language:

<img width="385" alt="Screenshot 2024-09-18 at 4 16 51 PM" src="https://github.com/user-attachments/assets/e709df9e-049d-4cdf-9f68-900587d80551">

When the language is set to English:

<img width="619" alt="Screenshot 2024-09-18 at 4 18 27 PM" src="https://github.com/user-attachments/assets/e8545179-c680-46f4-a90c-8af700968b93">

📌 ACTIONS
- Triaged

**Comment by zaguiini** [comment]
Fix: https://github.a8c.com/Automattic/wpcom-i18n/pull/103449

**Comment by zaguiini** [comment]
103449-ghe-Automattic/wpcom-i18n

**Comment by zaguiini** [comment]
This is fixed:

![image](https://github.com/user-attachments/assets/62288b6b-2c87-45c1-9912-3bb8d139d8b4)
