### ISSUE TITLE
Assembler: increase size of prompt to add patterns, select styles, etc. 

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#94608]
When going through the assembler experience, I noticed a prompt on the canvas describing actions to take. The problem is, even for my not very old eyes, it's incredibly hard to read or see:

![Screenshot 2024-09-16 at 9 53 26 PM](https://github.com/user-attachments/assets/832cd491-6fc9-41bc-b9a4-39804189e402)

To be safe since it's so small, this part is what I'm talking about:

![Screenshot 2024-09-16 at 9 56 13 PM](https://github.com/user-attachments/assets/e6dacd46-326a-448b-aa2b-319d8b007dde)

We should either remove this entirely or make it more readable.

**Comment by richtabor** [comment]
Closing this as Assembler work is paused.
