### ISSUE TITLE
Theme Showcase: Searching for a theme sometimes treat it as a non-free theme

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#94616]
### Quick summary

When we search for a theme in Theme Showcase, then click on a theme thumbnail, in certain cases the CTA will say `Upgrade to activate` even though the theme is free.

### Steps to reproduce

1. Prepare a Free Simple site.
2. Go to `/themes/:site`
3. Search for `Blask`
4. Click on the theme thumbnail/card

### What you expected to happen

The theme can be activated:

<img width="612" alt="image" src="https://github.com/user-attachments/assets/b3327074-dd45-410d-b2dc-6a03e86df930">

### What actually happened

It asks me to upgrade to activate:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/39a8e732-35be-46ae-b50e-3cf5022d4f08">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Refresh the page while we're on the theme detail page (after we click the theme thumbnail).

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

It's reproducible on Blask, Fewer, and Bute so far.

**Comment by ianstewart** [comment]
> Prepare a Free Simple site.

This can be reproduced on premium plan as well. See screenshot below of a premium plan site that displays Blask as "Upgrade to activate."

![image](https://github.com/user-attachments/assets/0f4cb423-4e89-4e70-81f7-daf37bb6ef28)

If you proceed to checkout, you'll see that the required plan level is Business. 

I think this is a regression or bug related to community themes and network-activated a8c themes.

**Comment by ianstewart** [comment]
Blask on the core directory:

![image](https://github.com/user-attachments/assets/d6cc2328-ddb0-4561-a47b-513849cc98d9)

**Comment by dsas** [comment]
Sounds like something is treating these themes as community themes but only on the theme details page and not on the theme grid. CC @Addison-Stavlo, I wonder if this is an existing bug that wasn't possible in practice until #94505 added a CTA.

**Comment by Addison-Stavlo** [comment]
>  like something is treating these themes as community themes

It seems this selector we used in https://github.com/Automattic/wp-calypso/pull/94505 comes back true for this theme.

While we have it on the 'free' plan. It does seem to be a wporg theme: https://wordpress.org/themes/search/blask/

Il update the check in https://github.com/Automattic/wp-calypso/pull/94505 to make sure the theme tier is actually 'community'.

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/94634 should resolve this.

**Comment by Addison-Stavlo** [comment]
this should be resolved now.
