### ISSUE TITLE
Latest Drafts: Drafts by contributors that are Pending Review don't show in Latest Drafts list

### ISSUE THREAD

**Issue by frosty** [Automattic/wp-calypso#9465]
#### Steps to reproduce

1. As a contributor to a site, create a new post and submit it for review.
2. As the owner / an admin of the same site, visit your Posts list, with a wide browser window.
3. In the Latest Drafts area on the right hand side notice that the new post isn't visible, even if you select Everyone from the people control.
4. If you collapse the window and choose Drafts from the filters at the top of the page, the post appears.

#### What I expected

The contributor's draft to appear in the Latest Drafts list.

#### What happened instead

The contributor's draft didn't appear, and I had to know to shrink my browser window to find the alternative Drafts list.

Note that the post is also available if I begin editing a new post and choose Drafts from the sidebar.

#### Browser / OS version

Safari 10.0, macOS El Capitan 10.11.6

#### Screenshot / Video

Latest posts area without draft:

<img width="1678" alt="screen shot 2016-11-17 at 10 25 52" src="https://cloud.githubusercontent.com/assets/4780/20385825/e859ecc2-acb0-11e6-9ea0-85d78946b199.png">

Drafts list with post:

<img width="882" alt="screen shot 2016-11-17 at 10 25 18" src="https://cloud.githubusercontent.com/assets/4780/20385830/f2e7edb0-acb0-11e6-8311-9b4faa585cc7.png">

Drafts list in editor with post:

<img width="274" alt="screen shot 2016-11-17 at 10 29 45" src="https://cloud.githubusercontent.com/assets/4780/20385841/f9be5e6c-acb0-11e6-8124-b3098805d158.png">

#### Context / Source

#manual-testing

I noticed this whilst testing posting as a contributor from the WP iOS app. It took me a while to find my own post on the web to approve it!

**Comment by starxedsteph** [comment]
A user contacted us today about this issue via email (#2923946-t).  I was able to replicate with the same steps listed here.

**Comment by SiobhyB** [comment]
We received a report of the same bug in 2983820-t. I was able to replicate in Chrome by following the steps in the original report.

A workaround, while we wait on a more permanent fix, is to head directly to the following URL:

https://wordpress.com/posts/drafts/

**Comment by ashercantrell** [comment]
Received a user report of this as well in chat. This is further compounded by the fact that on multi-user sites, the Drafts button no longer appears when you click on Posts in Calypso. It now only shows Published, Trash, and the Me/Everyone toggle. There's not an easy or intuitive way to get to the Drafts folder anymore.

**Comment by brezocordero** [comment]
Received a report of this bug on 3004638-t. Used the workaround of editing a post and clicking on Drafts icon to see it.

**Comment by ehti** [comment]
Had another user. There's absolutely no way of getting to pending review posts. :/

UNLESS you have at least one draft, then you can get to the drafts tab, and the pending review posts show up there.

Related, which I think is a bug rather than enhancement: https://github.com/Automattic/wp-calypso/issues/1516

**Comment by gemmagarner** [comment]
We've received a report of this bug in in #820755-f. I was able to replicate the issue — and clicking 'Blog Posts' revealed a blocked out title which quickly disappeared.

![pending-review](https://cloud.githubusercontent.com/assets/11627765/22299841/8f31dc60-e31d-11e6-9257-15d4b02839f8.png)

**Comment by rachelmcr** [comment]
The "latest drafts" section was removed in https://github.com/Automattic/wp-calypso/pull/19112. Posts pending review show up in the Drafts section in the posts nav menu (even when the pending review post is the only one there), so I'll close this issue as resolved.
