### ISSUE TITLE
Masterbar: the background color for Default scheme is wrong

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#94650]
### Quick summary

When we're on wp-admin (not Calypso) screens, the background color of the masterbar for the Default scheme is wrong.

### Steps to reproduce

1. Prepare a site.
2. Go to Users -> Profile.
3. Set the color scheme to Default.
4. Go to Dashboard (or any wp-admin screen)
5. Observe the background color of the masterbar.

### What you expected to happen

The color is correct (`#c3c4c7`)

<img width="132" alt="image" src="https://github.com/user-attachments/assets/7f1cc7a8-b503-445d-a95c-9d311dd19e42">

### What actually happened

The color is wrong (`#101517`)

<img width="132" alt="image" src="https://github.com/user-attachments/assets/a79a1470-c8d3-4ade-83e3-4e332e3a1f3e">

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I am almost certain that this is a regression from https://github.com/Automattic/jetpack/pull/39371.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![sBCtFl.png](https://github.com/user-attachments/assets/34c732de-e6f5-4627-a7cc-9b31e63cd48f)

📌 ACTIONS
- Triaged
- Lowering priority from High to Low, as the color difference is minor.
