### ISSUE TITLE
Hosting Overview: 'Need more storage?' is not a hyperlink

### ISSUE THREAD

**Issue by zdenys** [Automattic/wp-calypso#94670]
### Quick summary

Unlike all the other blue hyperlinks on the Hosting Overview page, the `Need more storage?` is not a working link.

![Screenshot on 2024-09-18 at 15:16:58](https://github.com/user-attachments/assets/7d55c245-4072-4340-95be-9a895299aaa9)

When I look at the code responsible for `Need more storage?` at https://github.com/Automattic/wp-calypso/blob/9db92b03c1ef48744601224b37f5cc61e0a77d4d/client/hosting/overview/components/plan-card.tsx#L307-L311 I can see there is a `<span>` and there is no `<a>` with a `href=`.

### Steps to reproduce

1. Navigate to `https://wordpress.com/overview/SITE_URL` on any of Atomic sites
2. Hover over or click `Need more storage?`

### What you expected to happen

Be able to click and navigate to `https://wordpress.com/add-ons/SITE_URL`

### What actually happened

Nothing. 

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

FYI: I know @Automattic/letero has recently worked on Hosting Overview refinements pcYYuD-1Pw-p2

**Comment by fredrikekelund** [comment]
This is a regression caused by https://github.com/Automattic/wp-calypso/pull/94144

Grabbing this for Letero's board
