### ISSUE TITLE
Reader: new post notification appears under menu bar on mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#947]
Only the bottom of the notification is visible on mobile, and it's not possible to tap on it.

<img src="https://cloud.githubusercontent.com/assets/1119271/11457171/02b37064-9670-11e5-89a6-2cc891225505.PNG" alt="img_5522" width="400" />
<sup>Seen at https://wordpress.com/ using Safari Safari iOS 9.1 on iPhone 6</sup>

/hat tip @shaunandrews for the original report

**Comment by blowery** [comment]
@shaunandrews can you take a look at this?

**Comment by shaunandrews** [comment]
Now that the Masterbar is fixed to the top of the viewport on mobile, this is no longer an issue.
