### ISSUE TITLE
Masterbar is rendered as plaintext at the bottom of P2 workspace pages

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#94704]
### Quick summary

On P2 workspace / hub pages, the masterbar is missing and rendered as plaintext at the bottom of the page.

### Steps to reproduce

1. Go to this test P2: dd9GH-p2
2. Observe the masterbar

### What you expected to happen

The masterbar should be rendered correctly at the top.

### What actually happened

The masterbar at the top is blank:

<img width="964" alt="image" src="https://github.com/user-attachments/assets/4ea3c101-98fb-4be4-8654-ddd1f6c43afa">

---

It's rendered weirdly at the bottom:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/64b5d9a6-a6d7-4e94-a86d-68b1514b82f1">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported by @jgcaruso here: p1726684679492869-slack-CRWCHQGUB

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on P2 – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can see this also on a P2 workspace page I own: dd9nZ-p2
![Markup on 2024-09-19 at 16:57:43](https://github.com/user-attachments/assets/e50c9888-4c5f-4dae-9057-0c6b3da17e46)

📌 ACTIONS
- Triaged
