### ISSUE TITLE
VerticalMenu crashes in dev docs

### ISSUE THREAD

**Issue by gikaragia** [Automattic/wp-calypso#94711]
### Quick summary

The VerticalMenu component preview crashes on https://wpcalypso.wordpress.com/devdocs/design/vertical-menu

### Steps to reproduce

1. Visit https://wpcalypso.wordpress.com/devdocs/design/vertical-menu

### What you expected to happen

To see a preview of the component

### What actually happened

There is an 'Oops! There was a problem loading this example. Check the browser console.` error

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by abhisharma9876** [comment]
This might help:This file might fix it
https://bit.ly/4gwC82r
I put the necessary dlls in the archive
