### ISSUE TITLE
Liking a post has the users jumping up and down

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#94749]
### Quick summary

When I like a post with 1 comment, the list of users who liked it jumps up and down

### Steps to reproduce

1. Go to Reader
2. Find a post with 1 like
3. Like

### What you expected to happen

My name goes straight to the top

### What actually happened

(1 more) appears, then my names jumps up and down

https://github.com/user-attachments/assets/04c72c39-1e69-497e-b734-2b6a92915bd8

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple

**Comment by davemart-in** [comment]
This is odd. We'll take a look!
