### ISSUE TITLE
Creating a new list displays an empty page

### ISSUE THREAD

**Issue by dcalhoun** [Automattic/wp-calypso#94769]
### Quick summary

When created a new list in the Reader lists feature, the an empty page is displayed after submitting the form. An error is present in the browser console. 

https://github.com/user-attachments/assets/563930c1-448b-40e6-95bb-307ee768ec8d

### Steps to reproduce

**New List from Index**
1. Visit https://wordpress.com/read. 
2. Expand the _Lists_ navigation item in the sidebar. 
3. Click _Create new list_. 
4. Fill in the required form fields and submit the form. 

**New List from Edit**
1. Visit https://wordpress.com/read. 
3. Expand the _Lists_ navigation item in the sidebar. 
4. Navigate to an existing list. 
5. Edit the list. 
6. Click _Create new list_ in the sidebar. 

### What you expected to happen

The UI updates to confirm the new list creation, likely displaying the list item edit UI. 

### What actually happened

The page empties entirely, displaying nothing. An error is present in the browser console. 

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Refreshing the page recovers the application state, displaying the list item edit UI. 

### Logs or notes

Environment: 

* macOS 14.6.1
* Safari 17.6

Error: 

```
Rendered more hooks than during the previous render.
```

```
v Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
ff r4 - 47903.849decafe3594cc18c53.min.js:14:44943
If (anonymous function)
47903.849decafe3594cc18c53.min.js:14:93586
N queueMicrotask
ff iw - 47903.849decafe3594cc18c53.min.js:14:93561 [f iq - 47903.849decafe3594cc18c53.min.js:14:114173
f iV - 47903.849decafe3594cc18c53.min.js:14:114450
N enqueueJob
N enqueueJob
N enqueueJob
```

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Reader – Replicated

📌 ACTIONS
- Triaged
- Raised priority from Normal to High
- Added to Loop's board.
