### ISSUE TITLE
The comment input is too far from the content

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#94800]
### Quick summary

This is not technically a bug but I believe is a usability issue.

### Steps to reproduce

1. Go to /read and click on any post
2. Scroll down and try to find the comment area without clicking the icon

### What you expected to happen

The comment should be immediately under the post like it is on a regular post

### What actually happened

The comment section is separated by some distraction

<img width="855" alt="Screenshot 2024-09-22 at 8 30 15" src="https://github.com/user-attachments/assets/4da1b39c-8890-49ee-98c2-71849c971420">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Reader - Replicated

📌 ACTIONS
- Triaged

📌 Message to Author
Thank you for flagging his @dzver I've marked this as an Enhancement for the Reader.

**Comment by davemart-in** [comment]
Yep. Good call. Let's move comments above the recommendations.

**Comment by allilevine** [comment]
We can move this here: https://github.com/Automattic/wp-calypso/blob/fix/checkout-back-button-domains-reset/client/blocks/reader-full-post/index.jsx#L663
