### ISSUE TITLE
Task: [Backend] Automated Migration - Save survey result in ZD ticket in site is already in WPCOM

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#94857]
### Details

If the user submits a WPCOM site in the credentials form, we create a ZD ticket for the user and in the next step we show the following survey form -

![image](https://github.com/user-attachments/assets/b1fd2866-2e51-44fd-a9c7-5330c25afcb3)

We need an API in the backend to save the info gathered from this form in the ZD ticket.

### Checklist

- [ ] Create the API to save the data in the ZD ticket
- [ ] Properly log the survey data for further analysis

**Comment by m1r0** [comment]
@Imran92, I'm switching back to the white-label plugin project so feel free to pick this up. I don't have much progress.

**Comment by Imran92** [comment]
Done in D163092-code
