### ISSUE TITLE
Automattic Stream: Crossposts: Change title color, indent more

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9486]
This is also an experiment to try and address one piece of the feedback left for us by @melchoyce.

Mel pointed out that crossposts don't look as different as they used to, which makes them harder to pick out and/or more confusing in context.

I'd like to suggest three small tweaks to try and address this problem:

1. Indent them a further 22px. (They're indented 20px now. Indenting them to 42px would put them in line with the vertical line where the name/site in other cards begins.)

2. Lighten the title text by 30%. Darken to normal on hover. (This accomplishes the same goal as having them appear on grey in the previous design - reducing contrast to tell the eye they're less important.)

3. All text (and grav/blav) should link to the post. (This isn't something Mel mentioned, it would just make them easier to click.)

These changes would leave them looking like this.

![xpost](https://cloud.githubusercontent.com/assets/24388/20405047/671bf91e-acbc-11e6-8645-312882629731.png)

Give it a try?

(Also ccing @nbradbury since we were talking about crossposts earlier today.)

**Comment by blowery** [comment]
I think I noticed a box-shadow for the selected state (maybe just when using the keyboard to move through items?)... Probably want to nix that or bring it in-line with the new selected state too
