### ISSUE TITLE
PopoverMenu: Popover onClose not called if item defines onClick 

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#9489]
#### Steps to reproduce

Define `onClick` for a `PopoverMenuItem`:

```
<PopoverMenu
    id="popover__menu-example"
    isVisible={ this.state.showPopoverMenu }
    onClose={ this.closePopoverMenu }
    position={ this.state.popoverPosition }
    context={ this.refs && this.refs.popoverMenuButton }
>
    <PopoverMenuItem action="A">Item A</PopoverMenuItem>
    <PopoverMenuItem action="B">Item B</PopoverMenuItem>
    <PopoverMenuItem action="C" onClick={ helloWorld }>Item C</PopoverMenuItem>
</PopoverMenu>
```
#### What I expected

The popover menu would close after `onClick` for the `PopoverMenuItem` was called.

#### What happened instead

The popover menu stayed open.

#### Browser / OS version

All.

#### Screenshot / Video

n/a

#### Context / Source

This bug prevented me from making use of `EllipsisMenu` when working on #8711.

**Comment by mattsherman** [comment]
Note https://github.com/Automattic/wp-calypso/pull/7616/commits/2d2295fb79728d0829f0ba4a2ae2dded25e254aa likely would fix this issue.

/cc @aduth

**Comment by mtias** [comment]
I think that may also be the issue with https://github.com/Automattic/wp-calypso/pull/6894
