### ISSUE TITLE
Pagination for Pages list in Site Editor doesn't load, instead black screen

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-calypso#94898]
### Quick summary

A couple users have reported that when they try to click through to second and following lists of Pages in the Site Editor, they see a black screen instead, like this:

https://github.com/user-attachments/assets/49486c2a-56b2-4d88-8d0b-8b8dd204f75e

A plugin conflict check seems to point to the Gutenberg plugin being the cause. I noticed that Gutenberg v19.3.0 was just released in the last day or so and this corresponds with when users who reported the issue started noticing it.

### Steps to reproduce

1. Head to Appearance > Editor > Pages
2. Where there is an option to click through to the second or following list of pages on the site, click on the pagination icon or select a new page from the dropdown
3. Observe a black screen loading.

### What you expected to happen

Users should be able to click through to subsequent pages containing lists of Pages in the Site Editor.

### What actually happened

Clicking through to the next page of listed pages produces a black screen.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

One option is to increase the number of pages listed on the initial page, like this:

https://github.com/user-attachments/assets/c0bf8b09-a5de-43c0-b382-3b6942948424

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Here are errors that I noticed in my browser console when this issue occurred during testing: 35bf7-pb/

Reported here:

- 8782113-zen
- 8783190-zen

**Comment by jp-imagines** [comment]
Related: https://github.com/WordPress/gutenberg/issues/65622

Slack discussion here: p1727267360739269/1727244008.644279-slack-CBTN58FTJ

This appears to be isolated to Gutenberg 19.2 and is fixed in 19.3 (released today, deploying on Dotcom soon).
