### ISSUE TITLE
Jetpack Plugins / Mobile: No controls on plugin list view

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#949]
When you access your plugin list for a site via mobile, there are no controls available at all. You have to navigate through to the individual plugin to do anything useful.

Would it make sense to at least be able to activate/deactivate plugins from here maybe?

Screenshot of plugins page:
![screenshot_20151129-080911](https://cloud.githubusercontent.com/assets/11487924/11457204/d0e29500-9670-11e5-9269-64e87b819262.png)

Screenshot after clicking on a plugin to see more:
![screenshot_20151129-080920](https://cloud.githubusercontent.com/assets/11487924/11457203/d0d82b6a-9670-11e5-8c70-b63a4da6385c.png)

Note by @MichaelArestad: I think it's probably still faster to go to each individual page on mobile. Controls add a lot of visual noise to look through.

**Comment by enejb** [comment]
I agree with @MichaelArestad here. The controls would add more noise.
