### ISSUE TITLE
Pages Navigation in Editor Won't Load

### ISSUE THREAD

**Issue by cat-og** [Automattic/wp-calypso#94917]
### Quick summary

The pages list through the Editor will load initially, but any attempt to use the filters or to navigate to a later page cause a black screen to load instead. This black screen will remain until the page is refreshed, or until I back out of the Editor in the browser entirely. When I refresh the page, I am still on the default 'Pages' list, page 1, in the Editor, no matter which page or filter I had initially selected. 

### Steps to reproduce

1. Go to Editor > Pages
2. Use the pagination at the bottom of the page list to try and access more pages
3. Use the filters to adjust the pages which appear in the list

### What you expected to happen

I expect to be able to switch to another page in the Page list, or to be able to use the filters. 

### What actually happened

When I try to apply the filters, or navigate to another page in the Pages list, the screen goes black and I have to refresh the page or back out of the Editor. 

https://github.com/user-attachments/assets/726a9738-2a43-4b53-bd38-50e6e39c83af

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

- Tested on Chrome, Safari, and Firefox
- Tested with multiple themes, including TwentyTwentyFour, Assembler, Bark, and Feelin'Good.

**Comment by cat-og** [comment]
8778974-zd-a8c

**Comment by Agepeuve** [comment]
Another report - 8814675-zd-a8c

**Comment by mmtr** [comment]
Looks like this is a Core issue that has been fixed in Gutenberg 19.3 (https://github.com/WordPress/gutenberg/issues/65622) which will be deployed to WP.com either today or tomorrow (p1727858688325669/1727857713.677219-slack-CBTN58FTJ).

Closing this one out, since there is nothing else we can do.
