### ISSUE TITLE
Hosting Features: Activation modal button styling improvements

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94923]
### Quick summary

The Activate Hosting Features modal has a couple of buttons that feel out of place with the design system:

"Choose a data center instead" button

| Default | Hover |
| --- | --- |
| ![Screenshot 2024-09-26 at 1 23 55 PM](https://github.com/user-attachments/assets/3d4ec8b6-18cd-4802-9d0e-9c55efec4f53) |  ![Screenshot 2024-09-26 at 1 24 22 PM](https://github.com/user-attachments/assets/4105ee35-8f48-4a50-b39f-3360e9047ee8) |

"Cancel" button (@ianstewart also noted that its position feels off).
| Default | Hover |
| --- | --- |
| ![Screenshot 2024-09-26 at 1 24 05 PM](https://github.com/user-attachments/assets/00500384-5ac4-4d11-b256-02e729979e92) |  ![Screenshot 2024-09-26 at 1 24 16 PM](https://github.com/user-attachments/assets/4b44fde5-335f-4d18-87ab-8339c661cbfe) |

### Steps to reproduce

1. With a Simple site on a Business plan, visit https://wordpress.com/hosting-features/{SITE}.
2. Click on the "Activate now" button.

### What you expected to happen

The buttons in the modal should follow the design system.

### What actually happened

The buttons in the modal don't seem to follow the design system.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by javierarce** [comment]
We've been working on improvements to this modal [here](https://github.com/Automattic/wp-calypso/pull/94676), and that UI has changed a bit.

Here's the proposed design: wCm5Tzb7JBaG4WNowWbjES-fi-5085_18

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- This is already fixed by https://github.com/Automattic/wp-calypso/pull/94676

📌 ACTIONS
- Triaged
- Closed as fixed / resolved
