### ISSUE TITLE
Simple Classic: Some menu items are missing on the Nav Unification

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94926]
### Quick summary

Theme File Editor & Plugin File Editor.
| Nav Unification | wp-admin |
| --- | --- |
| ![Screenshot 2024-09-26 at 2 04 40 PM](https://github.com/user-attachments/assets/0cb3002f-a4fc-4471-8331-327cb10a9b6f) | ![Screenshot 2024-09-26 at 2 05 08 PM](https://github.com/user-attachments/assets/53c1b020-7dce-4a0f-9978-f12123dffce6) | 

Permalinks & Privacy.
| Nav Unification | wp-admin |
| --- | --- |
| ![Screenshot 2024-09-26 at 2 04 49 PM](https://github.com/user-attachments/assets/d878785f-d934-4f18-b9e5-75b37ce84d3a) | ![Screenshot 2024-09-26 at 2 05 16 PM](https://github.com/user-attachments/assets/60abfca8-b564-48f7-85a7-8d5e9cda989a)|

### Steps to reproduce

Use a Simple Classic site and compare the menu items between when Dashboard is selected and when My Home is selected.

### What you expected to happen

Menu items should be the same.

### What actually happened

When in My Home, some menu items are missing.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by renatho** [comment]
D162633-code
