### ISSUE TITLE
Simple Classic: The "Activate all developer tools" button on the Feature Unlock screen goes to a 404 link

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94925]
### Quick summary

The "Activate all developer tools" button leads to a 404 page.

![Screenshot 2024-09-26 at 1 53 30 PM](https://github.com/user-attachments/assets/356c703b-3e8f-4eb3-bf33-977a10039992)

### Steps to reproduce

1. With a Simple Classic site on a Business plan, visit Settings > Permalink.
2. Click on the "Activate all developer tools" button.

### What you expected to happen

Land on the site's Hosting Management Panel, with the Hosting Features tab selected.

### What actually happened

Landed on a 404 page.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ivan-ottinger** [comment]
Hey @taipeicoder 👋🏼 Thanks for the report.

I am having trouble getting the `Permalinks` submenu item listed in the `Settings` menu on a fresh Simple site with Business plan.

Have you taken any specific steps? Thanks.

**Comment by taipeicoder** [comment]
> Hey @taipeicoder 👋🏼 Thanks for the report.
> 
> I am having trouble getting the `Permalinks` submenu item listed in the `Settings` menu on a fresh Simple site with Business plan.
> 
> Have you taken any specific steps? Thanks.

Thanks for following up on this! This is only available for the Classic view. You can switch the admin interface by going to General > Settings. 

Once switched, you'll find the Permalinks menu item under Settings.

This issue seemed to have been caused by the dev-tool route being renamed to hosting-features, and these links weren't updated.

**Comment by ivan-ottinger** [comment]
Thank you, @taipeicoder! That helps.

> This issue seemed to have been caused by the dev-tool route being renamed to hosting-features, and these links weren't updated.

This seems to be the culprit indeed. Going to take a closer look at it.

**Comment by ivan-ottinger** [comment]
Turns out this should be a pretty straightforward fix (related code: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Ssrngher%2Qhcfryy%2Qcntrf%2Qba%2Qfvzcyr%2Qpynffvp%2Shcfryy%2Qcntr%2Qgrzcyngr.cuc%3Se%3Q9n23p086%26zb%3Q1936%26sv%3Q35%2327-og).

I am going to create the patch with the fix.

**Comment by ivan-ottinger** [comment]
D162438-code is now ready for review.

**Comment by ivan-ottinger** [comment]
The D162438-code fix is now in production. → Marking as solved.
