### ISSUE TITLE
Hosting Features: Activation process screen has a gray background

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94930]
### Quick summary

Needs design input of whether this is intended background color (`#fdfdfd`).

![Screenshot 2024-09-26 at 1 36 40 PM](https://github.com/user-attachments/assets/a9f14f21-97b4-4a90-b383-2a2668a98456)

Note that the onboarding process screen also has the same background color.
![SCR-20240926-nepk](https://github.com/user-attachments/assets/6369f910-e1b1-42bb-9974-1d40fa1763c9)

### Steps to reproduce

1. With a Simple site on a Business plan, visit [https://wordpress.com/hosting-features/{SITE}](https://wordpress.com/hosting-features/%7BSITE%7D).
2. Click on the "Activate now" button.
3. Click on the "Activate hosting features" button on the modal.

### What you expected to happen

N/A

### What actually happened

N/A

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by javierarce** [comment]
Yes, that color is expected. We use #FDFDFD for the background of [the onboarding pages](https://www.figma.com/design/eqlepL7MHifK8Bgr1OWqLr/Dotcom-Design-Library?node-id=17921-21641&t=ZvZ3QB1cW6B5OS4a-4).

**Comment by taipeicoder** [comment]
Thanks for confirming! I'll close this issue, then.
