### ISSUE TITLE
Hosting Management Panel: Improve Help Center anchors

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94949]
### Quick summary

Currently, the cards of the Hosting Features tab matches the unlocked tabs once the site transfers to Atomic.

![Screenshot 2024-09-26 at 10 05 31 PM](https://github.com/user-attachments/assets/54bae667-a5af-4f46-afe5-5b32ac7f0ebb)
![Screenshot 2024-09-26 at 10 05 21 PM](https://github.com/user-attachments/assets/b686978d-9485-44e7-b76b-0acde33ee37b)

Every card contains a "Learn more" link. The issue is that the Monitoring and Logs tab share the same support article, and thus has some odd anchoring when opening in the Help Center.

Monitoring
| Current | Proposal |
| --- | --- |
| ![Screenshot 2024-09-26 at 10 06 05 PM](https://github.com/user-attachments/assets/190e178f-6133-4d8f-8125-77e96f314be5) | ![Screenshot 2024-09-26 at 10 07 01 PM](https://github.com/user-attachments/assets/4e3d6674-b784-43be-abb3-a61c94c52a35)|

Logs
| Current | Proposal |
| --- | --- |
| ![Screenshot 2024-09-26 at 10 06 34 PM](https://github.com/user-attachments/assets/947ab735-8c92-46e3-8f7a-ef73913233fa) | ![Screenshot 2024-09-26 at 10 06 55 PM](https://github.com/user-attachments/assets/4d617027-d572-4163-a472-c9cc96a192cf)|

### Steps to reproduce

1. Go to wordpress.com/sites.
2. Select a Simple site.
3. Select the Hosting Features tab.
4. Click on the Learn more links for the Monitoring, and Logs cards.

### What you expected to happen

See screenshots in the Proposal column.

### What actually happened

See screenshots in the Current column.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by fushar** [comment]
This is because Monitoring and Logs were previously part of the same Calypso page `/site-monitoring/:site`, but in different tabs (`Metrics` , `PHP Logs`, and `Webserver Logs` IIRC).

I believe the correct solution here is to split the docs into two separate pages to better reflect the current state. Currently, the page still refers to the old structure:

<img width="349" alt="image" src="https://github.com/user-attachments/assets/b3748e8e-6bba-42c2-ab22-39f875356b60">


<img width="350" alt="image" src="https://github.com/user-attachments/assets/edaeff3c-657d-4785-b337-0808af52b1f8">

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 ACTIONS
- Triaged

📌 Message to Author
@taipeicoder thanks for reporting this one. Good catch! 

@fushar If the only solution here is to split the docs into two different pages, please, let me know so we can repot it to support repo.

**Comment by taipeicoder** [comment]
@ianstewart also recommended splitting the pages, so let's go with that. Thanks!

**Comment by escapemanuele** [comment]
Ok @taipeicoder! Splitting the pages and changing the links in this page will for sure solve this.

Of course the problem will still be there, as scrolling to the appropriate anchor should work anyway, but at least we won't have the problem in this page.
