### ISSUE TITLE
Admin Interface: Update the notice to info instead of plain

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94947]
### Quick summary

Currently, the notice "Changing admin interface style" has the icon info with gray background. Update the notice to be is-info so that the icon info has a blue background instead. 

![Screenshot 2024-09-26 at 9 57 11 PM](https://github.com/user-attachments/assets/ae9c72f0-ef19-4a93-aa5c-d81805450c24)

### Steps to reproduce

1. Using a site with Default view, head to Settings > General.
2. Change the Admin interface option to Classic.

### What you expected to happen

The "Changing admin interface style" notice should be with the info icon and a blue background.

### What actually happened

The "Changing admin interface style" notice has the info icon and a gray background.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Aurorum** [comment]
Perhaps I'm missing some context, but my understanding is that the 'something happening' state should use this plain state; for instance, the 2FA login does this when sending a SMS. I wonder if there's some guidance on this and if this is a broader issue than just one notice?

**Comment by escapemanuele** [comment]
![Image](https://github.com/user-attachments/assets/29eb20e9-90c7-47eb-8c5f-b6bdcb4ef721)

I believe this has been changed to is-info @taipeicoder

**Comment by taipeicoder** [comment]
Thanks for the follow-up! Let's close this one then.
