### ISSUE TITLE
Poll block doesn't show results

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#94956]
### Quick summary

I created a poll in a p2 and it won't show the results without voting, and even if I vote, if I return to the page later it won't show me the updated results without voting again.

### Steps to reproduce

1. Go to Gutenberg, add a poll with some options.  
2. Vote on it, optionally have some other people vote on it.
3. Return to it.

### What you expected to happen

I should see the updated results.

### What actually happened

I see the option to vote again and not the results.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by gavande1** [comment]
> I see the option to vote again and not the results.

This behaviour is expected by default. If you want to display the results after a user has voted, you need to select the appropriate option:

![Image](https://github.com/user-attachments/assets/eddf6d93-477b-4bd9-9d48-4c23d30c834e)

Once I selected that option, I was able to see the results after reloading the page.

@paxblueribbon, am I missing anything? If not, can we go ahead and close this issue?

**Comment by gavande1** [comment]
I will go ahead and close this task. Feel free to reopen the issue if needed.
