### ISSUE TITLE
Congrats Modal: Exiting creates an odd masterbar height transition

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#94967]
### Quick summary

See recording for reference:

https://github.com/user-attachments/assets/cdb0ebc1-56a8-45c7-be7c-5ef20b8fe2b5

### Steps to reproduce

1. Head to the Theme Showcase /themes/{SITE}. Alternatively, the Plugins Marketplace /plugins/{SITE}
2. Activate any theme/plugin
3. Exit the Congrats modal

### What you expected to happen

The masterbar to remain at a fixed height.

### What actually happened

The masterbar had an odd height transition.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by gavande1** [comment]
Regarding themes, it appears that we have removed the congratulatory screen that appeared during the theme installation. This might explain why I couldn't reproduce the issue. Please let me know if I'm mistaken, @dsas.  

![Image](https://github.com/user-attachments/assets/ef455d0a-8fbf-45af-b165-7aaae484215d)

As for plugins, we automatically redirect users to the installed plugins screen after a plugin is installed.

@taipeicoder, are you still able to reproduce these problems? If not, can we consider this issue resolved?

**Comment by taipeicoder** [comment]
@lsl have we removed the congrats for theme activation of every type? We can close this issue if that's the case.
