### ISSUE TITLE
Facebook embeds not visible from smaller devices

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#95012]
### Quick summary

When a user embeds a Facebook post, the embed is invisible on the live site.
Instead, there is a blank space.

### Steps to reproduce

1. Obtain a Facebook post URL to embed;
2. Add it to a post or page with the Embed block
3. Notice how the post is visible on Desktop
4. Visit the published post from a mobile device
5. Notice that the post is not visible there

What I see in a desktop device:
![Screenshot 2024-09-28 at 11 16 17](https://github.com/user-attachments/assets/794dcbcb-d16a-48f6-af0c-c16f1be2e277)

And on a mobile device:
![5E5E64DB0C9DC0635425%7C1](https://github.com/user-attachments/assets/69821c6a-d895-4b9a-8d98-4a82b0ddc594)

### What you expected to happen

The embedded post should be visible across all devices.

### What actually happened

The embedded post is not visible on mobile devices.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Reported here:
8799570-zd-a8c

**Comment by vykes-mac** [comment]
I was able to reproduce following the provided steps. I also see this error in my console log

![image](https://github.com/user-attachments/assets/ffaa18de-78ec-4470-b4a5-e2c058bd3ee2)

**Comment by vykes-mac** [comment]
A quick googling of the issue shows it's a prominent issue that's on facebook side with `X-Frame-Options` deny on their end.

I also tested the issue on a simple HTML page using facebooks own provided embed widget and it still fail.

`<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fcontainerhouse4ever%2Fposts%2Fpfbid0sgH9mMgjiYFFDDGRoxUtLdht2TaFvvyMJScKL8LNVBnkeKADF3mNohRAAkuFfDiYl&show_text=true&width=500" width="500" height="641" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- I'm able to replicate this as well outside WordPress.com, using a simple HTML file

📌 ACTIONS
- Triaged

@vykes-mac I'm closing this one. This is on Facebook's end, and there's nothing we can do.
