### ISSUE TITLE
Post-migration Experience: Add the Transfer Domain task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#95076]
Related to pfuQfP-IF-p2

This task should guide the user through connecting or transferring the domain to WordPress.com. 

For more information, please visit: pfuQfP-IF-p2

**Comment by sixhours** [comment]
More context in this post: paYKcK-5uu-p2

**Comment by valterlorran** [comment]
Closing this as we merged everything related to the domain connection.
