### ISSUE TITLE
Post-migration Experience: Add the "Check SSL status" task

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#95096]
Please refer to this post: pfuQfP-Gs-p2

**Comment by renatho** [comment]
Adding something here that I accidentally found while searching for other things and I think could be useful: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sqbznvaf%2Qffy.cuc%3Se%3Qr47n8754-og

**Comment by andres-blanco** [comment]
Part of this task was completed in this job D164293-code

We still need to add a trigger when the SSL cert is actually provisioned. The places where this needs to be triggered are identified in this diff D163968-code. We would need to replace the do_action by actually enqueuing the job. Also getting a review from Nomado might be valuable.

**Comment by valterlorran** [comment]
Closing this as we launched everything related to the Check SSL task.
