### ISSUE TITLE
Reader: empty lists and tags in sidebar are strange

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#951]
Raised by @shaunandrews 

> When you create a new account and land on Reader, your sidebar looks a little strange:
> 
> <img width="298" alt="screen shot 2015-09-18 at 4 35 35 pm" src="https://cloud.githubusercontent.com/assets/191598/9970461/4f39a85c-5e23-11e5-8d17-0a3f3c778ded.png">
> 
> The Lists and Tags bits are the biggest offenders here. Showing an empty list and two inputs looks strange—its not obvious that these inputs are going to add something to your sidebar. I think there's some bigger changes we could make here, but for some quick-wins, I think we could add a default list (or 2?) and maybe hide the tag input until after the user follows their first tag. If we wanna get crazy, we could bring My Likes and My Comments into the Lists grouping, too.
> 
> ![sidebar simplifications](https://cloud.githubusercontent.com/assets/191598/9970647/53d13712-5e24-11e5-9ddd-eae1ac30baac.png)

Note from @kriskarkoski 

> Personally I don't care for My Comments and My Likes being inside of Lists as I see Lists as something I'm curating, but if we don't want the separate My Activity section I could see just including them below Recommended Blogs before the Lists section

**Comment by alisterscott** [comment]
This is the current sidebar for a brand new customer:

<img width="269" alt="screen shot 2017-05-11 at 1 18 43 pm" src="https://cloud.githubusercontent.com/assets/128826/25930967/770e8444-364c-11e7-8dca-7f9452fbe7d9.png">

expanded:

<img width="269" alt="screen shot 2017-05-11 at 1 18 51 pm" src="https://cloud.githubusercontent.com/assets/128826/25930970/7ce44854-364c-11e7-8772-f43f1e37c1ab.png">

This issue no longer applies to the current design so closing this out.
