### ISSUE TITLE
Onboarding: Use your domain link to contact help may be improved

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#95109]
### Quick summary

![Image](https://github.com/user-attachments/assets/e1167cb8-bf1e-4861-b778-2c9c934e60ed)

The link brings the users to `https://wordpress.com/help/contact`, that redirects to `https://wordpress.com/help?from=`, as `/contact` is no more used.

We should change it to https://wordpress.com/help?help-center=home, to open the Help Center when landing on the page.

### Steps to reproduce

1. Go through onboarding `/setup/onboarding` or `/start`
2. Reach the Domains step
3. Click on `Use a domain I own`
4. Input one domain
5. You will reach the page in the screenshot, the link is at the bottom

### What you expected to happen

To land in `https://wordpress.com/help?help-center=home`

### What actually happened

Landed in `https://wordpress.com/help?from=`

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Click on the Help Center icon

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple –  Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
- While trying to use an existing domain registered elsewhere, I couldn't get the screen above to either migrate or map it. 
- @Automattic/nomado is this something you could also test on your end?

📌 ACTIONS
- Triaged
- Pinging the team in case this is a blocker for potential customers.

**Comment by Robertght** [comment]
cc @Automattic/vertex too

**Comment by escapemanuele** [comment]
@Robertght this is something we at Vertex can take a look at, yes.

**Comment by gius80** [comment]
@Robertght I am on it 👍
