### ISSUE TITLE
Taxonomy Manager: Unable to delete categories with non-Latin charsets

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9511]
#### Steps to reproduce
1. Create a category or tag with non-Latin characters like `Римский` or `北京位`
2. Try to delete it

#### What I expected
To be able to delete it

#### What happened instead
The entry never disappears.  I was able to remove it from wp-admin

#### Browser / OS version
OSX Chrome and Windows IE11

#### Screenshot / Video
![wp-calypso-non-latin](https://cloud.githubusercontent.com/assets/7233112/20438193/a32035ba-ad84-11e6-910d-18ade7eea855.gif)

#### Context / Source
#manual-testing

**Comment by hoverduck** [comment]
Renaming the category also does not work.

**Comment by youknowriad** [comment]
This should be fixed by https://code.a8c.com/D3483
