### ISSUE TITLE
Checkout: Long domains break removal modal

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#95110]
### Quick summary

![Image](https://github.com/user-attachments/assets/6968efbe-fd42-4529-a8ca-163dc3f72aa5)

### Steps to reproduce

1. Search and select a long domain
2. Reach checkout
3. Try to remove the domain and the modal should appear

### What you expected to happen

To see the modal correctly

### What actually happened

There is a visual error

### Impact

All

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on checkout - replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was also able to see this on the inbox step:

![Image](https://github.com/user-attachments/assets/b20c8c8d-f4b9-4e12-acb3-a2897cf88bff)


📌 ACTIONS
- Triaged

@renancarvalho should I open a new issue for the extra thing above?

**Comment by renancarvalho** [comment]
Hello @Robertght, yes please :)

**Comment by Robertght** [comment]
Done: https://github.com/Automattic/wp-calypso/issues/95305
