### ISSUE TITLE
`create-site` and `site-creation-step` look like a duplication

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#95127]
### Details

On the Checkout page, the Stepper flow logs a step called create-site and a step called site-creation-step with the following events. These steps however don’t seem to exist in the Classic flow.

`calypso_signup_step_start` (step: create-site; step: site-creation-step)
`calypso_signup_actions_submit_step` (step: create-site; step: site-creation-step)
`calypso_signup_actions_complete_step` (step: create-site)

**Comment by renancarvalho** [comment]
@escapemanuele can we close this as well? It looks p1728309541567439/1728288796.108799-slack-C02T4NVL4JJ like it is not an issue?

**Comment by escapemanuele** [comment]
Yes, this is not an issue @skim1220. I checked the code and it is done by design because `site-creation-step` was the old name of the step and it is done like this to keep funnels with the old slug working

https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/helpers/get-step-old-slug.ts#L6
