### ISSUE TITLE
Checkout: Upsell doesn't trigger any track event

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#95129]
### Details

On the right pane of the checkout page, clicking the upsell button didn’t trigger any Tracks event. This happens in both Classic and Stepper. It would be nice to track this interaction as well.

![Image](https://github.com/user-attachments/assets/41601949-0d13-4871-af12-cb93ad6a1005)

**Comment by renancarvalho** [comment]
I am unable to reproduce this issue:


On `/start` I can see this being logged when clicking that button

![Image](https://github.com/user-attachments/assets/6f413e7b-1410-43ac-a816-f959663a1b0f)

On `stepper -> setup/onboarding/` I see this when clicking that button
![Image](https://github.com/user-attachments/assets/7a6a960e-71a7-41f9-bdb7-0f6c79874abf)

**Comment by renancarvalho** [comment]
And if you click again to switch to a 3y plan, it logs once more with the `3y` value, which makes total sense to me
