### ISSUE TITLE
Post-migration experience: Add blog stickers for migration state

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95156]
**Description**

Add blog stickers to indicate the state of a migration as per the following logic. A site should only have one of these stickers at any given time:

- `migration-pending` – After a plan is purchased in the migration flow.
- `migration-pending-diy` – When the "I'll do it myself" option is selected.
- `migration-pending-difm` – When the "Do it for me" option is selected.
- `migration-started-diy` – When a DIY migration starts.
- `migration-started-difm` – When a DIFM migration starts.
- `migration-completed-diy` – When a DIY migration finishes.
- `migration-completed-difm` – When a DIFM migration finishes.

pfuQfP-Hj-p2

**Comment by donnapep** [comment]
@valterlorran Note that the logic has changed a little to include `-diy` or `-difm` for each state. See the issue description above for the details.

**Comment by valterlorran** [comment]
Hey @donnapep, thanks for the heads up. I will update the logic in my diff. I also want to change from `pending-migration` to `migration-pending` to keep consistency.

**Comment by valterlorran** [comment]
I create a new diff to tackle the updates: D163224-code

**Comment by m1r0** [comment]
Thanks for the help on this, @valterlorran. FYI, I've just joined the project so don't hesitate to ping me if you need a hand.

**Comment by valterlorran** [comment]
I will remove this from our board, as @Automattic/nexus will take it from here.

**Comment by m1r0** [comment]
The last remaining task was extracted [here](https://github.com/Automattic/wp-calypso/issues/95288). Closing.
