### ISSUE TITLE
White-labelled plugin: Cleanup old translations

### ISSUE THREAD

**Issue by m1r0** [Automattic/wp-calypso#95154]
We've added some translation checks in https://github.com/Automattic/wp-calypso/pull/95101 that need to be cleaned up as soon as the new translations are ready.

**Comment by m1r0** [comment]
The new translations are [live](https://github.com/Automattic/wp-calypso/pull/95101#issuecomment-2402927481). cc @sixhours

**Comment by m1r0** [comment]
[The translations are ready.](https://github.com/Automattic/wp-calypso/pull/95101#issuecomment-2412374472)

**Comment by sixhours** [comment]
Done in #95557
