### ISSUE TITLE
Post-purchase Migration Experience: Show front-end banner for pending or in-progress migrations

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95166]
## Description
Display a banner on the front-end if a logged in user tries to view their new site, but the migration hasn't started yet or is in-progress. The CTA should go to the Sites dashboard.

### Migration Pending
A banner is displayed if the site has any of the following blog stickers:

- `pending-migration`
- `pending-migration-diy`
- `pending-migration-difm`

![Image](https://github.com/user-attachments/assets/07c38924-f05b-4230-b7d4-16568aef196e)

### Migration Started

A different banner is displayed if the site has any of the following blog stickers:

- `migration-started-diy`
- `migration-started-difm`

![Image](https://github.com/user-attachments/assets/b62cd892-327d-42c7-87e7-98348d7abe49)

p9Jlb4-ep1-p2

**Comment by Imran92** [comment]
Diff published D164000-code
