### ISSUE TITLE
Post-purchase Migration Experience: Redirect user according to state of migration

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95163]
**Description**

If a user tries to access any `wp-admin` / Calypso page (including their site's dashboard) on their new site, and that site has one of the following blog stickers, we should redirect as per this logic:

- `migration-pending` – Redirect to “How do you want to migrate?”.
- `migration-pending-diy` – Redirect to “Let’s migrate your site”.
- `migration-pending-difm` – Redirect to credentials screen.
- `migration-started-diy` – Redirect to Sites screen.
- `migration-started-difm` – Redirect to Sites screen.
- `migration-completed-diy` – No redirect.
- `migration-completed-difm` – No redirect.

pfuQfP-Hj-p2

**Comment by m1r0** [comment]
Blocking access on the pending migration state might be an issue when an existing site is used while going through the `/setup/hosted-site-migration` flow. For clarification, the site enters the pending state when the "I'll do it myself"/"Do it for me" option is selected.

The problem I see is that the user is losing admin access to an existing site (that could be live) and there's no way to cancel the migration process to get access back. I don't think it's a concern once the site enters the "started" state.

@fditrapani, WDYT?

**Comment by fditrapani** [comment]
Thanks for reaching out @m1r0. I've been thinking about this too. I'm starting to think that perhaps we don't block access during the pending migration state but do our best efforts everywhere to point people to the dashboard where they can track the migration status and resume where they left off (while still giving them a way to get back to their site). Here's an example of how the two can co-exist:

![Image](https://github.com/user-attachments/assets/72a6bd09-b5e2-4dd0-aaa2-4a12eee43867)

Let me know what you think.

**Comment by m1r0** [comment]
Closing the loop - this won't be implemented for now. p1728411453303989-slack-C07N53UNUQJ
