### ISSUE TITLE
Domains: Add Site Redirect to Calypso UI

### ISSUE THREAD

**Issue by wensco** [Automattic/wp-calypso#9517]
@supernovia recently mentioned that it is difficult for users to find the Site Redirect upgrade in Calypso. As far as I know, the only way to get to it is via a direct link, which is available in our [support documentation](https://en.support.wordpress.com/site-redirect/) or by contacting support to ask about it.

We need to investigate how much time and effort would be required to add this to the UI, including design input, so we can assign a priority, given that this is not a frequent user request.

**Comment by klimeryk** [comment]
FWIW, it's also in the site's Settings page:
<img width="779" alt="screen shot 2016-11-19 at 15 47 25" src="https://cloud.githubusercontent.com/assets/3392497/20456172/8cdcaea0-ae6f-11e6-9940-e1ef35d8c2b9.png">

See that cute little `redirect` link under `Site Address`? How could you have missed it? 😁

**Comment by wensco** [comment]
Thanks @klimeryk  - good to know it's there, but I think burying it under the "change site address" option makes it very hard to find and I think that placement is not very intuitive to most users.

**Comment by klimeryk** [comment]
Based on the discussion in https://github.com/Automattic/wp-calypso/pull/10300, I'm closing this issue. It seems this request is not very frequent and even when users ask about the redirect, what they _actually_ want is domain mapping. So putting it somewhere more prominent in Calypso, could lead to more support requests and user frustration.
I've updated the support doc, but only the section about removing the site redirect - no need to contact support, just remove it from purchases. The rest of the page seems up to date and clear.
All in all, this change could lead to more support load then actually lessening it :/
