### ISSUE TITLE
Reader: Better, less murdery "Back" from Full Post

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9519]
We're currently using browser history for the "Back" link (from fullpost to the stream, or tag to stream, etc), but that's buggy for various reasons (notifications, anything with an iframe). So the task here is to use another method to implement that action.

cc @blowery

**Comment by samouri** [comment]
Weird back-button bug as well:
1. Click an authors name in any stream and it will take you to a `SiteStream`.
2. the back button will appear
3. click the authors name repeatedly and it keeps adding new entries to your back history which is kind of weird and makes it require 2+ back button clicks to actual navigate away

**Comment by blowery** [comment]
We should probably disable the author link in site / feed streams

**Comment by fraying** [comment]
@blowery Is the author link on the site page _always_ a link to the page you're already on? If so, yeah, we should unlink it.

**Comment by blowery** [comment]
@fraying yup, every time. until we have user profiles, it'll probably stay that way.

**Comment by fraying** [comment]
👍
