### ISSUE TITLE
Free, Personal plan shouldn't prompt "Connect your account to continue using VideoPress"

### ISSUE THREAD

**Issue by formosattic** [Automattic/wp-calypso#95218]
### Quick summary

Site that are on a Free or Personal plan should just display `Upgrade to Premium to use this premium block`.

`Connect your account to continue using VideoPress` is not relevant for WordPress.com sites.

![Image](https://github.com/user-attachments/assets/8968fa77-2908-47cc-86a7-ecaa254cb562)

### Steps to reproduce

1. Create a free site
2. Add a VideoPress block

### What you expected to happen

Just a prompt to update to Premium plan.

### What actually happened

A prompt to connect to Jetpack also shows.

### Impact

Some (< 50%)

The confusing messaging may lead WordPress.com users down a wrong path and purchase Jetpack VideoPress.  This is not ideal for users and creates more work for support.

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Ignore the prompt to connect to Jetpack.

### Logs or notes

Context: internal discussion p7pQDF-9Ze-p2#comment-24978

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple site with a Free plan - Could't replicate the issue
 

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@formosattic is there any particular browser or steps we should be taking? I couldn't replicate this on my end yet using Chrome and proxied/unproxied displayed only the Premium plan banner.

**Comment by formosattic** [comment]
It seems it's been fixed, I can't reproduce it either. Look good now.

![Image](https://github.com/user-attachments/assets/898cd50a-82dc-4598-b616-04e08391fc6e)
