### ISSUE TITLE
Bug: Indented excerpts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9523]
The excerpt text in the posts on this site are all indented. Why?

http://wpcalypso.wordpress.com/read/feeds/42747358

![screen shot 2016-11-18 at 4 41 00 pm](https://cloud.githubusercontent.com/assets/24388/20451416/ce057762-adad-11e6-8d8a-53bd58cce959.png)

**Comment by jancavan** [comment]
It's odd how there's a bunch of `&nbsp;`s being added to the excerpts.

**Comment by fraying** [comment]
Could we strip out &nbsp;s in the excerpt generator?
