### ISSUE TITLE
Optimise data transfer on /themes

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [Automattic/wp-calypso#95248]
### Quick summary

The `/themes` page loads ~35MB of data on page load.

### Steps to reproduce

1. On Chrome, open dev tools, and keep the network tab open
2. Visit /themes page
3. Observe the data transferred over the network

### What you expected to happen

Data transferred to be in the ballpark of 5MB, similar to the "Pick a design" step in the signup flow

### What actually happened

Data transferred over the network is ~35MB. This is a significant amount of data to be transferring for a single page load. There was previously a related conversation on optimising the network transfer on "Pick a design" step in pdKhl6-3ds-p2. @danluu worked on image optimisations which led to a significant reduction in data transferred on this step. It would be great to apply that on the `/themes` page too.

This was discussed in p1728385843769819/1728381142.767659-slack-C02FMH4G8. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by xavier-lc** [comment]
I'll give it a go
