### ISSUE TITLE
Help Desk suggestion for Custom CSS points to inaccurate links and to Customizer, instead of Site Editor

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/wp-calypso#95242]
### Quick summary

The user explained in this video how it is confusing to search for Custom CSS in the help desk since it directs them to the Customizer instead of the Site Editor or Global Styles, and also the links are not pointing to the proper places:

User's video: https://www.youtube.com/watch?v=F4dpxdzqVHg

My recording of the issue: 
https://github.com/user-attachments/assets/63413700-49f3-496a-ac69-9cc178c47bc8

### Steps to reproduce

1. search for Custom CSS in the help desk
2. Customize my theme is pointing to the old Customize area instead of Global Styles.

### What you expected to happen

It would point me to Global Styles and the Add Custom CSS link would point me to the beginning of the support page instead of the Start Fresh anchor point.

### What actually happened

It leads me to the Customizer and to the bottom of the Add custom CSS support page.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by Robertght** [comment]
cc @Automattic/vertex

**Comment by escapemanuele** [comment]
Thank you @csabarakasz, I'll take care of this.

**Comment by csabarakasz** [comment]
Thanks!

**Comment by inaikem** [comment]
@escapemanuele, quick question for you: since this issue is closed, is there a reason the One Board status wasn't updated and the issue archived?

**Comment by escapemanuele** [comment]
I'm not totally sure @inaikem,  but here in Github I see:

```
inaikem moved this from Done 🎉 to In Progress in Automattic Prioritization: The One Board ™
```

![Image](https://github.com/user-attachments/assets/3e4fbbf0-452d-4821-a56e-d458233cc4c7)


Makes me think that it was Done, or that I saw it was set to Done?
