### ISSUE TITLE
Site Editor: Searching for a page causes page to go blank

### ISSUE THREAD

**Issue by rw-ye** [Automattic/wp-calypso#95243]
### Quick summary

When searching for a page in the "Pages" section of the site editor, it causes the entire page to go blank. I can consistently reproduce on both AT and Simple sites. 

Video:

https://github.com/user-attachments/assets/e68d633d-1bde-43f9-9587-94d036dd39ac

### Steps to reproduce

1. Make sure you have a FSE theme active.
2. Navigate to the site editor (Appearance > Editor)
3. Select "Pages"
4. Search for a page
5. The entire page will go blank

### What you expected to happen

To be able to search for a page

### What actually happened

The entire page goes blank

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The workaround is to use the "Pages" section on the site dashboard instead.

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Console errors:

![Image](https://github.com/user-attachments/assets/3846a2c8-2d16-454b-8fec-ab2f70798893)


📌 ACTIONS
- Triaged
- Marking this as Blocker

Weirdly, another similar thing I found yesterday but more specific to mobile use: https://github.com/Automattic/wp-calypso/issues/95072

**Comment by sejas** [comment]
I can reproduce the issue on simple and atomic when searching 

![Image](https://github.com/user-attachments/assets/ccfe696b-da8a-4a63-8e0f-0affb40de10c)

I see the same error in console:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at iS (index.min.js?m=1726663399i&ver=088cb1de53fe673a60d6:120:948)
    at index.min.js?m=1726663399i&ver=088cb1de53fe673a60d6:100:15607
    at index.min.js?m=1726663399i&ver=088cb1de53fe673a60d6:100:15902
    at index.min.js?m=1726663399i&ver=088cb1de53fe673a60d6:100:16007
    at Vr (VM45 react-dom.min.js:1:73191)
    at Cl (VM45 react-dom.min.js:1:92835)
    at dl (VM45 react-dom.min.js:1:85243)
    at Nn (VM45 react-dom.min.js:1:32432)
    at VM45 react-dom.min.js:1:91667
    at El (VM45 react-dom.min.js:1:91672)
```

I tested it on a non WPcom site and I see a similar behaviour in core. When searching a page the whole page turns "gray" and stays like that until the user clicks anywhere. The biggest difference is that WPcom throws an error in console and "crashes".

https://github.com/user-attachments/assets/19c9834c-0ff4-494c-a50e-c617a3030a32

**Comment by sejas** [comment]
I've tested a regular site (non WPcom) with Gutenberg 19.4.0 and I don't see the "blinking" anymore.

I've also tested a simple site using the sticker `gutenberg-edge` [v19.4.0-rc1](https://github.com/Automattic/wp-calypso/issues/95123) and I confirm that version of Gutenberg fixes the issue. You can add the Sticker `gutenberg-edge` to try it.

It seems that Gutenberg had an issue that cleared the dom when searching and that produced a conflict with some of our custom code. I'll see if I can find where it conflicts in WPcom side.

**Comment by donnapep** [comment]
@sejas Our team is currently on the Gutenberg rotation. The plan is to release Gutenberg 9.4.0 next week, but @Imran92 can confirm. 🙂

**Comment by Imran92** [comment]
Hi @obenland 👋 

I've already released v19.4.0 on simple edge sites.

Posted a CFT here  pdtkmj-321-p2 and cross-posted to Nexus, Bespin and Caribou for quick turnaround.

I'll try to release before Thursday EOD to avoid releasing on Friday if everything goes as expected.

Thanks!

cc: @donnapep

**Comment by Imran92** [comment]
v19.4.0 is released on simple sites.

The release build for AT is also in the right repo. AT will pull it following their schedule [p9o2xV-3Ov-p2#comment-8716]

**Comment by obenland** [comment]
Thank you for getting it out before the weekend @Imran92!

**Comment by donnapep** [comment]
Retested on both Simple and Atomic and confirm that this has been fixed. 🥳
