### ISSUE TITLE
Jetpack Personal Plan causes browser crash?

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-calypso#9529]
I purchased a Personal Plan for a Jetpack testing site (using credits), and didn't finish setting it up. Now, when I view My Sites in Calypso, with the site selected, I see this:

![screen shot 2016-11-19 at 5 41 12 pm](https://cloud.githubusercontent.com/assets/108942/20459500/9c29c904-ae80-11e6-80dd-72d0a39484be.png)

After a few seconds of seeing this, Chrome kills that process (confirmed via Task Manager that it seems to be spiking rapidly in memory usage). After killing it, I see:

![screen shot 2016-11-19 at 5 48 47 pm](https://cloud.githubusercontent.com/assets/108942/20459502/b5fa77ac-ae80-11e6-98f2-c38749cf6655.png)

If I change my URL so that this site is not selected, then Calypso works fine. As soon as I switch back to this specific site, things spiral out of control and in a few seconds the tab/process crashes again.

I believe there's some kind of memory leak going on, either in relation to the site not being completely configured, or perhaps just the Personal Plan?

There are no errors in the console, and the React DevTools don't get a chance to connect before the tab crashes.

**Comment by beaulebens** [comment]
I've narrowed this down as only happening on the Stats > Insights view (which is, unfortunately, the first view after clicking on My Sites).

**Comment by beaulebens** [comment]
I managed to access the "FINISH" prompt from a different view (and completed setting up my plan). Once that was complete, the Insights view no longer crashes! So apparently there's some conflict between having that message visible, and something on the Insights view.

**Comment by beaulebens** [comment]
Actually -- Now I'm seeing the same browser crash on a .com site (not Jetpack), and which has a different plan fully configured.

**Comment by beaulebens** [comment]
Seems to have been something in my `localStorage`, or some other caching perhaps. I logged out of WordPress.com, and back in, and now everything appears to be loading/working as expected.

**Comment by beaulebens** [comment]
I've just hit this again, which makes me think I'm not the only one hitting it. I purchased another Personal Plan, for another Jetpack site (this one hosted on Pressable). I don't know if that's related.

Again, the crash only happens on the Insights view, and appears to affect all of my sites. Within about 5 seconds of switching to that view, the browser crashes as described in the initial report.

**Comment by beaulebens** [comment]
If I load my account in Chrome Canary, Firefox or Safari, I don't see the problem. This suggests some kind of corrupted localStorage or local caching of some sort to me, but it's a pretty catastrophic result of that happening.

**Comment by hoverduck** [comment]
I saw this problem a few months ago as well, and only got out of it by clearing my browser cache / localStorage.  I assumed I caused it by corrupting something during testing, but I could never figure anything out to reproduce it.

**Comment by jblz** [comment]
I'm currently experiencing this. I _do_ have a site with a personal plan, but am crashing in the same manner as described above ("Aw, snap!" on the insights page after "mostly" loading -- nothing in the console).

It also does it on these pages (at least):
* https://wordpress.com/stats
* https://wordpress.com/stats/day
* https://wordpress.com/stats/week
* https://wordpress.com/stats/month

My user has multiple sites, if I include the site slug in the above (e.g. `https://wordpress.com/stats/day/site_slug_here`), it loads without issue.

...so it's not just the insights page.

Let me know if there's anything else I can do to troubleshoot.

/cc @timmyc -- you may have some ideas!

**Comment by jblz** [comment]
@timmyc It's not happening in Firefox for me -- only Chrome.

Also, not able to trigger it anywhere except stage and production (aka, on the `wordpress.com` domain).

I was able to get a partial stack trace with Chrome's [logging feature](http://www.chromium.org/for-testers/enable-logging):

```
    1: /* anonymous */ [https://wordpress.com/calypso/build-production.0d3355448f5e47f292ff.min.js:~12] [pc=0x777decea5](this=0x3721f2b0ef39 <JS Global Object>,subValue=0x20bccab82311 <undefined>,key=11184811)
    2: arguments adaptor frame: 3->2
    3: arrayEach [https://wordpress.com/calypso/build-production.0d3355448f5e47f292ff.min.js:~12] [pc=0x777decf53](this=0x...```

I don't see any instances of `arrayEach` in the wp-calypso codebase, so my best guess is some incompatibility or conflict with the webpack build / minification process or our config.

**Comment by jblz** [comment]
Using "Pause on exceptions" in the Chrome inspector has no effect.

If I also pause on caught exceptions, the last place it stops before crashing is in a notifications-related [bootstrap script](https://widgets.wp.com/notificationsbeta/webpack:/webpack/bootstrap%20d85f1beecde5aa35f824):

**Comment by timmyc** [comment]
@jblz it is kind of sounding like it is something in indexDB that is specific to stage/production on chrome since the crash isn't happening in Firefox.

Curious to see how large your indexdb database is - can you paste the following snippet into your console: https://raw.githubusercontent.com/jonnysmith1981/getIndexedDbSize/master/getIndexedDbSize.js

enter `calypso` for the db name when prompted

**Comment by jblz** [comment]
I did a bit of troubleshooting with @timmyc and was able to isolate the cause (for me, at least):

A `data` key in the redux store just below `state.stats.lists.items[siteId].statsStreak` was incorrectly being persisted as an `Array` instead of an `Object`.

The array was the size of the `siteId` with a single value at `siteId - 1` (maybe if I posted more, it would've fix it itself!!).

The API response was properly formed as an object.

Doing the following "fixed" things:

```
indexedDB.open('calypso').onsuccess = (e) => {
    const db = e.target.result;
    const transaction = db.transaction( 'calypso_store', "readwrite" );
    const store = transaction.objectStore( 'calypso_store' );

    store.get( 'redux-state' ).onsuccess = (ee) => {
        const state = ee.target.result;
        delete state.stats.lists.items[siteId].statsStreak;
        store.put( state, 'redux-state' );
    }
};
```

It's noteworthy that the site in question for me _does_ have a Jetpack Personal Plan.
However, it might be unrelated to the plan & just that it was the most recent site I added to my account.

**Comment by timmyc** [comment]
Big props to @jblz for all of the time today troubleshooting with his broken state tree.  The ability to reproduce this locally led to a fix in #10326

**Comment by beaulebens** [comment]
Wow, this is awesome that you managed to find enough data to track down and fix this -- nice work!

**Comment by timmyc** [comment]
> Wow, this is awesome that you managed to find enough data to track down and fix this -- nice work!

I'm hopeful this is the same bug you hit @beaulebens - it _feels_ a bit different then the one I had experienced a few weeks back, so we will see!
