### ISSUE TITLE
"Full post" being displayed in the new post emails even if the "Excerpt" option is turned on

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#95309]
### Quick summary

Even if we set an excerpt and have it set under Settings > Writing, the full blog post is being display in the email notification.

### Steps to reproduce

1. Go to Settings > Reading and set under "RSS feed settings" to "Excerpt"
2. Create a new post and add content to it
3. Set an excerpt and publish it
4. Check results

### What you expected to happen

The excerpt text should be displayed in the email notification.

### What actually happened

It displayed the full post  in the email notification.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Using the More block can help go around this.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

So far tested on Simple sites due to lack of time.

Previous ref: https://github.com/Automattic/jetpack/issues/34372#issuecomment-1833938949 cc @ivan-ottinger if you're still working on these

Also confirmed here: p1728635005695919-slack-C03TY6J1A by @mxhassani

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate


📌 ACTIONS
- Triaged
- Replicated on Simple sites only.

**Comment by tanjoymor** [comment]
Another report: 8762178-zd-a8c

This user also has the Settings > Newsletter option set to "Excerpt" as well as the Settings > Reading option. Their latest post email notification contained the full post.

**Comment by ivan-ottinger** [comment]
> Previous ref: https://github.com/Automattic/jetpack/issues/34372#issuecomment-1833938949 cc @ivan-ottinger if you're still working on these

Thank you for the ping, Robert!

I am heading for AFKs so probably won't have enough bandwidth to take a deeper look at this issue this time, but someone from @Automattic/apex may be able to take a closer look.

When it comes to the issue itself, if I recall correctly, we have previously decoupled the RSS feed setting from the Newsletter's setting:

![Image](https://github.com/user-attachments/assets/35adb67f-f4c2-4066-9f09-f7892dc853fc)

These two settings should work separately: One for RSS only and one for email newsletter only.

**Comment by phcp** [comment]
> When it comes to the issue itself, if I recall correctly, we have previously decoupled the RSS feed setting from the Newsletter's setting:

Indeed, we have two site options: one for newsletters `wpcom_subscription_emails_use_excerpt`, and the other for RSS `rss_use_excerpt`. To set the newsletter option, the user must go to **Settings > Newsletter**.

> This user also has the Settings > Newsletter option set to "Excerpt" as well as the Settings > Reading option. Their latest post email notification contained the full post.

The email excerpt works consistently in my tests with other simple sites. So, I checked this specific site, and the `wpcom_subscription_emails_use_excerpt` is missing in the database, so it defaults to the full-text email format. @tanjoymor, I can try switching it to full-text and then back to excerpt to verify that the option will be set correctly in the database. If it doesn't work, it may be related to the setting field or the settings API side and will require more research. How does that sound to you?

**Comment by tanjoymor** [comment]
@phcp apologies, I missed this ping. Yes that sounds good to me to try that.

**Comment by caitlindawn** [comment]
Reported in 8854889-zen

**Comment by Robertght** [comment]
@phcp this appears to be already fixed in https://github.com/Automattic/wp-calypso/issues/95469 but I can see a new report here and in the other GH issue.

@lezama do you have a few minutes to review this further?

**Comment by devNigel** [comment]
Another report: 8894793-zd-a8c

**Comment by lezama** [comment]
> Another report: 8894793-zd-a8c

Hey @devNigel, the screenshot the user provided is from before the fix, when picking "the excerpt" was still delivering the full post. I’ve checked it now, and the setting was correctly displaying as “Full Post.” I’ve already updated it to “Excerpt” for them.

**Comment by lezama** [comment]
> Reported in 8854889-zd-a8c

@caitlindawn @Robertght I checked this user site and it has the setting set to "Full post" they need to set it as "Excerpt" to get back the "read more" links.

> I tried clicking on "show excerpt", but that doesn't help. In the email, after the text it only gives "Comment" or "Like", not "Read post

Are they perhaps changing the RSS settings instead of the Newsletter settings?

**Comment by ariel-maidana** [comment]
@lezama I checked their newsletter settings and noticed they have them set to "Full text". I asked them to change it to "Excerpt".

**Comment by phcp** [comment]
Closing this issue since all reports were solved. Feel free to reopen if anything related comes up.
