### ISSUE TITLE
Feature Request: Add "Delete Site" to Kebab Menu at wordpress.com/sites

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#95300]
### What

Add "Delete Site" to Kebab Menu at wordpress.com/sites

### Why

Sometimes users end up with a big list of sites and need to delete/disconnect unwanted ones.  Right now they have to go to the site settings to delete, but this would help them speed up the process. And, now that people can restore deleted sites on their own, there's no much risk with putting it here.

### How

![Image](https://github.com/user-attachments/assets/020cfa4b-b2dc-4a39-a3fc-f25aaee8c8e6)

**Comment by supernovia** [comment]
Via ZD feedback from 8257540-zd-a8c

**Comment by tanjoymor** [comment]
This would be a terrific enhancement for users, reducing steps to delete unnecessary sites, and would reduce support interactions by making the delete option more visible.

I'm wondering which team a /sites page enhancement would fall under:
@Automattic/quake 
@Automattic/lego 
@Automattic/t-rex 

Based on the information here: PdqkMK-1nV-p2 I've assigned this to Lego, please correct me if this is wrong.

**Comment by lsl** [comment]
The dropdown fields are defined in here: https://github.com/Automattic/wp-calypso/blob/trunk/client/sites/components/sites-dataviews/actions.tsx

Added to our board but anyone is welcome to pick this up.
