### ISSUE TITLE
Long domain/subdomain names appear disruptive on the Email step

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#95305]
### Quick summary

This is a consequences of testing this one: https://github.com/Automattic/wp-calypso/issues/95110#issuecomment-2406590459

### Steps to reproduce

1. Try to add a very long domain/subdomain name
2. Check the second step(Email)

### What you expected to happen

The fields should remain fairly the same size

### What actually happened

Instead the first one got very small and the domain one increased too much overlapping content on the right side

![Image](https://github.com/user-attachments/assets/b593910b-dcae-423a-9274-708bf14f947c)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
cc @renancarvalho 

Marking as Triaged

**Comment by Aurorum** [comment]
PR in #95331. :)
