### ISSUE TITLE
Help Center: Ordered lists have wrong margin and list style

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#95326]
### Quick summary

Unordered lists are styled with `margin: 0 0 1.5em 1.5em` and `list-style-position: inside;`. Ordered lists are not. See the screenshots:

<img width="400" src="https://github.com/user-attachments/assets/753e3cbf-d282-43f7-90d8-e264b53f5e1e" />
<img width="400" src="https://github.com/user-attachments/assets/ff0588c6-d9ab-4bc8-b263-83bc2076d1ea" />

### Steps to reproduce

1. Have an Atomic site
2. Navigate to `/hosting-config/:site_slug`
3. Scroll down to the `Defensive mode` card
4. Click the `Learn more` link
5. In the Help Center, scroll down to the ordered list below `To enable defensive mode, take the following steps`

### What you expected to happen

The list should have the correct margin and list style.

### What actually happened

The list has the wrong margin and list style.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Suggested solution: https://github.com/Automattic/wp-calypso/pull/95120#issuecomment-2393849559

**Comment by escapemanuele** [comment]
I approved the PR, but I was just considering that maybe the before version is more readable?

![Image](https://github.com/user-attachments/assets/d543bc86-f101-4f87-87dc-9654c08d1a09)

Also on the website it is like in the before screenshot
