### ISSUE TITLE
Fix the broken course videos

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#95338]
The issue was noted in the self-serve interview here: p2-pau2Xa-6jH. 
The videos in `/setup/site-setup/courses` are unplayable:

https://github.com/user-attachments/assets/4e8d32a8-f468-4df5-8bef-1ea200fe2fcb

## Steps to reproduce
1. Log in to any existing account
2. Visit `/setup/site-setup/courses?siteSlug=<site url>`
3. Click on any of the videos and confirm they are not playable.

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested in Chrome and Firefox with two accounts; could not reproduce

📌 ACTIONS
- Triaged
- Requested author feedback


📌 Message to Author
@southp I couldn't reproduce this and am wondering if you have already solved it. Do you need anything from PAs? I'm marking this as triaged for now, but if you need us to triage this please move it back to Needs Triage in The One Board. Thanks!

**Comment by southp** [comment]
Thanks for looking into it, @supernovia . 
After studying further, it looks like a Chromium specific issue, which is my browser of choice for development tasks. The video is encoded in H.264 format, and [it is not supported by Chromium by default](https://chromium.woolyss.com/#html5-audio-video).

I'm closing this since it likely doesn't affect any real user. If we want we can likely show a message saying some codec is missing, but it's likely not worth the effort at the moment.
