### ISSUE TITLE
Update the call to formatCurrency to eliminate warnings in the plans page

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#95336]
Currently there are loads of `formatCurrency` warnings when visiting any page with the plans grid, e.g. the following screenshot was taken from the logged-in /plans:

![Image](https://github.com/user-attachments/assets/11f8effa-d268-4b77-95e9-f696ee5182dc)

The warning is meant to highlight the calls that should be updated, so let's update the call accordingly to eliminate the warnings.

**Comment by jeyip** [comment]
https://github.com/Automattic/wp-calypso/pull/95369

**Comment by jeyip** [comment]
I created a follow-up issue to investigate why the add-on cost calculations are re-rendered dozens of times for identical return values, even though the logic is memoized
