### ISSUE TITLE
Header Bar Login CTA link not working

### ISSUE THREAD

**Issue by stronenv** [Automattic/wp-calypso#95358]
### Quick summary

The Login redirect link doesn't work in the Header Banner that shows the Login CTA for the first 24h after you've attached a domain to a simple site.

### Steps to reproduce

1. Set up a fresh simple site
2. Launch it / attach a domain
3. The "Is this your new site? Log in to activate admin features and dismiss this message" header bar should appear on the site
4. Click Log in and follow the steps.
5. You'll get redirected to a blank page on https://r-login.wordpress.com/remote-login.php?action=link&back=%2F
6. Message is not dismissed. 

### What you expected to happen

Be able to log in, and the message to be dismissed. 

I can log in to my account, so it would be good to have a way to dismiss the message from the Site Editor or Dashboard. It sounded like I would "find" that option in the WP Admin once I was signed it. 

### What actually happened

Got redirected to a blank page on https://r-login.wordpress.com/remote-login.php?action=link&back=%2F

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could not replicate -- could not see CTA bar at all

📌 FINDINGS/SCREENSHOTS/VIDEO
![Image](https://github.com/user-attachments/assets/38a593a7-890d-4d1b-abc4-418037dae880)
![Image](https://github.com/user-attachments/assets/84e3a354-c195-432f-badd-055228cb6e46)


📌 ACTIONS
- Triaged
- Requested author feedback


📌 Message to Author
@stronenv I can't get the login header CTA to come up at all right now. If I'm logged in, I see the normal bar. If I'm logged out, I don't get a CTA. I tried with and without proxy. Are there other circumstances needed to see the CTA bar with login?

**Comment by stronenv** [comment]
Thanks for checking this out, @supernovia! The header bar is only visible within the first 24 hours after you connect the domain. 

I noticed I also upgraded the site to the Premium plan prior to adding the domain. 

Here's the banner for reference:
![Image](https://github.com/user-attachments/assets/605b8afb-e07c-4a5d-ab13-8e737c510f07)

**Comment by jartes** [comment]
Thanks for the additional info, @stronenv 

While I was able to get the banner, I'm getting redirected correctly: 

https://github.com/user-attachments/assets/82b49b96-265b-407e-b625-533f0c44802f

This is the full link: 

```
https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fr-login.wordpress.com%2Fremote-login.php%3Faction%3Dlink%26back%3Dhttps%253A%252F%252F0testdelete.blog%252F2024%252F10%252F16%252Fhello-world%252F
```

Are you still getting the link that is not working?

**Comment by stronenv** [comment]
It was after login. I realize the naming of the issue wasn't the best description 🙃  But steps 4 and 5 in [Steps to Reproduce](https://github.com/Automattic/wp-calypso/issues/95358#issue-2586225835) above are where the issue happened.  

Also, after you're logged in, the message should be dismissed. Did that happen on your end, @supernovia ?

**Comment by supernovia** [comment]
@stronenv I don't see any message, whether I'm logged in or not. I added a new domain for the test and shared screenshots above.

**Comment by stronenv** [comment]
Hmm. It's notoriously hard to debug this if we need to keep buying new domains every 24h 😅 
Do you know if there's a URL parameter or cookie we could set to make it show up?

**Comment by supernovia** [comment]
@stronenv  I don't ... I'm wondering though, I bought the domain while logged in (of course), but had to log back out again to look for any messaging prompting me to log in. Does it matter how I logged out?

**Comment by stronenv** [comment]
No, sorry. I don't know how the dynamics of that works.

**Comment by BogdanUngureanu** [comment]
@supernovia @stronenv I've managed to reproduce the issue. Initially I couldn't, but it seems that after you remove the Hello World post, the user is then redirected to `https://r-login.wordpress.com/remote-login.php?action=link&back=%2F` where they get a blank page. 

I'll look into it. :)

**Comment by BogdanUngureanu** [comment]
Opened D164219-code that fixes the issue. :)

**Comment by stronenv** [comment]
Hi @BogdanUngureanu! 

Yes, I can confirm that it works as expected now. I've tried with a new blog and a new domain, deleting the Hello World post, and I got redirected correctly after login. Thanks both for working on this 🙌
