### ISSUE TITLE
Post-purchase Migration Experience: Handle selecting a DIFM site in the Sites dashboard that is pending migration

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95379]
## Description
When a user clicks on a site in the Sites dashboard that has the `migration-pending-difm` sticker, display a detailed view communicating that the site is ready to be migrated.

Clicking on the _Start your migration_ button goes to the _Tell us about your WordPress site_ (i.e. credentials) step of the migration flow. We should ensure that this button click can be analyzed in Tracks funnels so that we can discern that the user entered the flow from the Sites dashboard.

Figma - nOWSHCjXMpB5sXHthTVdvK-fi-3949_19810

![Image](https://github.com/user-attachments/assets/b23eba95-c73a-44ea-affa-1264a466d9e8)

**Comment by Imran92** [comment]
Hey @renatho ! Looks like the issue https://github.com/Automattic/wp-calypso/issues/95383 issue will depend on the completion of this issue right?

So I'm not picking this up because otherwise we may end up working on creating the same structure :p
