### ISSUE TITLE
Post-purchase Migration Experience: Site title not updating on the dashboard after migration

### ISSUE THREAD

**Issue by m1r0** [Automattic/wp-calypso#95377]
## Description

After a successful migration, the site title is not updated on the `/sites` dashboard, probably due to cache.

## Steps to reproduce

- Create a jurassic.ninja site and take note of the site title.
- Go through `/setup/migration-signup/`, select "I'll do it myself", and complete the migration.
- Go to your newly migrated site, open `yoursite.wpcomstaging.com/wp-admin/options-general.php`, and verify that the site title got migrated.
- Go to `/sites`, you will see that the title update is not reflected there.

![Image](https://github.com/user-attachments/assets/c4560449-eb9a-43b3-a7d8-eccca2f581ae)

**Comment by cuemarie** [comment]
+1

I'd love to see this get updated!  This impacts all self-serve migration customers; here's an example of a customer reporting the issue on 5 sites they migrated in: 8940806-zen

Reported in Slack here: p1730094152463739-slack-C06PZC1RR5F

This also impacts all HE-managed migrations; we manually schedule a checksum and fix via the JPBD for every migrated site to get that updated.

**Comment by cuemarie** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/92968

**Comment by m1r0** [comment]
I've suggested a fix in D166081-code.

**Comment by m1r0** [comment]
This is fixed by the above. 🙂
