### ISSUE TITLE
Post-purchase Migration Experience: Handle selecting a site in the Sites dashboard that is pending migration

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95380]
Dependent on #95379.

## Description
When a user clicks on a site in the Sites dashboard that has the `migration-pending` or `migration-pending-diy` sticker, display a detailed view communicating that the site is ready to be migrated.

Clicking on the _Start your migration_ button goes to the:
- `migration-pending` - _How do you want to migrate?_ step of the migration flow.
- `migration-pending-diy` - _Let's migrate your site_ (i.e. migration instructions) step of the migration flow.

In either case, we should ensure that the button click can be analyzed in Tracks funnels so that we can discern that the user entered the flow from the Sites dashboard.

Figma - nOWSHCjXMpB5sXHthTVdvK-fi-3949_19810

![Image](https://github.com/user-attachments/assets/b23eba95-c73a-44ea-affa-1264a466d9e8)

**Comment by renatho** [comment]
I'll implement this in parallel with https://github.com/Automattic/wp-calypso/issues/95379 since it will have the same logic, just redirecting to a different link after clicking on the CTA.
