### ISSUE TITLE
Post-purchase Migration Experience: Handle selecting a DIFM site in the Sites dashboard that has started migration

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95383]
## Description
When a user clicks on a site in the Sites dashboard that has the `migration-started-difm` sticker, display a detailed Overview communicating what the user can expect.

Figma - nOWSHCjXMpB5sXHthTVdvK-fi-3949_19811

![Image](https://github.com/user-attachments/assets/314aea61-6db1-4a30-a722-f08033f282fc)

**Comment by Imran92** [comment]
Moving it to blocked till this https://github.com/Automattic/wp-calypso/issues/95379 one gets completed

**Comment by renatho** [comment]
When working on this, we could remove [this check](https://github.com/Automattic/wp-calypso/pull/95497/commits/7d7672861c61af89443cad1252360b6971ab2d81), and also implement this logic in the `MigrationOverview` (maybe splitting it between pending and started?).
