### ISSUE TITLE
Limited Global Styles on Personal

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#95396]
Update the Global Styles gating to be available on the Personal plan.

### Global Styles Availability

| Plan | Before | After |
|--------|--------|--------|
| Free | ❌ | ❌ |
| Personal | ❌ | ✅ |
| Premium | ✅ | ✅ |
| Business | ✅ | ✅ |
| Commerce | ✅ | ✅ | 

### Current Plan

- Determine whether we should run another A/B test, or temporarily release it to all and quickly and painlessly revert if needed.

### Useful Links

- 2023 experiment PT: paYJgx-3tS-p2
- 2023 experiment summary: pbxNRc-2HR-p2
- 2023 experiment analysis: paYJgx-3PM-p2
- 2023 experiment post-mortem: paYJgx-3FM-p2
- 2024 framing: paYJgx-5u5-p2
- 2024 Project Thread: paYJgx-5w2-p2

**Comment by richtabor** [comment]
For clarification, this is to gate global styles to `Personal` correct, down from the current plan. Not to have limited global styles on personal?

**Comment by Copons** [comment]
@richtabor Exactly! I'm reusing the same phrasing we have been using for at least two years — which admittedly can be confusing for anyone who hasn't followed its development.

I'll clarify this in the issue description.

**Comment by richtabor** [comment]
> Determine whether we should run another A/B test, or temporarily release it to all and quickly and painlessly revert if needed.

Historically, what's been the path forward. And what would be grounds for reverting?

**Comment by dsas** [comment]
>  what would be grounds for reverting?

Presumably revenue tanking. It'd be really rather lovely to quantify this upfront, so that if revenue does noticeably decrease then we can act quickly and decisively.

**Comment by Copons** [comment]
We have been monitoring GS-related data for years and have a decent idea of how it trends: paYJgx-5tg-p2.

I think that _if_ we lose revenue, whatever we lost, we'd gain in number of upgrades — which is arguably more important in the long run.

**Comment by rcrdortiz** [comment]
@copons Once we get a green light on this PT I'll start adding issues.

**Comment by dsas** [comment]
@rcrdortiz I've reconfirmed with @Copons that we have a green light, so long as changes are behind a feature flag.

**Comment by Copons** [comment]
Quick update for the curious onlookers: We have updated the ETA from Friday, November 15, to Monday, November 18, to clarify that we won't be launching on a Friday.

We are still aiming to launch early, but since there are many interested parties, it's essential that we are all on the same page.

**Comment by rcrdortiz** [comment]
Closing the main issue, we still have pending actively monitoring the results. I don't think we nee this issue here as a reminder though.
