### ISSUE TITLE
Reader: display follow errors in the appropriate position

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#954]
Raised by @bluefuton 

When a follow or unfollow error is encountered, we always show the error on the post card:

<img width="692" alt="screen shot 2015-09-30 at 15 40 28" src="https://cloud.githubusercontent.com/assets/17325/10209089/002daab0-678d-11e5-82e1-b87c418aec90.png">

...and it persists in the full post view if the user doesn't dismiss it.

This sometimes feels a bit odd. We should perhaps store the origin of the follow, so we can display the error in the appropriate places.

Note from @designsimply

> Error for reference:
> 
> ```
> Sorry, we couldn't follow this site. Please try again in a while. 
> ```

**Comment by blowery** [comment]
Need to determine if this is still a problem

**Comment by blowery** [comment]
Yup, still a problem. Moving to feature backlog.

**Comment by alisterscott** [comment]
The error notice seems to appear at the very top now regardless:

<img width="1196" alt="screen shot 2017-05-11 at 1 23 08 pm" src="https://cloud.githubusercontent.com/assets/128826/25931021/0bd1cabe-364d-11e7-8ee7-362ed1572ce3.png">

And it doesn't seem to follow to full post view.

Closing this and we can raise a separate issue if the current display is not correct.
