### ISSUE TITLE
Changing Paragraph Block Color Also Affects Link Color, Making Links Invisible

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/wp-calypso#95403]
### Quick summary

When I change the color of a Paragraph block, the link color is also changed to the same color, which could make the links invisible for users on both the frontend and the editor.

### Steps to reproduce

1. Theme used: https://wordpress.com/theme/bain-marie/
2. Go to My Sites -> Site Editor.
3. Add a few Paragraph blocks.
4. Go to the block's color settings.
5. Add a few links to the Paragraph block.
6. Apply color to the text only, and notice the text color is also applied to the links.

Short video: 

https://github.com/user-attachments/assets/91d38751-9d21-42b7-b74e-b68b3fa2ea82

### What you expected to happen

By default, the text color shouldn’t be applied to the link color.

### What actually happened

The text color is currently being applied to the link color as well.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

We can change the link color from the link color option again.

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- These are my results:
![GLdsSQ.png](https://github.com/user-attachments/assets/430be154-880e-41ba-8766-0b52ec2609f9)
The colors are consistent on the frontned.

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@mdtanjid0 please reopen if you're still seeing this and let us know if this happens on a Simple/Atomic or self-hosted website.
