### ISSUE TITLE
Post-purchase Migration Experience: Update "We'll take it from here!" step of migration flow

### ISSUE THREAD

**Issue by donnapep** [Automattic/wp-calypso#95404]
Update the last step of the DIFM flow to send people to the Sites dashboard to monitor the progress of their migration. Clicking the button should take the user to their Sites dashboard (https://wordpress.com/sites).

Figma - nOWSHCjXMpB5sXHthTVdvK-fi-3919_14181

![Image](https://github.com/user-attachments/assets/1b87e423-568e-4402-9379-d68ab163b653)

**Comment by sixhours** [comment]
I noticed the mockups in this issue and #95565 have a similar proposal (add a button pointing to the `/sites` dashboard) but the button uses different copy/capitalization. Should these be standardized? @fditrapani

**Comment by sixhours** [comment]
@fditrapani I noticed this screenshot has multiple changes in addition to the button -- should I be updating the current screen (screenshot in https://github.com/Automattic/wp-calypso/pull/95762) to match the screenshot here or just add the button? Thanks!!

**Comment by fditrapani** [comment]
Thanks for checking @sixhours. In addition to adding the button, we'll need to make the following updates:

- Update the copy for the timing of the migration to reference the sites dashboard:
  ![Image](https://github.com/user-attachments/assets/93fc3808-f73b-4b40-b6cd-f8a3249a53df)
- Hide the Explore and Learn buttons.

**Comment by fditrapani** [comment]
After digging up this last update, perhaps we should update the case from `sites dashboard` to `Sites dashboard` in all instances.

**Comment by sixhours** [comment]
Updating the sentence: "You can also check the progress of your migration your Sites dashboard." 

to

"You can also check the progress of your migration _from_ your Sites dashboard."

LMK if that's not the intended wording!

> Hide the Explore and Learn buttons.

I don't think this screen is shown in multiple contexts, so I believe these cards/buttons can be removed entirely rather than hidden, but let me know if I'm missing something.

**Comment by fditrapani** [comment]
> Updating the sentence: "You can also check the progress of your migration your Sites dashboard." to "You can also check the progress of your migration from your Sites dashboard."... LMK if that's not the intended wording!

Good catch again :D Looks great thanks! 

> I don't think this screen is shown in multiple contexts, so I believe these cards/buttons can be removed entirely rather than hidden, but let me know if I'm missing something.

Let's do it. We can always add them back if we missed something but I don't think we have.
