### ISSUE TITLE
Stats: Follower list won't load beyond page 1

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#9542]
#### Steps to reproduce
1. Starting at URL: wordpress.com/stats/follows/wpcom/yoursitehere.wordpress.com
2. Make sure it is on a site that has over 20 followers/that will show multiple pages of results.
3. Click the Next Page arrow or numeric link to view the next page
4.

#### What I expected
For the next page of followers to load.

#### What happened instead
In some cases the URL changed briefly to that for the next page, but then returned to page one. The content on the page goes blank for a moment, then reappears showing the first page of results.

Manually linking directly to the next page, e.g. wordpress.com/stats/follows/wpcom/2/yoursitehere.wordpress.com, simply reloaded the first paeg of results.

#### Browser / OS version
Confirmed in the latest versions of Chrome, FF, Safari and IE11 across Win 7, Win 10 and Mac OS X Sierra.

#### Context / Source

Reported in the WordPress.com public forums: 

http://en.forums.wordpress.com/topic/list-of-followers-5

**Comment by timmyc** [comment]
This appears to also be a regression caused by #9445 - further details [here](https://github.com/Automattic/wp-calypso/issues/9550#issuecomment-262122111)

**Comment by KokkieH** [comment]
Works again for me as of a few hours ago. Thanks for the speedy fix.
