### ISSUE TITLE
Email excerpt newsletter setting being ignored

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#95469]
## Description

A Business plan customer reported [on his blog](https://hughsviewsandnews.com/2024/10/15/is-this-wordpress-problem-affecting-you-its-been-reported/) and on our newly created [Reader customer council blog](https://readercouncilgeneral.wordpress.com/2024/10/15/general-feedback/#comment-19) that the newsletter excerpt setting stopped working a week or so ago.

He forwarded me a copy of the email that was sent out for the blog post linked above:

![Image](https://github.com/user-attachments/assets/65737970-7730-4b6f-a23f-4c4d460ce606)

I logged into his account and he indeed has emails set to just show excerpts:

![Image](https://github.com/user-attachments/assets/ed51d32c-64cd-435f-8ed3-e344a1ec3a3c)

I double checked and there is an excerpt set for [this post](https://hughsviewsandnews.com/2024/10/15/is-this-wordpress-problem-affecting-you-its-been-reported/).

## Testing the issue

Status: **Replicated**

I went into my test blog and made sure that the excerpt setting was selected:

![Image](https://github.com/user-attachments/assets/eb8bacf8-65ab-453f-a82d-9e3e43ca52e4)

I then published this test post with a short excerpt:

![Image](https://github.com/user-attachments/assets/29366ea2-9f3a-442a-9089-543defc53790)

And here's the email I received:

![Image](https://github.com/user-attachments/assets/fdd29926-a61c-443d-8638-69d63af4d4de)

## Expected

If the excerpt option is checked, emails should only include the excerpt text, prompting readers to click to read more.

## Actual

The excerpt newsletter option is ignored.

## Related issues

https://github.com/Automattic/wp-calypso/issues/82815 may be related, but I suspect it isn't since this just seemed to crop up a week or so ago.

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Not replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested with and without custom excerpts, with and without more tags, on both Atomic and Simple
- Both Atomic and Simple respect the "more" tag and only send content before that, but only Atomic respects the excerpt (whether custom or generated from the first few lines of content)

📌 ACTIONS
- Triaged

**Comment by supernovia** [comment]
8857355-zd-a8c - I'm having them use the "more" tag for now

**Comment by supernovia** [comment]
8871914-zd-a8c (original reporter)

**Comment by supernovia** [comment]
8892498-zd-a8c

**Comment by lezama** [comment]
I am looking into this

**Comment by supernovia** [comment]
8853385-zd-a8c -- just noting cases in case we want to follow up with users. Thanks for working on this!

**Comment by davipontesblog** [comment]
8863292-zd-a8c

**Comment by ariel-maidana** [comment]
8848542-zd-a8c

**Comment by mauropereiira** [comment]
8899887-zd-a8c
