### ISSUE TITLE
Feature Request: "Find and Replace" tool for upgraded plans

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#95479]
### What

Customer request: this user wants our editor tools to include a native find and replace text within posts/pages/templates. They are hoping this could be a paid feature we could include this feature with Premium and up.

### Why

It could be useful when they:
- change a phone number
- change their name
- change colors and need to replace all hard-coded instances in blocks

### How

Not sure. It would probably make more sense under Tools than in the post/page/template editor, but we'd definitely want to store any changes as revisions that can be undone, if it's not too heavy a process.

Also, there are plenty of plugins to handle this sort of thing; this user was hoping we could include it within WP.com's built-in features. I'm sharing the request from 8305797-zd-a8c, as I've personally seen many customers need something like this once in a while, but who are otherwise best suited to a Premium plan.

**Comment by supernovia** [comment]
Marking as triaged since this was Zendesk feedback: 8305797-zd-a8c

**Comment by inaikem** [comment]
Feels like this might be a nice feature request for Jetpack. @jeherve, do you have any strong opinions about this being a JP or a Core features?

**Comment by jeherve** [comment]
@inaikem I don't believe that's something we would include in Jetpack. As @supernovia mentioned, there are many plugins that do that well already, so there wouldn't be much need for the feature in the Jetpack plugin for self-hosted site owners.

If we were to add such a feature to WordPress.com, it would probably be better to add it to the mu-wpcom plugin instead. That said, I don't know that there is much need for it right now ; it's a feature that may not be used that often overall. I would personally close this issue as "won't fix" for now. We can always reopen it later if more folks request such a feature.

**Comment by inaikem** [comment]
Works for me. Thanks. @jeherve!
