### ISSUE TITLE
Redesign Design Picker and Theme Showcase

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#95492]
### Brief

Both the Design Picker and Theme Showcase projects to be redesigned to reflect orienting themes towards types of websites and categories of content. Related https://github.com/Automattic/wp-calypso/issues/95495

**Comment by dsas** [comment]
Also related: https://github.com/Automattic/wp-calypso/issues/95651

**Comment by Copons** [comment]
As mentioned, this and #95651 should be considered together. The [key point](https://github.com/Automattic/wp-calypso/issues/95651#issuecomment-2462678307) is:

> If we want to re-align Design Picker and Theme Showcase, then we must ask, "What about the wp-admin Themes section"?

**Comment by richtabor** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/95789 (duplicated).
