### ISSUE TITLE
Add goal-centric filtering for design picker

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#95495]
**Project Thread: pbxlJb-6Hz-p2**

[Goals are moving in front of the design picker](https://github.com/Automattic/wp-calypso/issues/95488). By doing so, we can pre-configure the showcase results based on the user's multi-selection goal selection. 

This proposal is to introduce another meta value to filter themes by website type (store, blog, portfolio, newsletter, course, etc... ) that is secondary to the current category list. This way users can select a website type alongside any other category/topic (_i.e. an online store for artists, or a blog for artists_). Type should be multi-select (as are goals), while category can only be applied one at a time. 

### Requirements 

- Discuss introducing a filter by website type (store, blog, portfolio, newsletter, course, etc... ) in addition to the existing category list. 
- Define the types we need. Some current categories will be reclassified as types. 
- Determine the hierarchy of type/goals—i.e. when you select both a a goal to sell online and creating a blog, are both types pre-selected, or does "store" take precedence (as a store can easily have a blog, but a blog is less likely to have a beautiful store). 
- Type is multi-select whereas Category is single-select.
- Themes are recategorized and assigned to a single type.

**Comment by richtabor** [comment]
In the interim, pre-selecting a category for the goals would be a good step.

**Comment by autumnfjeld** [comment]
> https://github.com/Automattic/wp-calypso/issues/95488. By doing so, we can pre-configure the showcase results based on the user's multi-selection goal selection.

Goals were always in front of the Design Picker (DP).  Currently the goals are used to configure the DP by filtering on either Business or Blog.

**Comment by taipeicoder** [comment]
Design spec is ready for dev - rQKOSaTKHBSXu3CxyHAWnV-fi-2133_7933.

**Comment by taipeicoder** [comment]
@richtabor @fditrapani confirming on the following requirement:

> Type is multi-select whereas Category is single-select.

Is this still the case? Meaning that according to the design spec below, "Features" is multi-select, while "Subjects" is single-select.

![Image](https://github.com/user-attachments/assets/7e4ab160-8215-4925-9293-fcb10f680133)

**Comment by fditrapani** [comment]
> Type is multi-select whereas Category is single-select... Is this still the case?

This is not the case since we have some goals that map over to the Subject list. We should have it multi-select in both groupings as a first pass anyways. As a next step in the new year, I'm hoping we can revisit the options in both groupings and revisit this decision.

**Comment by taipeicoder** [comment]
Closing this as pbxlJb-6DF-p2 has been completed.
