### ISSUE TITLE
Sites: Jetpack site preview from My Sites shows navigation masterbar

### ISSUE THREAD

**Issue by lancewillett** [Automattic/wp-calypso#9555]
#### Steps to reproduce
1. Starting with a Jetpack site connected to WordPress.com
2. Go to wordpress.com and click on My Sites
3. Select the Jetpack site
4. Click the site title to bring up the site preview

#### What I expected
I expected to see the site preview without the WordPress core adminbar visible at the top.

#### What happened instead
The WP.com "masterbar" navigation is now visible.

#### Screenshot
<img width="1192" alt="screen shot 2017-06-18 at 19 37 30" src="https://user-images.githubusercontent.com/66797/27267481-98ed7c94-545d-11e7-91d9-67d4f7708417.png">

#### Context / Source
#context is #dogfooding #livesharing -- I don't think we should show any toolbars in preview because site owners are liable to click there and get preview-ception rather than breaking out of Calypso preview and doing the actions in a new tab or window.

Note: WP.com sites do not show the masterbar in site preview.

**Comment by lancewillett** [comment]
A bit similar to #2013

**Comment by lancewillett** [comment]
@spen How's it going on addressing this one?

**Comment by spen** [comment]
Completely slipped by me! Sorry I'll make this a priority and tackle it tomorrow & the weekend! :)

**Comment by marekhrabe** [comment]
We are looking into moving all the preview handling code from dotcom codebase to Jetpack. That will also handle this issue.

**Comment by lancewillett** [comment]
Re-testing this one today, still seeing the masterbar navigation for Jetpack sites in View Site preview pane. (Safari 10.1.2 on OS X 10.12.6)

![screen shot 2017-09-04 at 14 15 48](https://user-images.githubusercontent.com/66797/30038618-971f97fc-917b-11e7-987e-3d9c27a5e02d.png)

![screen shot 2017-09-04 at 14 15 53](https://user-images.githubusercontent.com/66797/30038619-99198536-917b-11e7-8b4d-5e592b0ead2d.png)

**Comment by marekhrabe** [comment]
@lance are you on Jetpack beta? If not, a regular update (5.3) which includes our code should be shipping Sep 5th

**Comment by lancewillett** [comment]
Awesome, thanks @marekhrabe. Confirmed on my test site by turning back to latest Jetpack stable:

With Jetpack 5.1 I still see the masterbar in Calypso preview
![screen shot 2017-09-04 at 17 12 51](https://user-images.githubusercontent.com/66797/30040467-69d3d5c4-9194-11e7-9f73-3cf435c48f7d.png)

Now turning on Release Candidate (5.3)
![screen shot 2017-09-04 at 17 12 57](https://user-images.githubusercontent.com/66797/30040468-69d4db22-9194-11e7-8d81-74683506502f.png)

Checking the front-end of the site, it's visible there as expected
![screen shot 2017-09-04 at 17 13 09](https://user-images.githubusercontent.com/66797/30040469-69d70398-9194-11e7-8a1d-34b9081aa495.png)

Now checking Calypso View Site preview again — gone! Sweet.
![screen shot 2017-09-04 at 17 13 14](https://user-images.githubusercontent.com/66797/30040466-69d3d380-9194-11e7-8f2a-d71bd4ed778f.png)
