### ISSUE TITLE
White-labeled plugin: Internal documentation of the plugin and update process

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#95562]
@andres-blanco pointed out that we should have an internal document of the White-labeled plugin so we know:

- [x] Where and how to make changes.
- [x] What can we update vs. what BlogVault has to update.
- [x] Who to contact on the BlogVault side.

**Comment by sixhours** [comment]
Started a FG doc here: PCYsg-13dy-p2

**Comment by gabrielcaires** [comment]
@sixhours  I think we can expand the  `Where and how to make changes.` topic.

I want to know what happens after I open an issue on github.
Should we open a PR fixing and let them review? 
Show we merge and send the zip file?

**Comment by sixhours** [comment]
> I want to know what happens after I open an issue on github.
> Should we open a PR fixing and let them review?
> Show we merge and send the zip file?

Great points, I've expanded on that section!

**Comment by andres-blanco** [comment]
+1 what Gabriel said. I would like to have a clear picture of how a specific change gets to production, at least, have the responsibilities laid out, for example (probably this is factually incorrect): "After a PR is made in the BlogVault repository a new version of the plugin will be submitted to WPORG"

**Comment by sixhours** [comment]
@andres-blanco I updated that section with a more detailed process but it appears the changes didn't save. :-| I'll work on them again today.

**Comment by sixhours** [comment]
@andres-blanco I've updated that again, please let me know if it's clearer!

**Comment by andres-blanco** [comment]
Looking way better @sixhours, thanks!

Can you add instructions on how to do this?
![Image](https://github.com/user-attachments/assets/38332fef-b83a-4130-89ef-f692c1308eed)

**Comment by sixhours** [comment]
> Can you add instructions on how to do this?

Gotcha, let me know if the updated instructions are clearer!

**Comment by sixhours** [comment]
I'm going to mark this as done since we can always go back and update the docs.
