### ISSUE TITLE
White-labeled plugin: `/move` page still references Migrate Guru

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#95577]
@cuemarie brought this to our attention in Slack: p1729187364514169-slack-C0Q664T29 

We may need to coordinate with Marketing folks to get this page updated.

**Comment by sixhours** [comment]
Pinged in Slack: p1729603889718949-slack-CV1BNGVCH

**Comment by sixhours** [comment]
MarTech fixed it <3

**Comment by cuemarie** [comment]
That was fast!  Thanks so much ☺
