### ISSUE TITLE
Reader: pull more information out of MediaRSS feeds, like YouTube

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#956]
Raised by @blowery 

> Feeds for YouTube sites looks pretty terrible. See https://wordpress.com/read/blog/feed/38918632. They use some RSS extensions called MediaRSS, which we should probably understand and use to make the display better.

To reproduce:
1. View the blog feed stream for https://www.youtube.com/feeds/videos.xml?channel_id=UCORIeT1hk6tYBuntEXsguLg in the Reader at https://wordpress.com/read/blog/feed/38918632

<strong>Result:</strong> no videos!

Blog feed stream:

![screen shot 2015-11-29 at sun nov 29 9 13 13 am](https://cloud.githubusercontent.com/assets/1119271/11457543/a61bff56-9679-11e5-8dca-dbd2fd7cda07.png)
<sup>Seen at https://wordpress.com/read/blog/feed/38918632 using Firefox 42.0 on Mac OS X 10.10.5</sup>

Single-post view:

![screen shot 2015-11-29 at sun nov 29 9 13 25 am](https://cloud.githubusercontent.com/assets/1119271/11457544/aa04956a-9679-11e5-865f-8111ef8ff117.png)
<sup>Seen at https://wordpress.com/read/post/feed/38918632/861541983 using Firefox 42.0 on Mac OS X 10.10.5</sup>

Note: use https://www.youtube.com/channel/UCORIeT1hk6tYBuntEXsguLg at https://wordpress.com/following/edit to subscribe to that YouTube MediaRSS feed.

**Comment by designsimply** [comment]
Another example: https://www.youtube.com/channel/UC_A%E2%80%93fhX5gea0i4UtpD99Gg at https://wordpress.com/read/feeds/45331199

Reported at https://test.wordpress.com/2017/02/09/subscribing-to-youtube-video-channels-in-reader/

**Comment by blowery** [comment]
Fixed with r153777-wpcom

**Comment by designsimply** [comment]
Tested https://wordpress.com/read/feeds/38918632 ([screenshot](https://cloud.githubusercontent.com/assets/1119271/24882775/7fc79bb2-1dff-11e7-87c5-1702e02ba96e.png)) and https://wordpress.com/read/feeds/45331199 ([screenshot](https://cloud.githubusercontent.com/assets/1119271/24882775/7fc79bb2-1dff-11e7-87c5-1702e02ba96e.png)) and they both look amaaazing. 😍
