### ISSUE TITLE
Preview & Customize option for themes generates an error when trying to save/activate changes (Saving failed. TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by philnick206** [Automattic/wp-calypso#95611]
### Quick summary

When using the Preview & Customize option from a theme page, users are not able to save/activate the theme. Instead, they see the error "Saving failed. TypeError: Failed to fetch"

![Image](https://github.com/user-attachments/assets/43b4434b-cbee-4334-8225-75fd75847d48)

### Steps to reproduce

1. Log in to a site with a free or Personal plan
2. Navigate to a theme that requires and upgrade to use
3. Click on Preview & Customize
4. Go to the Editor under Appearance > Editor  and edit a page
5. Click on Activate/save in the upper right

### A clear and concise description of what you expected to happen.

I would expect to be directed to checkout/pay for the required plan upgrade

### What actually happened

Error is displayed: Saving failed. TypeError: Failed to fetch

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Purchase plan first and then activate theme

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 8891321-zd-a8c

**Comment by Robertght** [comment]
PS: I also moved this to wp-calypso.

**Comment by arthur791004** [comment]
Closing it via https://github.com/Automattic/wp-calypso/pull/95639
