### ISSUE TITLE
Account Settings: Modals in account deletion flow have incorrect spacing

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95610]
### Quick summary

The modals shown in the account deletion flow have incorrect spacing to the right and bottom of the action buttons.

![Image](https://github.com/user-attachments/assets/8061a3a9-4c23-4e2d-9682-21c60cd1febf)
![Image](https://github.com/user-attachments/assets/aeccde69-80d9-4bd7-b662-9ccc9797e202)

### Steps to reproduce

1. Go to Account Settings.
2. Close the account.
3. Note that both the "Are you sure?" and "Confirm account closure" modals have too much space around the actions.

### What you expected to happen

The padding to the right and bottom of the action buttons should be `24px`.

### What actually happened

Incorrect padding.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I checked this with Firefox and Chrome, and it looks okay from my end: 

![Image](https://github.com/user-attachments/assets/3c4fb5a2-d947-4ccf-8298-7db1efa9984b)

![Image](https://github.com/user-attachments/assets/34dc7c94-5337-40e8-9f3d-ff91994ea7f7)

📌 ACTIONS
- Triaged
- Closed as could not replicate (please reopen if the issue reoccurs)
- Lowered priority from High to Low.

📌 Message to Author
👋🏻 @matt-west Are you still getting this incorrect spacing? Thank you!

**Comment by matt-west** [comment]
@jartes Nope. Looks like it’s been fixed! 👍
