### ISSUE TITLE
Replace "Comments" Calypso view with standard WordPress "Comments" view

### ISSUE THREAD

**Issue by richtabor** [Automattic/wp-calypso#95622]
> [!IMPORTANT]
> **Project thread: pekYwv-4PY-p2**
> Tracked by #98483 

As part of the Untangling Calypso epic, let's remove the custom implementation of the `wordpress.com/comments` view, in lieu of the standard WordPress `wp-admin/comments.php` view—**for all users**. 

This will reduce confusion navigating between Calypso and proper WordPress admin. 

### Requirements 
- Selecting "Comments" from the WordPress or Calypso menu opens the standard WordPress pages view at ` wp-admin/comments.php`

**Comment by tanjoymor** [comment]
**Recommendation:** Switch to WP Admin for All users / All platforms

**Suggestion:** Add the ability to Block Users

<img src="https://github.com/user-attachments/assets/571cf461-4be4-4619-b1d7-13aa4e470947" width="25%">

No other considerations

**Comment by Copons** [comment]
I don't see any blockers for this. Let's use **wp-admin for new users**, as recommended!

### Considerations

- Block Users
  - On paper, it's an essential feature. In practice, it's used ~15 times a day (which is a good thing!!).
  - I don't consider this a blocker. However, in the context of this issue, we should do a **quick investigation on how we handle comments marked as spam**. Maybe we don't explicitly need to block users, but we can simply rely on our regular anti-spam capabilities.

**Comment by Aurorum** [comment]
Calypso also offers the ability to collapse replied comments - not sure how essential that is, but it’s something which I have found useful.

![Image](https://github.com/user-attachments/assets/675a88d8-f342-47af-ae83-ce3e6d8ebe57)

**Comment by Copons** [comment]
@Aurorum Well noted!

The Calypso comments section has loads of nice UX touches — I shouldn't say so: I was one of the people who originally developed it in... IIRC... the late 1950s. 😅
However, now that we are moving back to wp-admin, we are more concerned about any missing functionality, and even if sometimes painful, UX niceties are not blockers.

**Comment by rcrdortiz** [comment]
> I don't see any blockers for this. Let's use **wp-admin for new users**, as recommended!
> 
> ### Considerations
> * Block Users
>   
>   * On paper, it's an essential feature. In practice, it's used ~15 times a day (which is a good thing!!).
>   * I don't consider this a blocker. However, in the context of this issue, we should do a **quick investigation on how we handle comments marked as spam**. Maybe we don't explicitly need to block users, but we can simply rely on our regular anti-spam capabilities.

If we want to replicate blocking users from commenting we could do so in the `Discussion Options` settings page by adding a new section. I will not work on that as part of the main issue since the feature isn't used much and has declined in the past 3 years.
- https://04112024rortiz.wordpress.com/wp-admin/options-discussion.php

![Image](https://github.com/user-attachments/assets/b5080d03-bad4-46e7-a948-bec02709a095)

[Funnel](https://mc.a8c.com/tracks/trends/?eventname=calypso_comment_management_moderate_user&interval=month&startdate=20211206&stat=uniques)

**Comment by Copons** [comment]
@rcrdortiz is the Calypso version simply adding IPs and keywords to these options?

![Image](https://github.com/user-attachments/assets/019a5ebd-0828-4ee1-9241-1e018c8d5bae)

If that's the case, I'd say we are fundamentally covered. Maybe we could mention the change in an "educational" tooltip. 🤔

**Comment by mmtr** [comment]
> for new users

We discussed this today and decided that, considering we'll release changes with a holdout test, we want to target all users (new and existing), so I updated the issue summary to reflect that. See p1733745514693799-slack-C04DZ8M0GHW.

**Comment by rcrdortiz** [comment]
> [@rcrdortiz](https://github.com/rcrdortiz) is the Calypso version simply adding IPs and keywords to these options?
> 
> ![Image](https://github.com/user-attachments/assets/019a5ebd-0828-4ee1-9241-1e018c8d5bae)
> 
> If that's the case, I'd say we are fundamentally covered. Maybe we could mention the change in an "educational" tooltip. 🤔

Yes, the Calypso version is fundamentally a glorified text field where you can input IPs.

**Comment by rcrdortiz** [comment]
These changes are now live.

@Copons should we create an enhancement issue for providing IP filtering on wp-admin?
