### ISSUE TITLE
Getting "This page could not be found. Try searching posts using the search field." when trying to preview an unpublished post

### ISSUE THREAD

**Issue by zyousafi** [Automattic/wp-calypso#95679]
### Quick summary

While using the "Cultivate" theme on a simple site, am unable to preview unpublished posts from the editor.  Keep getting the following error on the previewed page:

```
This page could not be found. Try searching posts using the search field.
```

### Steps to reproduce

1. Create a new post
2. Give it a title.  Add some test text
3. Save the draft by clicking on "Save draft"
4. Click on the preview option highlighted here: https://cloudup.com/c04dzrrZCof

### What you expected to happen

The preview should display the post title and content in a new tab

### What actually happened

"Page not found" error was thrown:

https://cloudup.com/cU6V74K2_Bh

### Impact

One

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Here's the workaround:
* Before clicking on the preview option, click on the "Zoom Out" option first
* Then click on the preview option highlighted here: https://cloudup.com/c04dzrrZCof

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I was unable to recreate the issue on my test site with the Cultivate theme active, but I was able to reproduce it on multiple posts on the user's site.  There's something strange going on here

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate 
- Replicable outside of Dotcom – No


📌 ACTIONS
- Closed as could not replicate it (please reopen if the issue reoccurs)

📌 Message to Author
- @zyousafi If we can't replicate this right away, please open this on the HF P2 so we can bring in extra eyes on it.

**Comment by hacchism** [comment]
Just to update. The user to whom @zyousafi talked came back and confirmed that everything works just fine now, so the issue must be a temp glitch.
