### ISSUE TITLE
Comment textarea keeps expanding when I type

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#95692]
### Quick summary

Comment text area keeps expanding with typing, which is distracting. It does that even when the text is deleted.

### Steps to reproduce

1. Post a comment on a test site
2. Go to https://wordpress.com/comments/all/[SITE]
3. Reply to the comment

### What you expected to happen

Textarea to not move

### What actually happened

Textarea keeps expanding with each key pressed

https://github.com/user-attachments/assets/b1e699cd-5aca-4ac3-8e9c-5602b17f51fe

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

It's just a visual glitch, the comment works.

### Platform (Simple and/or Atomic)

Simple

**Comment by andres-blanco** [comment]
Hi @dzver I cannot reproduce the issue on Chrome. Can you still reproduce it now? What browser are you using?

Thanks

**Comment by dzver** [comment]
Can't reproduce right now. It was very persistent last week. Feel free to close it if it's no longer reproducible, we can reopen in case it starts again.

Chrome

**Comment by andres-blanco** [comment]
Ok, thanks for the follow up.

Closing this for not being reproducible.
