### ISSUE TITLE
Automated Migration: Cleanup errors message

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#95690]
### Details

At this point fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnhgbzngrq%2Qzvtengvba.cuc%3Se%3Qrqn9r1rn%23308-og we are calling the `automated_migration_tools_login_and_get_cookies`. When it returns an error, that function will include a lot of context so we can log it and later analyze it. That's great when it's called from an async job (fbhepr%2Skers%2Sjcpbz%2Snflap%2Qwbof%2Svapyhqrf%2Szvtengvba%2Snhgbzngrq%2Qzvtengvba.cuc%3Se%3Qs804oo3p%23165-og), but not that great when called via an API endpoint from Calypso. In the later case, we are sending to the client superflous information.

More context
p1729797313545229/1729796631.307769-slack-C0Q664T29

### Checklist

- [ ] Refactor this part of the code: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Sraqcbvagf%2Sfvgr%2Qnhgbzngrq%2Qzvtengvba.cuc%3Se%3Qrqn9r1rn%23308-og. That condition is long and hard to read.
- [ ] Create a new error that includes only the needed parts for Calypso, which in this case I think we only need the error code

**Comment by andregardi** [comment]
Closed by D165306-code
