### ISSUE TITLE
Reader: safeContentImages trips up on empty Discover attribution image

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#957]
Raised by @bluefuton 

When rendering a list containing posts from the Discover blog (e.g. /read/list/bluefuton/abcde), safeContentImages() can trip up on `img.discover-attribution-avatar` with a blank src, raising an error in the console.

<img width="1153" alt="screen shot 2015-10-26 at 11 51 59" src="https://cloud.githubusercontent.com/assets/17325/10739223/7588d226-7bd8-11e5-84a6-a845e91e16db.png">
<img width="700" alt="screen shot 2015-10-26 at 11 53 15" src="https://cloud.githubusercontent.com/assets/17325/10739224/759eba50-7bd8-11e5-9f92-bd8a4bafc174.png">

**Comment by blowery** [comment]
Marking this high because Discover has launched and bugs that kill the interpreter are unacceptable.

**Comment by bluefuton** [comment]
No longer able to reproduce this. Both post attribution and site attribution check if `attribution.avatar_url` exists before attempting to render an img element.
