### ISSUE TITLE
AT: make sure Jetpack looks installed in the plugin directory (non-business sites)

### ISSUE THREAD

**Issue by drw158** [Automattic/wp-calypso#9574]
Once .com non-business users are able to browse the plugin directory, we need to make sure that Jetpack looks installed in the directory page and  also the plugin detail page.

Obviously it will look installed once they are transferred to Pressable.

**Comment by vindl** [comment]
Should I do the same for Akismet, since it will be included with Jetpack Professional (after AT)?

**Comment by vindl** [comment]
> Once .com non-business users...

Also, I think we should show it as installed for for business users too?

**Comment by drw158** [comment]
You're right on both counts
