### ISSUE TITLE
Reader Onboarding: Improve empty posts display

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#95770]
### Steps to reproduce

1. Go to /read?flags=reader/onboarding
2. Click "Discover and subscribe to sites you'll love"
3. Select "DIY Projects" and "Finance" as categories
4. Click "Load more" a few times until "Mark Stephens" shows up
5. Select that blog.

### What you expected to happen

The list of posts shows up.

### What actually happened

Shows a Welcome to Reader message

### Impact

One

### Available workarounds?

There is no user impact

### Logs or notes

Posts list response:
```
{
    "code": 200,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application\/json"
        }
    ],
    "body": {
        "date_range": {
            "before": "",
            "after": ""
        },
        "number": 0,
        "posts": null
    }
}
```

![Image](https://github.com/user-attachments/assets/585cb30a-4f7c-465b-a24e-ef749f69c7de)

**Comment by davemart-in** [comment]
We should prevent sites with zero results from showing here.

**Comment by allilevine** [comment]
> We should prevent sites with zero results from showing here.

@davemart-in I investigated and we do prevent sites with zero posts from being recommended: D159312-code

I can't replicate this site showing up as a recommended site, but it returns posts from the API endpoint correctly, and the feed loads correctly. More details: p1730233920506369/1730142040.227029-slack-C03NLNTPZ2T

@obenland Are you able to replicate this and share the API request URL? That might give us a clue about why no posts were returned.

Otherwise we can improve the empty posts display (as the issue title says).

**Comment by davemart-in** [comment]
@allilevine I just searched for [technology in the reader](https://wordpress.com/read/search?q=technology). If you open up all of the links in that right sidebar, a couple of them had zero recent posts showing:

- https://wordpress.com/read/feeds/15363560
- https://wordpress.com/read/feeds/51785229
- https://wordpress.com/read/feeds/48204499

I'd dig in there. I think we're using the same API to fetch related sites for the reader onboarding stuff.

**Comment by davemart-in** [comment]
Weird, if you click into the actual site for those links, I'm seeing recent posts:

- https://blog.ericgoldman.org/
- https://assistivetechnologyblog.com/
- https://educationtechnologysolutions.com/

**Comment by davemart-in** [comment]
> It could be that we need to filter out feeds with errors

Is there a way to easily do that?

**Comment by allilevine** [comment]
> > It could be that we need to filter out feeds with errors
> 
> Is there a way to easily do that?

I thought I'd found a way, by checking for these meta errors on the feed, but then I was testing onboarding and an empty feed came up for me! It was TechCrunch. The request is: `/rest/v1.2/read/feed/111100674/posts?http_envelope=1&orderBy=date&meta=post%2Cdiscover_original_post&number=4&lang=en&content_width=675`

So far I've traced it back to an empty user here: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sfhofpevcgvbaf.cuc%3Se%3Q0o019753%26sv%3Qjcpbz_fhof_trg_srrq%23290-og

**Comment by allilevine** [comment]
I opened two follow up issues with my findings:
- https://github.com/Automattic/wp-calypso/issues/95968
- https://github.com/Automattic/wp-calypso/issues/95970

**Comment by davemart-in** [comment]
Let's close this out in favor of:

- https://github.com/Automattic/wp-calypso/issues/95968 and
- https://github.com/Automattic/wp-calypso/issues/95970
