### ISSUE TITLE
Reader Site View Bug: Missing excerpts for WordPress.tv

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9579]
On the live site, WordPress.tv posts have excerpts: https://wordpress.com/read/blogs/5089392

But on wpcalypso, they do not: https://wpcalypso.wordpress.com/read/blogs/5089392

Any idea why? They should still have excerpts.

**Comment by bluefuton** [comment]
In the refreshed card, we always use our own excerpt which is created from post content (aka `better_excerpt`). On WordPress.tv, there's no post content so the `better_excerpt` is empty.

One way to handle this might be - if the `better_excerpt` is empty, fall back and use the regular `excerpt`. We currently only use the regular excerpt for Discover.

**Comment by fraying** [comment]
@bluefuton I like that plan.
