### ISSUE TITLE
Reader: extra shadow in comment box on mobile

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#958]
Raised by @beaulebens 

The inset shadow at the top of the comment field feels redundant given the outline that's already there. It only seems to be present on mobile/small screens.

<img src="https://cloud.githubusercontent.com/assets/108942/10834519/954a9a34-7e5f-11e5-8803-ea7a1d2f69c0.jpg" alt="img_3733" width="400" />

**Comment by alisterscott** [comment]
I confirm this is still present when the text field has focus. Since it's been open for some time and low priority I am closing this.
