### ISSUE TITLE
Reader: Post Recs: Notes, tweaks, and questions

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9580]
Just gave the <a href="https://calypso.live/?branch=add/reader/inline-recommendations">current state of in-stream Post Recs</a> a look on wpcalypso and wanted to note some things. We're making great progress! Sorry if this list is overwhelming. I've made them checkboxes so we can keep track and invoked people where I think I know who would handle something. If I'm wrong about that, please say so.

- [ ] @blowery: Would you please set recs to appear every 5 cards while we're testing? It'll make this easier.

![screen shot 2016-11-22 at 10 51 19 am](https://cloud.githubusercontent.com/assets/24388/20537440/069406d8-b0a2-11e6-8147-604b37ae9ae6.png)

- [x] @jancavan: Images should have the same 1px grey line as other card images (for the same reasons).
- [x] @jancavan: The text placement around the gravatar should match the other cards (seems too high).
- [x] @jancavan: Needs the standard 20px of whitespace between image and headline.
- [ ] @aaronyan/@gibrown: Is it possible to omit recs that have no excerpts? The experience above is not great. (I'm not even sure why I'd get recommended a post that's just a <a href="https://calypso.live/read/blogs/34392579/posts/5449">photo of a baby</a>.)
- [ ] Also note the indentation before the excerpt in the first rec. In <a href="https://calypso.live/read/blogs/36755584/posts/1566">the post</a> there seems to be a paragraph with just a space in it. Can we ignore that in the excerpt?

![screen shot 2016-11-22 at 10 50 41 am](https://cloud.githubusercontent.com/assets/24388/20537632/c00125ba-b0a2-11e6-8bf2-9c5c4259ff2c.png)

- [x] When both recs are text only, they should be limited to 5 lines total (including title and excerpt). I believe this is what we're doing in the More links now. Or is it possible to omit text-only recs entirely?  
- [ ] Note the crazy text in the second rec above. All those numbers are in a blockquote/table in <a href="https://calypso.live/read/blogs/18192625/posts/4704">the post</a>. Possible to remove that kind of text from the excerpt? It doesn't work as an excerpt.

![screen shot 2016-11-22 at 11 11 13 am](https://cloud.githubusercontent.com/assets/24388/20538056/677825ea-b0a4-11e6-89b8-44fdbf65fb3e.png)

- [ ] Can we avoid having with-image and without-image recs presented side by side? This is important because we're essentially giving the user a choice, and the image rec will almost always win, so it's not a fair fight.
- [ ] Either way, if this happens, they should both end at the same line (ie, the text only rec should have 2 fewer lines.

And a general question:

- [ ] Do we have a tracks event for clicking a rec post? (We should.) Same goes for Following from a rec post, as well as dismissing (when that's present).

Hope this is helpful. If it would be better to post these as separate issues, I can do that.

**Comment by gibrown** [comment]
>Is it possible to omit recs that have no excerpts? 

Unfortunately the word counts are broken in the current index. But once I can get back to fixing it we can.

**Comment by fraying** [comment]
@gibrown Okay - one more for the list. ;-)

**Comment by jancavan** [comment]
> - Images should have the same 1px grey line as other card images (for the same reasons).
> - The text placement around the gravatar should match the other cards (seems too high).
> - Needs the standard 20px of whitespace between image and headline.
> - When both recs are text only, they should be limited to 5 lines total (including title and excerpt). I believe this is what we're doing in the More links now. Or is it possible to omit text-only recs entirely?

These are fixed in: https://github.com/Automattic/wp-calypso/pull/9490/commits/3a8a84879ea86fb0166b81277d8b9689c07708ac

**Comment by fraying** [comment]
Calling this done - remaining things in other issues or no longer relevant.
