### ISSUE TITLE
Checkout: Contact info validation errors are misaligned

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95816]
### Quick summary

![Image](https://github.com/user-attachments/assets/96fd446c-4c29-4568-a21e-25fc88cf2d38)

### Steps to reproduce

1. Go to checkout
2. Attempt to submit contact information section without completing any fields

### What you expected to happen

The validation errors should be aligned with the left-side of the input.

### What actually happened

The validation errors are offset.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by renancarvalho** [comment]
Did a quick investigation and there's a `padding-left:26px` wrongly being applied to this `form-input-validation`
Seems from [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/forms/form-input-validation/style.scss#L22)

Adding `Groundskeeping` label
