### ISSUE TITLE
Checkout: VAT checkboxes use the wrong blue

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95817]
### Quick summary

The VAT checkboxes should use `WP Blue 50` like all other elements on the page, they are currently using an older shade of blue.

![Image](https://github.com/user-attachments/assets/7ce9d023-a6cd-40bc-90e7-f1f7ff325b42)

### Steps to reproduce

1. Go to checkout as a user in the UK
2. Tick "Add VAT details" checkbox
3. Tick "Is VAT for Northern Ireland?" checkbox

### What you expected to happen

They should use `WP Blue 50`.

### What actually happened

They are using an older shade of blue.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
I was able to replicate this.

To put this in perspective with the other elements:

![Image](https://github.com/user-attachments/assets/419c3042-e099-4d57-bce9-0fe9b63a314e)

Marking as triaged and flagged it to groundskeeping for a quickfix.

**Comment by taipeicoder** [comment]
Closing as it's fixed.
