### ISSUE TITLE
Domains: Primary site address banner should use the banner component

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95828]
### Quick summary

This banner is using a custom component, but it should use our standard info banner.

![Image](https://github.com/user-attachments/assets/ba516185-aee5-40a4-b140-f10fabf2939f)

### Steps to reproduce

Go to https://wordpress.com/domains/manage/[SITE_URL]

### What you expected to happen

We should use the [Banner component](https://wpcalypso.wordpress.com/devdocs/design/banner) here instead.

### What actually happened

Using a custom banner.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by Aurorum** [comment]
> We should use the [Banner component](https://wpcalypso.wordpress.com/devdocs/design/banner) here instead

Hi! Would you mind elaborating on the reasoning here? My understanding is that this is not intended to provide information, but primarily to provide an option for users to switch their primary domain. I feel that a banner might be a bit intrusive and overwhelming for users who intentionally don’t want to purchase a domain, especially since it would need to be non-dismissible to meet that criteria.

**Comment by matt-west** [comment]
> My understanding is that this is not intended to provide information, but primarily to provide an option for users to switch their primary domain.

I see now that this section includes a dropdown if you have more than one domain:

![Image](https://github.com/user-attachments/assets/c50e1ace-4c66-4135-832a-b96c541f2973)

The main motivation of this issue is to reduce the number of custom components we’re defining throughout Calypso to bring more consistency to the UI. This stood out in our walkthrough because it’s not consistent with styles we use elsewhere.

I think the UX needs a bigger re-think here though. This banner should probably be a modal that’s triggered by a "Change primary site address" button somewhere in the UI.

Do you have any context on why this banner was banner was originally added?

**Comment by Robertght** [comment]
I was able to replicate this on my end.

cc @Automattic/nomado

**Comment by matt-west** [comment]
Thanks for the additional context @ramynasr. Makes sense to keep the banner then rather than going with the button + modal approach. 👍

**Comment by Robertght** [comment]
@matt-west is the context shared above enough for now? If yes, is it ok to close the report?

**Comment by matt-west** [comment]
Yep, we can close this.
