### ISSUE TITLE
Domains: Update WordPress.com logo on Titan login screen

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95831]
### Quick summary

The WordPress.com logo shown on the Titan email login page is outdated and needs updating.

![Image](https://github.com/user-attachments/assets/6485d628-b18b-4c92-8ef0-d0d1edc784d5)

### Steps to reproduce

Go to: https://wp.titan.email/login/

### What you expected to happen

The [latest logo](https://www.figma.com/design/OO6HpZCGgCb4Ebnxg3nWln/Dotcom-Brand%2FMarketing-Design-Library?node-id=3484-2246&t=xolWNu6T09nUedr8-4) should be displayed.

### What actually happened

We're displaying the old WordPress.com logo.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by wojtekn** [comment]
I'm checking with the Titan team to see how we can update the logo.

**Comment by wojtekn** [comment]
I passed the new logo to Titan team and they will let us know when it's changed.

**Comment by wojtekn** [comment]
The logo is changed now:

<img width="474" alt="Image" src="https://github.com/user-attachments/assets/d790e22a-fdab-49b8-bce2-5460f471af23" />
