### ISSUE TITLE
Suggestion: Give A4A a more prominent banner here

### ISSUE THREAD

**Issue by inaikem** [Automattic/wp-calypso#95855]
### What

We should give A4A a more prominent banner here.

https://wordpress.com/me/developer

### Why

Developers may be interested in A4A.

### How

Adding a banner/feature box/improving copy.

**Comment by wongasy** [comment]
@inaikem We've observed that users who self-identified as developers aren't necessarily developers. We should revisit the purpose of the Developer Feature Page as well as the "I am a developer" toggle before making further changes. See more details here p4ya8V-b0m-p2#comment-5086

**Comment by Robertght** [comment]
As we're revisiting this option at the moment, I'm going to close this one for now.

@wongasy or @inaikem, feel free to reopen it if it becomes relevant again.
