### ISSUE TITLE
Email: Go to inbox button should open in a new tab

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95863]
### Quick summary

The `Go to inbox` link shown on the success page after purchasing an email plan should open in a new tab. The buttons should also include the external link icon.

![Image](https://github.com/user-attachments/assets/b4855ada-d932-4ddd-8375-771d2a92a762)

### Steps to reproduce

Purchase a new email plan.

### What you expected to happen

The button should open Titan email in a new tab as it is an external service.

### What actually happened

The button opens Titan email in the same tab.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
I agree this would improve the user experience as I've felt the need for it many times.


@Automattic/nexus or @Automattic/yolo I marked it as a High priority as I believe it could be a quickfix.
