### ISSUE TITLE
Reader: Content links do not always open in a new tab

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-calypso#9588]
https://wpcalypso.wordpress.com/read/feeds/7396759/posts/1233278060

Click on "Read 3 remaining paragraphs" at the bottom.

At least based on a comment by @fraying this should open in a new tab and doesn't for me on Chrome.

**Comment by fraying** [comment]
Oh. I was talking about links we own in Reader (interface stuff). Dunno if we want to add targets to links in content. Do we? Did we before?

**Comment by gibrown** [comment]
For me, I want the link to open in the Reader (if it can), or to open in a new tab.

**Comment by astralbodies** [comment]
Here's an example: https://wordpress.com/read/feeds/57434441/posts/1254610564

Clicking `The Old Fashioned` title of the reblog takes you to the post it's linked to instead of popping out to a new window. Reader is now gone, place lost for the user.

**Comment by fraying** [comment]
This is operating as designed.
