### ISSUE TITLE
Gutenberg: v19.6.x plugin upgrade

### ISSUE THREAD

**Issue by holdercp** [Automattic/wp-calypso#95885]
Previous upgrade:  #95318 
Release notes: [v19.6.2](https://github.com/WordPress/gutenberg/releases/tag/v19.6.2)

**Install and activate**

- [ ] Install and activate v19.6.0-rc.1 on edge (######-code)
- [ ] Install and activate v19.6.0-rc.2 on edge (######-code)
- [x] Install and activate v19.6.0-rc.3 on edge (D165396-code)
- [ ] Install and activate v19.6.0 on edge (######-code)
- [ ] Activate v19.6.0 on production (######-code)
- [ ] Request v19.6.0 AT upgrade (######-p2)
- [x] Install and activate v19.6.1 on edge (D165888-code)
- [ ] Activate v19.6.1 on production (D165890-code)
- [ ] Request v19.6.1 AT upgrade (######-p2)
- [x] Install and activate v19.6.2 on edge (D166369-code)
- [x] Activate v19.6.2 on production (D166370-code)
- [x] Request v19.6.2 AT upgrade (######-p2)
- [ ] Install and activate v19.6.3 on edge (######-code)
- [ ] Activate v19.6.3 on production (######-code)
- [ ] Request v19.6.3 AT upgrade (######-p2)
- [ ] Install and activate v19.6.4 on edge (######-code)
- [ ] Activate v19.6.4 on production (######-code)
- [ ] Request v19.6.4 AT upgrade (######-p2)

**Testing**

- [ ] v19.6.0 Desktop viewport E2E
- [ ] v19.6.0 Mobile viewport E2E
- [ ] v19.6.0 WPCOM core (D165397-code)
- [x] v19.6.1 Desktop viewport E2E
- [x] v19.6.1 Mobile viewport E2E
- [ ] v19.6.1 WPCOM core (######-code)
- [x] v19.6.2 Desktop viewport E2E
- [x] v19.6.2 Mobile viewport E2E
- [x] v19.6.2 WPCOM core (D166370-code)
- [ ] v19.6.3 Desktop viewport E2E
- [ ] v19.6.3 Mobile viewport E2E
- [ ] v19.6.3 WPCOM core (######-code)
- [ ] v19.6.4 Desktop viewport E2E
- [ ] v19.6.4 Mobile viewport E2E
- [ ] v19.6.4 WPCOM core (######-code)

**Publish internal announcements**

- [x] Slack: #wpcom-happy-announce - p1731684434115899-slack-CB0B2G43X
- [x] P2: wpcomhappy - p7DVsv-lHA-p2

**Wrap-up**

- [x] Clean up unused releases
- [x] Add log entry to the Gutenberg Upgrade Log - pcoGjb-3O-p2
- [x] [Open a new issue](https://github.com/Automattic/wp-calypso/issues/new?assignees=&labels=gutenberg-upgrade%2C+%5BType%5D+Task&template=gutenberg-plugin-upgrade.md&title=Gutenberg%3A+%5Bv%23.%23.%23%5D+plugin+upgrade) for the next upgrade, transfer remaining tasks, close this issue. -> https://github.com/Automattic/wp-calypso/issues/96365

### Blockers 🤷‍♀️

None

### Other Issues 🐛

**Issues transferred from previous release(s)**

- A bug was reported in p1729012544736219-slack-CBTN58FTJ that appeared after the v19.4.0 release. It seemed minor but it's worth following up with if there's time.
- #95944 was reported shortly after v19.5.0 was released. v19.5.0 was reverted because of a bug and v19.5.1 is staged for deployment. v19.5.1 might fix the issue reported here but I was unable to reproduce on v19.5.0 so it might have been a fluke when an old page is edited after a GB update. It's worth following up on if there's time.

---

cc @Automattic/gutenberg-upgrades @Automattic/cylon

**Comment by xavier-lc** [comment]
There's a buggy behavior with write/design mode making some template blocks unable to interact with, I'm trying to investigate: 

https://github.com/WordPress/gutenberg/issues/66463
https://github.com/WordPress/gutenberg/issues/66802
https://github.com/WordPress/gutenberg/issues/66803

**Comment by xavier-lc** [comment]
I've identified https://github.com/WordPress/gutenberg/pull/65945 as the first PR where the List View content doesn't change when switching between the Write and Design modes.

**Comment by xavier-lc** [comment]
A fix for https://github.com/WordPress/gutenberg/issues/66463 is read yon gutenberg: https://github.com/WordPress/gutenberg/pull/66833

**Comment by synora** [comment]
v19.6.0 and v19.6.1 seem to be causing [a similar issue](https://github.com/Automattic/wp-calypso/issues/95318) where items within a  Group Block cannot be edited. 

https://github.com/user-attachments/assets/9a7c7a60-9cb4-4261-a2a3-f0bd0948cd6e


Disabling Gutenberg allows the user to access the Form Block nested within a Group Block. 

Reported in 9015639-zen. 
The live site is on v19.6.0 and staging is on v19.6.1.

The Slack report at p1731159809368739-slack-C03TY6J1A

**Comment by xavier-lc** [comment]
@synora do you have reproduction steps for the issue so I can try to debug it?

**Comment by mgozdis** [comment]
@xavier-lc I was helping @synora with that ticket. I could reproduce the issue on their live site like this:

1. Pages > Add New Page
2. Click Add New Page button and select Contact under "Featured"
3. Select "Center heading with contact form"
4. Attempt to click any of the field names and see they aren't editable. 

Worth noting is the issue does not exist if we use an unmanaged version of the plugin and is specific to the versions on Dotcom possibly since 19.5.0. Using an unmanaged version of 19.6.1 and the page with the issue can be edited fine and is no longer reproducible.

**Comment by xavier-lc** [comment]
> I could reproduce the issue on their live site like this:

Thanks @mgozdis. My question was more if it was possible to reproduce the issue on any site from a scratch, in order to debug it.

> Using an unmanaged version of 19.6.1 and the page with the issue can be edited fine and is no longer reproducible.

It's goo to know that, thanks!

**Comment by xavier-lc** [comment]
The Gutenberg simple E2E tests edge (mobile) passed successfully! [View build](https://teamcity.a8c.com/viewLog.html?buildId=13683440)
The Gutenberg simple E2E tests edge (desktop) passed successfully! [View build](https://teamcity.a8c.com/viewLog.html?buildId=13683439)

**Comment by synora** [comment]
Thanks for replying while I was AFK, @mgozdis.  
@xavier-lc, at the time of testing, I couldn't reproduce it on my test site. However, that was before we discovered the blocks work using an unmanaged version of 19.6.1. I was using 19.5.0.

While I can no longer reproduce the issue, you'd want to create a new page and insert a 2 Column Block with text on one side and a contact form on the other. Then, group the parent Column Block and the column that contains the contact form. Save your changes, refresh your screen, and try to edit the form. You may need to ungroup them all in order to edit.

I'll try posting the video again:https://github.com/user-attachments/assets/8f0b041c-e080-448e-aa22-844bcd6f86b9

One thing I noticed happening to that user's site is that initially, their page is a 2 Column Block layout. When you ungroup the parent Column Block, all column blocks disappear.

**Comment by xavier-lc** [comment]
> While I can no longer reproduce the issue, you'd want to create a new page and insert a 2 Column Block with text on one side and a contact form on the other. Then, group the parent Column Block and the column that contains the contact form. Save your changes, refresh your screen, and try to edit the form. You may need to ungroup them all in order to edit.

I couldn't reproduce it either, the form is editable after reload.

**Comment by xavier-lc** [comment]
I was about to deploy v19.6.1 on production simple sites, but @david-binda noticed that there's a regression that allows comments to be posted on closed posts. (See slack p1731515367049229/1731510987.907329-slack-C4GAP2RHD)

**Comment by xavier-lc** [comment]
Asked the folks on team IO for help and @ellatrix has set up a fix PR: https://github.com/WordPress/gutenberg/pull/66976

**Comment by xavier-lc** [comment]
✅ [Simple desktop e2e tests](https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_simple_edge_desktop/13714724?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildDeploymentsSection=false)
✅ [Simple mobile e2e tests](https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_simple_edge_mobile/13714737?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildDeploymentsSection=false)

**Comment by xavier-lc** [comment]
Gutenberg: Remove unused v19.1.0 - D166405-code
