### ISSUE TITLE
Feature Request: Speed Test Tool - Remove scrollbar in screenshot

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#95890]
### What

In the Speed Test Tool tool, there seems to be a scrollbar in the screenshot in the top right section of the report

|Report | Zoomed in Screenshot|
|-------|------|
|![Image](https://github.com/user-attachments/assets/a6bfbd20-a1b1-44c5-924c-2a2be89c7aa3) |![Image](https://github.com/user-attachments/assets/fc7a5f63-5f7a-4f36-8b41-a49766841bd6) |

### Why

It does not look correct

**Comment by epeicher** [comment]
Planning discussion: We think we could work around 10 minutes trying to tweak the screenshot with CSS if possible. If not, we can close this task as the Screenshot comes from pagespeed insights API so we cannot control it.

**Comment by epeicher** [comment]
I have spent a few minutes and I have [proposed a solution here](https://github.com/Automattic/wp-calypso/issues/95890), but I would not progress it due to the following reasons:
- It updates all screenshots regardless of if they have a scrollbar or not. It is only 4px, but it is cropped anyway.
- It does not differentiate between desktop and mobile. We can add more logic for that, but I don't think the extra-code is worth it.
- The gallery below is not cropped, so we can still see the scrollbar there. We can also add more logic, but I don't think is worth it.

**Comment by cpapazoglou** [comment]
> I have spent a few minutes and I have [proposed a solution here](https://github.com/Automattic/wp-calypso/pull/96738), but I would not progress it due to the following reasons:
> 
> * It updates all screenshots regardless of if they have a scrollbar or not. It is only 4px, but it is cropped anyway.
> * It does not differentiate between desktop and mobile. We can add more logic for that, but I don't think the extra-code is worth it.
> * The gallery below is not cropped, so we can still see the scrollbar there. We can also add more logic, but I don't think is worth it.

I just tested your solution and I agree that it doesn't worth accounting for all cases. I am closing this.
