### ISSUE TITLE
Speed Test Tool - The text in the Enable email confirmation screen is incorrect

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#95897]
### Quick summary

When selecting `Enable email alerts`, the text displayed in the confirmation window is incorrect. It reads `The first email is on it‘s way now.` while the first email will arrive the next week.

|Click button | Confirmation screen|
|-------|------|
|![Image](https://github.com/user-attachments/assets/d8e8edfe-03e3-4585-ac6c-5390512b7fb2)|![Image](https://github.com/user-attachments/assets/72c64be1-3010-4ff8-a058-0dd8dc39b92b)|

### Steps to reproduce

1. Navigate to https://wordpress.com/speed-test tool and run a test or open an existing report like https://wordpress.com/speed-test-tool?url=https%3A%2F%2Fwordpress.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Nzc3Mn0.048zsfIxmJ0M_YpPGRg0QSsTmtMglyBAlPMJhrGB1vg&tab=mobile
2. Click on `Enable email alerts` button
3. Check the text

### What you expected to happen

The text should read something like `The first email will arrive in around a week` or something around those lines

### What actually happened

The text displays `The first email is on it‘s way now.`

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
@epeicher If this will be worked on by your team, please feel free to mark this as Triaged.

I'll mark this one for now, but let us know if you need PA's input on it.

**Comment by epeicher** [comment]
> [@epeicher](https://github.com/epeicher) If this will be worked on by your team, please feel free to mark this as Triaged.
> 
> I'll mark this one for now, but let us know if you need PA's input on it.

Thanks @Robertght, for the Bugs we don't need PA's input, so I will mark them as Triaged, thanks!
