### ISSUE TITLE
Speed Test Tool - Links above and below title don't have a correct hover effect

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#95896]
### Quick summary

The button above the title and the link below the title do not have a correct hover effect

![Image](https://github.com/user-attachments/assets/b9e33a80-51e9-42aa-b9da-02a594a38753)

### Steps to reproduce

1. Navigate to https://wordpress.com/speed-test tool and run a test or open an existing report like https://wordpress.com/speed-test-tool?url=https%3A%2F%2Fwordpress.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Nzc3Mn0.048zsfIxmJ0M_YpPGRg0QSsTmtMglyBAlPMJhrGB1vg&tab=mobile
2. Hover over the button above the title named `WordPress Speed Test` and the link below the title with the text `Test another site`
3. Check they hide with the background when hovering over them

### What you expected to happen

They should be visible

### What actually happened

They hide with the background

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by agrullon95** [comment]
@epeicher - What do you think about adding the same hover color effect from `Test another site` to `WordPress Speed Test`?
Both will have a slight grey color. Here is video:

https://github.com/user-attachments/assets/06eaa512-5aa9-4172-bd9b-8fc1ff012760

**Comment by epeicher** [comment]
> What do you think about adding the same hover color effect from `Test another site` to `WordPress Speed Test`?
> Both will have a slight grey color

That sounds great to me @agrullon95, I will also loop in @fditrapani about it

**Comment by fditrapani** [comment]
Thanks for the video @agrullon95!  I think that works. It's a bit subtle and that's fine. We could remove the underline for Test another site for something a little more obvious.

**Comment by agrullon95** [comment]
> We could remove the underline for Test another site for something a little more obvious.

@fditrapani - Do you mean removing the underline on hover only?

**Comment by fditrapani** [comment]
That's right @agrullon95.

**Comment by Robertght** [comment]
Marking this as triaged as it's in progress.
