### ISSUE TITLE
Reader: group bursts of multiple posts from the same site

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#959]
Raised by @shaunandrews 

I follow a few... um... annoying... sites that I follow. I like browsing the overpriced gadgets at Fancy, and I like keeping up with my local news. I can follow Fancy and a few local news stations via RSS, which is pretty cool. But these feeds update throughout the day, and make it easy to "lose" posts from other sites, which I care about just as much or more than Fancy.

If we could group these "bursts of posts" from a feed together, it would help me keep up-to-date with my less-active followed sites while still seeing a bit from the hyper-active sites.

![artboard 2](https://cloud.githubusercontent.com/assets/191598/10048849/d61b9002-61e2-11e5-9a51-aec80c2b2acb.png)

**Comment by alisterscott** [comment]
This has been recently implemented in The Reader 😊
