### ISSUE TITLE
GitHub Deployments UI Cleanup

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#95903]
### Quick summary

During a feature walkthrough, we noticed a few UI issues that should be addressed:
* Ensure all buttons have proper style applied (they should not have different border radius from that of the "WP Admin" button). Here are some examples of the buttons that require cleanup, there may be more.

|Connect|Connect repository|Disconnect repository|
|--------|-------------------|-----------------------|
|![Image](https://github.com/user-attachments/assets/708f28da-d92a-4e7b-99bf-e85f47c5af5c)|![Image](https://github.com/user-attachments/assets/e0fbe686-c510-4346-a012-8fb0708bdbff)|![Image](https://github.com/user-attachments/assets/e090a133-411d-4497-b5af-42c252b9070b)|

* We should use the same search UI for consistency. Currently the search box for sites and repositories look different.
<img src="https://github.com/user-attachments/assets/c12cfcd1-da28-4849-8f68-9d78d6de4dfa" width=500 />

* Disconnect repository confirmation modal style is off:
    * Inconsistent margins
    * Is the "Disconnect repository" button red-worthy?

<img src="https://github.com/user-attachments/assets/3c8dfa1d-f273-46bd-b5f0-0f0e8a1aec0c" width=500 />

### Steps to reproduce

1. Have a site on Business or higher plan.
2. [Activate hosting features](https://wordpress.com/support/activate-your-business-plan/#activate-hosting-access) if they're not yet activated.
3. Go to "Deployments" tab.
4. **Observe** "Connect" button not rendered in correct style.
5. Select and connect a repository.
6. After the repository is connected, observe "Connect repository" button not rendered in correct style.
7. **Observe** the search box is inconsistent with the sites search box.
8. Click "..." to bring up the context menu, select "Disconnect repository".
9. **Observe** the confirmation modal style is off.

### What you expected to happen

GitHub deployments UI rendered in style consistent with the rest of the site.

### What actually happened

GitHub deployments UI rendered in style inconsistent with the rest of the site.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by wongasy** [comment]
@Automattic/quake FYI

**Comment by wongasy** [comment]
>Disconnect repository confirmation modal style is off

Let's ensure we use the `<Dialog>` component and remove any custom css overrides.

**Comment by p-jackson** [comment]
> Let's ensure we use the `<Dialog>` component and remove any custom css overrides.

@zaguiini we should also consider whether the easiest way to fix the layout is to switch to Core's modal component as @matt-west suggests here https://github.com/Automattic/wp-calypso/pull/96267#pullrequestreview-2429705497

I know this code is already using `<Dialog>` so it's a slightly different case from #96267. But given the fix in #96124 already involves quite a few code changes, maybe it's better to make the necessary changes to switch to Core's component.

**Comment by zaguiini** [comment]
Yeah @p-jackson I think I'll create a bunch of smaller PRs. That linked PR will cover the button changes.
