### ISSUE TITLE
Domain Selection: "Skip purchase" button not rendered properly

### ISSUE THREAD

**Issue by wongasy** [Automattic/wp-calypso#95902]
### Quick summary

When users launch a site without a custom domain, they'll be taken to the domain selection screen to purchase a custom domain. The "Skip purchase" button at the bottom of the list is not rendered properly.

![Image](https://github.com/user-attachments/assets/e5edec2f-7c69-4ff3-a498-90001bba2eda)

### Steps to reproduce

1. Have an unlaunched site without a custom domain.
2. Click "..." button for that site in the Global Sites View.
3. Select "Launch site"
4. On the domain selection screen, scroll to the bottom to get to the "Skip purchase" button.
5. Observe the "Skip purchase" button is not rendered properly.

### What you expected to happen

"Skip purchase" button should be rendered properly.

### What actually happened

"Skip purchase" button is not rendered properly.

### Impact

All

### Available workarounds?

There is no user impact

**Comment by wongasy** [comment]
@Automattic/nomado FYI

**Comment by Imran92** [comment]
Are you still able to reproduce it? It renders as expected for me ![Image](https://github.com/user-attachments/assets/ae824068-41bc-4c14-a39c-c55fb338b19f)

**Comment by wongasy** [comment]
@Imran92 The label and chevron are no longer rendered in two lines, but they're still not aligned with the rest of the line items

![Image](https://github.com/user-attachments/assets/aa5b514d-4539-448b-a8aa-dfefe30d3a0b)

**Comment by Imran92** [comment]
Thanks @wongasy for the quick reply!

Looks like It was fixed here https://github.com/Automattic/wp-calypso/issues/96222

But a new issue was opened here https://github.com/Automattic/wp-calypso/issues/96222

I'm picking up the later issue, because it looks like it'll help us close your new findings as well

**Comment by Imran92** [comment]
Should we close it in favor of https://github.com/Automattic/wp-calypso/issues/96222 ?

**Comment by wongasy** [comment]
>Should we close it in favor of https://github.com/Automattic/wp-calypso/issues/96222 ?

Sounds good!
