### ISSUE TITLE
Editor: Block Inserter doesn't show up on a new line

### ISSUE THREAD

**Issue by hacchism** [Automattic/wp-calypso#95935]
### Quick summary

As #2 in [this support guide](https://wordpress.com/support/wordpress-editor/add-content-blocks/#how-to-add-a-block) explains, we should see a block inserter when on a new line, but it currently doesn't show up.

![Image](https://github.com/user-attachments/assets/c8677218-7b64-4795-87a7-9f15554b44b5)

### Steps to reproduce

1. Open an editor.
2. On a new line, check if you can see the + Block Inserter at the side of an empty block.

### What you expected to happen

See the + Block Inserter at the side of an empty block.

![Image](https://github.com/user-attachments/assets/c8677218-7b64-4795-87a7-9f15554b44b5)

### What actually happened

The + Block Inserter doesn't show up.

![Image](https://github.com/user-attachments/assets/69466465-b60a-4a5d-9c75-476cae0df382)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

There are several other ways to add a new block as explained in https://wordpress.com/support/wordpress-editor/add-content-blocks/#how-to-add-a-block.

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by dsas** [comment]
Opened https://github.com/WordPress/gutenberg/issues/66632 upstream

**Comment by lsl** [comment]
[The fix is being backported](https://github.com/WordPress/gutenberg/pull/66636#issuecomment-2451771696). Is there anything else to be done here or are we just waiting for the GB release?

**Comment by arthur791004** [comment]
It's on the edge site and I assume GB rotations will release it to all wpcom sites soon.

**Comment by obenland** [comment]
Fixed on November 4. p1730732704574439-slack-CBTN58FTJ
