### ISSUE TITLE
Domains: Spacing on Domains page is inconsistent with Sites

### ISSUE THREAD

**Issue by matt-west** [Automattic/wp-calypso#95945]
### Quick summary

The left/right spacing on the Domains page in the global site view is inconsistent with the Sites page. This leads to layout shift as users switch between the pages. Perhaps it’s a max-width issue?

We should use the same spacing as the Sites page.

https://github.com/user-attachments/assets/94b65bf0-578c-4598-9c4e-d4a23444df45

### Steps to reproduce

1. Log in to WordPress.com
2. Navigate to Sites page
3. Navigate to Domains page
4. Note that the layout shifts

### What you expected to happen

The Domains page should have the same max-width as the Sites page.

### What actually happened

The pages have different spacing which causes layout shift.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by fditrapani** [comment]
Thanks for starting this issue Matt. The quick and easy fix could be some CSS overrides. The problem with that is every time the DataView component changes, those changes break too. Ideally, we're updating this entire view to use the DataView component. This should also give us a consistent search field to match the other screens.

**Comment by matt-west** [comment]
> Ideally, we're updating this entire view to use the DataView component

I agree! Hopefully we can tackle that as part of the wider updates to domain management.

In the meantime, let’s find an interim fix so this experience isn’t so disjointed for users.

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on the platform - Replicated

📌 ACTIONS
- Triaged
