### ISSUE TITLE
Domain Purchase: Notice about providing valid contact info disappears if account already has a domain

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-calypso#95954]
### Quick summary

This message can only flash briefly when an existing domain owner registers a new domain:
> Registering a domain name requires valid contact information. Privacy Protection is included for all eligible domains to protect your personal information.

### Steps to reproduce

1. Have an existing domain
2. Add a new domain & check out with domain only
3. Look for WHOIS verification messaging
4. notice it disappears quickly

### What you expected to happen

We've had feedback from folks who didn't realize they may have to provide proof of correct contact information. It may be smart to make that a checkbox that has to be checked, but at least it should display with each new domain registration.

### What actually happened

The warning about WHOIS verification blinks away if the account owner already has a domain

## Initial flash
![Image](https://github.com/user-attachments/assets/14976fad-ef42-4677-ae1f-75101a5a60e0)

## Shows contact info instead
![Image](https://github.com/user-attachments/assets/21715598-6a87-4471-993c-a84255733cb8)

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

If a user provides inaccurate contact info, some registrars suspend the domain while the user gathers proof of their contact information or updates it; either way it's a time-consuming process and the domain can be suspended in the meantime.

### Logs or notes

- This flash away only happens on my account that already has another domain
- FWIW, we've also had new domain owners not understand that they must provide accurate information and get upset when their domain is suspended over inaccurate info. It may be worth telling them upfront / asking them to acknowledge that they may need to provide proof of contact information.

**Comment by StevenPartridge** [comment]
https://github.com/Automattic/wp-calypso/pull/95972
