### ISSUE TITLE
Gutenberg v19.6.0-rc.2 Removes `getCanvasMode()`

### ISSUE THREAD

**Issue by holdercp** [Automattic/wp-calypso#95960]
### Quick summary

**This is a defect discovered during testing the upcoming Gutenberg 19.6.0 release. It is not live.**

The Gutenberg[ v19.6.0-rc.2 release](https://github.com/WordPress/gutenberg/releases/tag/v19.6.0-rc.2) removes the `getCanvasMode()` API in Wordpress/gutenberg#66213 from the `edit-site` store. Several Calypso apps are using this API and are now unable to load with this GB version installed.

The following Calypso apps should be updated to determine the canvas state from the URL params as suggested in the GB PR:

- `help-center`
- `wpcom-block-editor`

Using the URL for this state is compatible with older GB releases so this can be deployed before v19.6.0 lands.

Related to Automattic/jetpack#39997

### Steps to reproduce

1. Install GB v19.6.0-rc.2 on a site
2. Install a Full Site Edit theme
3. Navigate to Appearance -> Editor
4. Check console logs and notice errors relating to the `help-center`, `wpcom-block-editor`, and the Jetpack `wpcom-block-editor-nux` plugins
5. Notice the help center icon is missing
6. Click into the canvas to edit
7. Notice the errors in the UI

### What you expected to happen

The mentioned plugins load as normal.

### What actually happened

- Missing help icon
- Visible UI errors
- Console errors

![Image](https://github.com/user-attachments/assets/e0c2dc77-b47b-4694-bff9-4e9fd1892f0e)

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by obenland** [comment]
@holdercp Can this be closed now?
