### ISSUE TITLE
FullPost content not showing when clicked from /read/search stream

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#9596]
When viewing the recommendations in /read/search, there are three issues with excerpt-only posts:
1. The post image does not appear in the stream
2. The post content of the post does not appear in fullpost view
3. The post content appears in fullpost view after refreshing the page

No image in stream:
<img width="854" alt="reader_refresh_search_empty" src="https://cloud.githubusercontent.com/assets/4505888/20548112/8b4f63bc-b0d5-11e6-9557-88e8520580ac.png">

No post content in fullpost view:
<img width="980" alt="scalzi_from_stream" src="https://cloud.githubusercontent.com/assets/4505888/20548120/92e645a0-b0d5-11e6-98c8-4c3971b271eb.png">

**Comment by fraying** [comment]
To be clear, @aaronyan is talking about the first rec from Scalzi.

@blowery We had this problem with Scalzi (and other VIPs) a while back, do you remember?
