### ISSUE TITLE
Wix Importer unable to import https://www.alineerbeia.com/

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/wp-calypso#95982]
### Quick summary

User purchased a Business plan to move their Wix site to WordPress.com.

Their website is https://www.alineerbeia.com/.  (confirmed it's a Wix site using our site-profiler)

When trying to import using Wix importer it fails and says- "It looks like we are unable to access the website address at the moment. (ID: 86e7db86-e4b8-4ce8-beb9-f5e329f12a54)"

### Steps to reproduce

1. Go to Tools> Import> Wix
2. Paste the Wix site URL- https://www.alineerbeia.com/
3. Click on Import

### What you expected to happen

I expect the Wix site's static pages to get imported.

### What actually happened

We see this error that says- "It looks like we are unable to access the website address at the moment. (ID: 86e7db86-e4b8-4ce8-beb9-f5e329f12a54)"

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

I tried workarounds-
* Importing multiple times.
* Importing using non www URL and with www URL as well.

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 ACTIONS
- Closed as duplicate
- 
📌 Message to Author
@ahmadbaig1 I'm going to close this in favor of this one: https://github.com/Automattic/wp-calypso/issues/94260

Here's some workaround users can try in the meantime: https://themeisle.com/blog/transfer-from-wix-to-wordpress/
