### ISSUE TITLE
Me: Fix password change with 2fa enabled

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#960]
Currently, if a user has 2fa enabled, the flow for changing a password looks like this:

- Go to `/me/security`
- Change password
- Page is reloaded
- User is asked to reauthorize 2fa code after page reloads

We should find a way to ask the user to reauthorize their 2fa code before reloading the page.

**Comment by lancewillett** [comment]
Might be a duplicate of #202

**Comment by lancewillett** [comment]
Closing in favor of older issue.
