### ISSUE TITLE
Editor: Images cannot be inserted via Add via URL option

### ISSUE THREAD

**Issue by mahangu** [Automattic/wp-calypso#9600]
In the Calypso Editor, adding an Image through the `Add via URL` option, results in a `1 file could not be uploaded because an error occurred while uploading.` error. The image does not upload.

#### Steps to reproduce
1) Open/create a Past or Page in the Editor
2) Click Add Media
3) Hit `Add via URL`
4) Enter a valid image URL and hit`Upload`
5) Observe the error message `1 file could not be uploaded because an error occurred while uploading.` and see that the file doesn't upload.

#### What I expected
The image file should upload and you should see the option to insert it into the Post or Page.

#### What happened instead
The file would not upload, and I was presented with the error `1 file could not be uploaded because an error occurred while uploading.` 

#### Browser / OS version
Mac OS X 10.11.6 - Chrome 54.0.2840.98, Firefox 50.0
Other HEs were able to reproduce this as well, so it's almost certainly a cross-browser/platform issue.

#### Screenshot / Video
<img width="1258" alt="screen shot on 2016-11-23 at 15-34-25" src="https://cloud.githubusercontent.com/assets/10125810/20557870/57fb0282-b193-11e6-928e-e50d0162a775.png">

Reported in #533947-c, follow up in #2931856-t.

**Comment by iamgabrielma** [comment]
The same case with an mp3 file for #534484-c, also trying it through wp-admin shows no error message but has no effect.

**Comment by carladoria** [comment]
Seen in in 534491-chat

**Comment by carladoria** [comment]
Seen in 534491-chat

**Comment by KokkieH** [comment]
Another case in #805726-f

The user provided an example of a link that won't add the photo via URL: http://i61.photobucket.com/albums/h73/NinasRoad/IMG_6303_zpsertfglov.jpg

Adding via WP-Admin editor hotlinks the image rather than uploading it, and that works as expected.

**Comment by iamgabrielma** [comment]
Adding another case #2931426-t

**Comment by gracie** [comment]
Another case in #534707-chat

**Comment by supernovia** [comment]
We have several issues here:
http://en.forums.wordpress.com/topic/problems-with-a-number-of-issues

It doesn't seem to matter where the image is coming from; even ones hosted here are returning errors.

**Comment by rachelmcr** [comment]
There are no console errors corresponding with the error seen in the UI.

I checked network requests while uploading a photo using the "Add via URL" option. The POST request to the `/media/new` endpoint returns this response: `{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"errors":[]}}`

**Comment by carladoria** [comment]
another case in #2934018-t

**Comment by thehenrybyrd** [comment]
Another case in #535695-chat
Also tested in Calypso Page editor through adding "Featured Image". Same error.

**Comment by mahangu** [comment]
Another report in #2935636-t

**Comment by dromero20** [comment]
Same error here in #537308-chat

**Comment by dbtlr** [comment]
It looks like this was an error in our API due to some recent upgrades I applied for Jetpack. I patched it up and it appears to be returning normally now for media url uploads.

**Comment by KokkieH** [comment]
Just tested and it's working for me, @dbtlr. I'll reply to the forum threads and ask the users there to also confirm.

**Comment by iamgabrielma** [comment]
Looks like there's another case here: #2941329-t . I couldn't replicate it, uploading via URL works on my end.

**Comment by timmyc** [comment]
Based off some of the comments here, and I just tested this right now and it is working for me, I'm going to close this out.  The last reported [occurrence](https://github.com/Automattic/wp-calypso/issues/9600#issuecomment-264126386) of this was during the time period when it was broken.

@dbtlr could you link to the related API fix here to close up the loop?

**Comment by spncrb** [comment]
Reported for audio in #1322318-chat

**Comment by designsimply** [comment]
Also see https://github.com/Automattic/wp-calypso/issues/14877

**Comment by cesarabeid** [comment]
another instance, reported in [#14877](https://github.com/Automattic/wp-calypso/issues/14877)
