### ISSUE TITLE
Reader: Youtube embed in comments not displaying correctly

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/wp-calypso#9605]
#### Steps to reproduce
1. Navigate to Reader
2. Find a post with a youtube embed in the comments
3. See that it 

#### Browser / OS version
Latest 
Mac/Chrome

#### Screenshot / Video

<img width="658" alt="screen shot 2016-11-23 at 10 07 19 am" src="https://cloud.githubusercontent.com/assets/5835847/20571441/afe36d38-b164-11e6-87b5-1466cf99a861.png">

#### Proposed fix

It seems to fix itself if you get rid of the inline centering style on the `embed-youtube` span but I don't see where that is being applied in the code. 

`<span class="embed-youtube" style="text-align:center;display: block;">`

#dogfooding

**Comment by fraying** [comment]
Nice catch, @kellychoffman! Thank you.
