### ISSUE TITLE
Support connection switch between Google Photos <-> Google Photos Picker

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#96061]
Currently, it works from "Google Photos" to "Google Photos Picker", but we need to support the opposite side.

**Comment by bogiii** [comment]
Endpoint: `public-api.wordpress.com/wpcom/v2/me/connections`

For the case when the Picker feature flag is turned ON with a previously established connection, the connection status is `invalid,` and based on that, we show the upgrade screen.
![Image](https://github.com/user-attachments/assets/1af4db87-a84d-41a4-8f7c-aa7ece972e68)

Otherwise, when we turn OFF the flag, the connection status remains `ok`. We should handle this case and pass the right status in order to support the feature revert use-case.

cc @ouikhuan @zaerl

**Comment by ouikhuan** [comment]
Backend done in: : D166759-code.

**Comment by bogiii** [comment]
Frontend done in: https://github.com/Automattic/wp-calypso/pull/96580

**Comment by bogiii** [comment]
Deployed both FE and BE changes.

**Comment by ouikhuan** [comment]
Adding more gating for backend endpoints here: D167658-code
