### ISSUE TITLE
Remove Jetpack Social Advanced plan on the Complete plan

### ISSUE THREAD

**Issue by alinclamba** [Automattic/wp-calypso#96083]
I noticed that on the [Complete plan](https://jetpack.com/complete/), we still mention the Jetpack Social plan, but the Advanced plan is no longer available. We need to remove "Advanced" since there is only a paid Social plan now.

![Image](https://github.com/user-attachments/assets/d378a6a3-089d-4425-9a67-06f1f4f1ee55)

@Automattic/martech-design is this something you can do or should I report it somewhere else?

**Comment by CodeyGuyDylan** [comment]
This was handled in one of the Growth PRs when updating the Complete card, iceboxing 😄

**Comment by CodeyGuyDylan** [comment]
Right [here](https://github.a8c.com/Automattic/wpcom-a8c-themes/pull/155323/files#diff-5cb9398ffea92e20414ba03f64dfa3801e7a7fd4569ab8b9876624b32df9dc56L1095) is where it was handled, I'll add it to the issue
