### ISSUE TITLE
Reader: Feed Header grav/blav logic

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9608]
Currently, the Feed Header component exclusively uses the Site Icon (blav): https://github.com/Automattic/wp-calypso/pull/9436

This needs to be updated to:

- Display the grav
- If we don’t have grav then blav
- If we don’t have that then nothing
- If a site has multiple authors, use blav

**Comment by fraying** [comment]
So, in other words, in the **header** for any **site view**:

+ If the site has 2 or more authors: Show blav. If no blav, show nothing.

+ If the site has 1 author, show grav. If no grav, show blav. If no blav, show nothing.

Make sense?

**Comment by bluefuton** [comment]
> If a site has multiple authors

Just a note: we don't currently have this information exposed in the API. If we do find a way to add it, it'll only be available for wpcom sites.

**Comment by bluefuton** [comment]
This is waiting on an API patch to land (D3509).

**Comment by bluefuton** [comment]
No plans to implement this one at the moment.
