### ISSUE TITLE
Substack importer: simplify copy to translate plurals easier in "all set" for content -message

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#96112]
The copy of this "all set" text depends on a number of posts, pages and attachments, and each combination (zero, singular plural) needs its own variation. Copy is great, but the amount of text to translate and code complexity is a bit much for something this trivial.

See [code](https://github.com/Automattic/wp-calypso/blob/efd179982934223ca4797cc2df23700a3223d7d2/client/my-sites/importer/newsletter/content-upload/author-mapping-pane.jsx#L15-L74)
Slack convo p1728553977305199-slack-C052XEUUBL4

![Image](https://github.com/user-attachments/assets/742a1aeb-6e88-468b-8feb-60c9000836c1)

Couple options:

- Keep the complexity.
- Use format like:
    ```
    All set! We’ve found:
    %d post, - with plural %d posts,
    %d page, - with plural %d pages,
    %d media - with plural %d media
    ```
- Use format like:
    ```
    All set! We’ve found:
    Posts			%d
    Pages			%d
    Media items		%d
    ```

Here's a visual:

![Image](https://github.com/user-attachments/assets/debc6041-1292-4073-a013-ded20c1bd238)

Or with zero sums:

![Image](https://github.com/user-attachments/assets/00d79620-d218-4f19-9a02-ec1957f75064)

This would be straightforward as we could use the same component as for the summary page:

![Image](https://github.com/user-attachments/assets/50acfaf0-7c42-434d-8afb-fdbf5ec54459)

**Comment by simison** [comment]
@crisbusquets thoughts on above?

I could go with this at least in interim:

![Image](https://github.com/user-attachments/assets/6fdf89d9-ab9d-4535-a018-9332eeff0a39)

**Comment by crisbusquets** [comment]
@simison I replied here :)
https://github.com/Automattic/wp-calypso/pull/96113#issuecomment-2460630778
