### ISSUE TITLE
Default Card Image Flips

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9612]
Sometimes, in the stream, I see a card load with one image that then flips to another.

Why does this happen? Any way for us to avoid it?

Example post: https://wpcalypso.wordpress.com/read/feeds/4716498/posts/1234446309

Video:

![image-flip](https://cloud.githubusercontent.com/assets/24388/20576183/b5c44472-b171-11e6-908e-8f9cc2f8f1e4.gif)

**Comment by blowery** [comment]
Need to revalidate this one. Shouldn't be happening any more.

**Comment by fraying** [comment]
Think it's fixed!
