### ISSUE TITLE
Reduce initial comments shown in FullPost

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#9613]
Currently, we show up to 25 comments on a page. The comment section takes up a lot of page real estate. With Recommended Posts, this problem becomes more common because the posts that are recommended tend to have higher comment counts.

I suggest we reduce the number of comments to around 1-2 comments. We could even consider adding an algorithm to display certain comments:

- comments that have a total of x characters of text (or y lines of text)
- most popular comments (by like count)

This proposal has two benefits:

1. Reduces scrolling past comments to get to More in WordPress links
2. Improves tracking of user's clicking "View earlier comments" to measure the interest in viewing comments

Seems like an easy adjustment if we want to only reduce the comments shown! Initial comment size is set [here](https://github.com/Automattic/wp-calypso/blob/54a3da183a558ff47059ba50a60e5494810042fa/client/blocks/reader-full-post/index.jsx#L356).

Example of post with 3 comments taking up the whole page:
<img width="1439" alt="reader_refresh_fullpost_comment_count" src="https://cloud.githubusercontent.com/assets/4505888/20576132/6db3351c-b171-11e6-9df6-80b333ba3543.png">

**Comment by fraying** [comment]
I'm for this, though I'd set the number to 10 to start. That's a reduction of 15 and it'll give us some signal to see if anyone notices/cares.
