### ISSUE TITLE
Replace Calypso "Testimonials" and "Portfolio" with the corresponding wp-admin versions

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#96183]
> [!IMPORTANT]
> **Project thread: pekYwv-4PY-p2**
> Tracked by #98483 

As part of the Untangling Calypso epic, let's remove the custom implementation of the Testimonials and Portfolio views, in lieu of the corresponding wp-admin versions — **for all users**.

This will reduce confusion navigating between Calypso and proper WordPress admin.

**Note**: to enable Testimonials and Portfolio, head to Settings > Writing and toggle their options.

### Requirements

* Selecting "Testimonials" from the WordPress or Calypso menu opens `/wp-admin/edit.php?post_type=jetpack-testimonial`.
* ~Adding a new Testimonial from the WordPress or Calypso menu opens `/wp-admin/post-new.php?post_type=jetpack-testimonial`.~
* Selecting "Portfolio" from the WordPress or Calypso menu opens `/wp-admin/edit.php?post_type=jetpack-portfolio`.
* ~Adding a new Portfolio project from the WordPress or Calypso menu opens `/wp-admin/post-new.php?post_type=jetpack-portfolio`.~
* Selecting "Portfolio > Project Types" from the WordPress or Calypso menu opens `/wp-admin/edit-tags.php?taxonomy=jetpack-portfolio-type&post_type=jetpack-portfolio`.
* Selecting "Portfolio > Project Tags" from the WordPress or Calypso menu opens `/wp-admin/edit-tags.php?taxonomy=jetpack-portfolio-tag&post_type=jetpack-portfolio`.

**Comment by mmtr** [comment]
> * Adding a new Testimonial from the WordPress or Calypso menu opens `/wp-admin/post-new.php?post_type=jetpack-testimonial`.
> * Adding a new Portfolio project from the WordPress or Calypso menu opens `/wp-admin/post-new.php?post_type=jetpack-portfolio`.

@Copons I think this should be part of the iframed editor removal, right?

**Comment by Copons** [comment]
@mmtr good point, yes. I'll remove them from the requirements for now.

**Comment by mmtr** [comment]
Closing this one out. There are two remaining tasks, but they are being handled on separate issues:

- Stats link is broken for Portfolio Projects: @BogdanUngureanu is preparing a fix for that as part of https://github.com/Automattic/wp-calypso/issues/95621, which will also fix the same issue for Posts (and presumably for Pages)
- We should show a notice the first time a user is enforced to the WP Admin view: Done in https://github.com/Automattic/jetpack/pull/40609, will be shipped shortly (likely tomorrow).
