### ISSUE TITLE
Migration icon is throwing warnings on dev env

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#96228]
## Description
The MigrationFavicon is throwing several warnings in development because there is an "embed" SVG that is using incompatible properties

## How to reproduce
* Site any site as `migration-pending-status` status
* Go to `/site` 
* Select the site with the pending 
* Check the DevTools > Console

> [!NOTE]  
> The error will happing only on development env. E.g. (http://calypso.localhost:3000/)

![Image](https://github.com/user-attachments/assets/78ab0d27-6b95-49ed-b65a-74c9f57be57e)

**Comment by Robertght** [comment]
I'm marking this as triaged on our board because I can see it already has a team assigned.

@gabrielcaires For this type of reports, let's mark the issues as "Triaged" on our board, too, and ping us if you need our input. Thanks!

**Comment by andres-blanco** [comment]
@renatho was this fixed by https://github.com/Automattic/wp-calypso/pull/96259?

**Comment by renatho** [comment]
Yes @andres-blanco! Sorry! I forgot to link the issue.
