### ISSUE TITLE
Enable the GB simultaneous editing post-lock screen for a12s in more circumstances

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#96229]
### Quick summary

GB shows a "this post is already being edited" dialog if two people are editing a post at the same time. This is completely disabled on dotcom for a12s only, to avoid leaking a12 personal data when SUing to users (see fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Scyhtvaf%2Sthgraoret%2Qjcpbz%2Svaqrk.cuc%3Se%3Q6r7prss1%23226-og) 

It would be helpful if we could be a bit more selective when disabling this, to stop a12s from trying to edit a post at the same time.

Some ideas:
 * Detect if using old SU and only disable the feature then
 * Don't disable on p2s
 * Don't disable if you're a user on the site

See discussion: p1731321103057459-slack-C07H21B2W59

### Steps to reproduce

1. Open a post and make an edit
2. Ask another a12 to open the same post and make an edit

### What you expected to happen

To get a "post is already being edited" dialog

### What actually happened

No dialog

![Image](https://github.com/user-attachments/assets/6efa75f4-70a4-4f82-8b56-f0ef11628153)

### Impact

One

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
I'm marking this as triaged on our board because I can see it already has a team assigned. 

@dsas For this type of reports, let's mark the issues as "Triaged" on our board, too, and ping us if you need our input. Thanks!

**Comment by mmtr** [comment]
Opened a fix: D166421-code
