### ISSUE TITLE
Misleading text on the "Activate hosting features" screen

### ISSUE THREAD

**Issue by donalirl** [Automattic/wp-calypso#96262]
### Quick summary

During atomic transfer, the messaging tells users that "your domain will change", referring to the site address change from .wordpress.com to .wpcomstaging.com. A more accurate statement would be "your **default site address** will change". Their _domain_ won't change, but the text in this warning causes fear and confusion for the site owner.

### Steps to reproduce

1. Navigate to https://wordpress.com/sites 
2. Choose a Business plan site that hasn't gone atomic yet
3. Click the Hosting Features tab
4. Click "Activate now"
5. Read the message:

![Image](https://github.com/user-attachments/assets/fb80ea1b-bd0a-45bb-9128-e86527fdc148)

### What you expected to happen

I expected my domain to stay the same when going atomic. It does, but the copy in this warning says the opposite.

### What actually happened

I received the message:

> When you install a plugin, theme, or activate hosting features, your domain will change. 

We should update that paragraph to say something like:

> When you install a plugin, theme, or activate hosting features, **your default site address will change**. Visitors to the old address will be redirected to the new address, or to your domain if you have added one.

Going further, we could add a "learn more" link to this doc to provide more context for the user: https://wordpress.com/support/changing-site-address/#change-a-wpcomstaging-com-address as suggested in #55898 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Here's an example of the confusion this messaging causes: https://wordpress.com/forums/topic/cant-download-csv-of-subscribers/?view=all

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on the platform - Replicated

📌 ACTIONS
- Triaged

📌 Message to Author
@donalirl This makes sense and thank you for raising it!

@Automattic/lego could this be something for you?

**Comment by gavande1** [comment]
Created a diff to fix the text: D166060-code

**Comment by gavande1** [comment]
The diff was deployed in r308708-wpcom
