### ISSUE TITLE
Login: Two different Lost password links

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96285]
### Quick summary

![Image](https://github.com/user-attachments/assets/d9c4d039-65f3-4b18-80f1-b865c511ba07)

"Forgot password" links to https://wordpress.com/log-in/lostpassword
"Lost your password" links to https://wordpress.com/wp-login.php?action=lostpassword

### Steps to reproduce

- Login page
- Use an account with email and password

### What you expected to happen

The two links to be the same

### What actually happened

The links were not the same

### Impact

All

### Available workarounds?

There is no user impact

**Comment by zaguiini** [comment]
I wonder if we should drop the "Lost your password?" link instead of making them the same. Can't see the reason to have them pointing to the same place.

**Comment by escapemanuele** [comment]
I think the "Forgot password" has been added there unintentionally at a certain point
