### ISSUE TITLE
Login: No orphans in wrong password text

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96283]
### Quick summary

It's strange to have words like e-mail split in two lines.

![Image](https://github.com/user-attachments/assets/75ba83c0-020b-49a0-9298-40c2ce5886f3)

### Steps to reproduce

- Login page in Italian
- Email and wrong password

### What you expected to happen

To see "e-mail" all in one line

### What actually happened

"e-mail" was split into two lines

### Impact

All

### Available workarounds?

There is no user impact

**Comment by renancarvalho** [comment]
I can reproduce this issue, marked it as triaged and Groundskeeping
