### ISSUE TITLE
Login: Forgot your password has a forgot your password link

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96290]
### Quick summary

![Image](https://github.com/user-attachments/assets/8f376be2-61bc-49f0-9936-3c39d0db8f1e)

Forgot your password has a forgot your password link

### Steps to reproduce

Go to https://wordpress.com/log-in/lostpassword

### What you expected to happen

Not seeing a link at the bottom

### What actually happened

I see a link

### Impact

All

### Available workarounds?

There is no user impact

**Comment by renancarvalho** [comment]
I am able to reproduce this, indeed it makes no sense to show the lost password link if the user is already on the lost password page.
Triaged.
