### ISSUE TITLE
Onboarding: Where do users land, /home or /wp-admin?

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#96310]
I'd like to clarify what happens after the initial onboarding steps. 

![Image](https://github.com/user-attachments/assets/9fe78c5d-111c-4ca6-86e0-f4f90804c43f)
[You can check this Figma file for reference](https://www.figma.com/design/W9xI27S6Swvw5Ku21EbZvn/Dotcom-Onboarding?node-id=6213-46989&t=zAXwun0rbZiTwbHu-4)

**Logged-out**
Users who go through our onboarding flow from our homepage.

* Select goals → New account → /home
* Select goals → Existing (logs in) → /home
* Skip to admin → New account → /wp-admin
* Skip to admin → Existing → /wp-admin

**Logged-in**
Users who create a new site from /sites:

* Select goals → {user is flagged as developer} → /wp-admin
* Select goals → {not flagged as developer} → /home
* Skip to admin →  {user is flagged as developer} → /wp-admin
* Skip to admin → {not flagged as developer} → /home

Relates to: https://github.com/Automattic/wp-calypso/issues/95840

**Comment by nuriapenya** [comment]
@richtabor 👋🏼 wanted to double-check this part of the onboarding, which came up in a discussion today with @autumnfjeld and @p-jackson .

I think the general consensus was users should always land on My Home (/home), where the Launchapd will take over.

But in past conversations we also pondered what happens to those who choose "Skip to admin" and are flagged as developers. In this case, should they go to /wp-admin? And if so, how do we surface the Launchpad?

Same goes with the logged-in case: From /sites, when someone is adding a new site, I hope we trigger this new onboarding flow - so assuming users skip to admin, I'd expect to drop them in wp-admin if they are flagged as devs.

I tried to map the cases above 👆🏼 lemme know if that makes sense.

**Comment by richtabor** [comment]
> I think the general consensus was users should always land on My Home (/home), where the Launchapd will take over.

I was thinking we'd land here. We can clean up My Home to give the launchpad appropriate prominences (it's quickly lost as-is). 

![Image](https://github.com/user-attachments/assets/d12694e3-5880-4595-8822-84561d31e7d9)

> But in past conversations we also pondered what happens to those who choose "Skip to admin" and are flagged as developers. In this case, should they go to /wp-admin? And if so, how do we surface the Launchpad?

My Home would still be available for those sites, correct? Just not as the top-level view. The launch pad in My Home would be accessible there, but if these are developers, I'm curious how helpful My Home is to them.

**Comment by nuriapenya** [comment]
> My Home would still be available for those sites, correct? Just not as the top-level view.
@richtabor, exactly./home It's available, but when opening WordPress.com, they are defaulted to wp-admin, and when they create a new site, they also go straight to wp-admin.

There's a chance they don't go to the Calypso home at all. 

On a related note, [here are some first drafts/ideas ](https://wp.me/p9Jlb4-eTm) on cleansing My Home. I'll post an iteration this week, but it would be good to figure out the developers/skip flow in parallel too. 

Thanks for the feedback!

**Comment by nuriapenya** [comment]
After speaking with @autumnfjeld and @p-jackson, we decided to keep it simple (as in what can be done for today), and we'll default to `/home` (Calypso) for all the scenarios until we have a better idea where the Untangling project is heading to. We can always revise this.
