### ISSUE TITLE
Map new goals to existing Design Picker categories

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96325]
This is a quick piece of work to best align the new Goals with the best Design Picker category.  See the [Onboarding Goals spreadsheet](https://docs.google.com/spreadsheets/d/1zILBEO5Yb9VVzxJmY5o1quR7XOQdOQkKlQ8G7wEQsAY/edit?gid=526360926#gid=526360926&range=G4) for mapping information: 

| Goals | Design Picker |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/115e1be3-2b7b-41b5-9615-d2209cf201ac)  | ![Image](https://github.com/user-attachments/assets/90a2a622-eccd-4286-a2c6-38c48d38b1a0)  |

### Mapping
![Image](https://github.com/user-attachments/assets/9c203019-1e04-4c78-9718-a97da8410a8f)

Later work, like [Add goal-centric filtering for design picker](https://github.com/Automattic/wp-calypso/issues/95495#top)  will adapt the UI of the Design Picker and set up more sophisticated matching between Goals and themes.

**Comment by autumnfjeld** [comment]
@p-jackson   We could start this in the next day or two if you have bandwidth (e.g. after Groundskeeping commitments).  Waiting for confirmation on the mapping p1731456952429269/1731454668.413339-slack-C07H21B2W59

**Comment by p-jackson** [comment]
I've implemented the new goals selection logic in https://github.com/Automattic/wp-calypso/pull/96386

When the user selects multiple goals it might correspond to multiple categories. Because the design picker doesn't currently support filtering by multiple categories we have to decide which category is most important. This is the order I'm using.

```ts
	// Sorted according to which theme category makes the most consequential impact
	// on the user's site e.g. if you want a store, then choosing a Woo compatible
	// theme is more important than choosing a theme that is good for blogging.
	// Missing categories are treated as equally inconsequential.
	const mostConsequentialDesignCategories = [
		CATEGORY_STORE,
		CATEGORY_EDUCATION,
		CATEGORY_COMMUNITY_NON_PROFIT,
		CATEGORY_ENTERTAINMENT,
		CATEGORY_PORTFOLIO,
		CATEGORY_BLOG,
		CATEGORY_AUTHORS_WRITERS,
	];
```
