### ISSUE TITLE
Plugins details: The separator in the right-hand sidebar is barely visible

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#96359]
### Quick summary

In the plugin details screen, the sections separator in the right-hand sidebar is barely visible, it would benefit from some contrast ![Image](https://github.com/user-attachments/assets/7723d7f9-a33e-4afc-8329-08532eb5ce95)

### Steps to reproduce

1. Navigate to a plugin details screen, e.g. `https://wordpress.com/plugins/wordpress-seo-premium/:siteId` replacing `:siteId` by a site
2. Check the right-hand sidebar

### What you expected to happen

The sections are clearly separated

### What actually happened

There is a separator there, but the contrast is not enough 
![Image](https://github.com/user-attachments/assets/542e5c22-0f3a-458e-b776-4520ce6f1b12)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Originally found during p58i-iGP-p2

**Comment by andregardi** [comment]
I am able to reproduce it.
Will lower the priority to Normal. But will probably address it during this groundskeeping anyway since seems to be easy to fix.
