### ISSUE TITLE
Plugins marketplace: The Yoast SEO icon is not displayed for some users

### ISSUE THREAD

**Issue by epeicher** [Automattic/wp-calypso#96358]
### Quick summary

The Yoast SEO icon is not displayed _for some users_ in both, the Spotlight banner and in the plugin card

|Spotlight banner | Plugin card|
|-------|------|
|![Image](https://github.com/user-attachments/assets/fd3fe76b-ab49-4083-b928-7fb8fe1c33e1) | ![Image](https://github.com/user-attachments/assets/ae6a135b-978a-4449-bc2e-515eacb3fcaf) |

### Steps to reproduce

1. Navigate to either https://wordpress.com/plugins
2. Check the `Drive more traffic with Yoast SEO Premium.` banner

### What you expected to happen

The banner and plugin card should contain the Yoast logo

### What actually happened

For some users, the logo is not displayed and there is an error in the Network panel in the Developer Tools 
<img src="https://github.com/user-attachments/assets/d7db602b-fc2a-4e89-a692-be6f5c46830c" width=200 />

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Originally found during p58i-iGP-p2

**Comment by Robertght** [comment]
I'm marking this as Triaged, as someone is taking care of it. 

Please let us know if you need our input.

**Comment by zaguiini** [comment]
I was going to triage it but didn't have a lot of time and was thinking of coming back later. I've unassigned myself in case someone wants to take it.

**Comment by epeicher** [comment]
I have lowered the Priority to Low (it was labeled automatically as High) as I don't think it is an important bug, and it is not reproducible for all users

**Comment by epeicher** [comment]
Update: the issue with the image seems to be reproducible now, for example https://wordpress.com/plugins returns ![Image](https://github.com/user-attachments/assets/2be2017b-8ed4-48a5-bb8e-9ead7729fa2c)

**Comment by gcsecsey** [comment]
This is fixed by https://github.com/Automattic/wp-calypso/pull/96504
