### ISSUE TITLE
Goals screen: ensure goals are presented randomly

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#96369]
Rather than presenting the goals in the same format each time, to get better data, let's ensure the goals are randomized. Opening this as it's been discussed but I couldn't find a dedicated issue for it.

**Comment by p-jackson** [comment]
Goal randomisation was implemented in the initial PR which added the new goals https://github.com/Automattic/wp-calypso/pull/95707 👍

**Comment by annezazu** [comment]
Weee! Thank you for confirming.
