### ISSUE TITLE
Help Center Lacks Clear Option to Open Contents in a Separate Tab

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#96396]
Currently, users can open the contents of the Help Center in a separate tab by clicking the title, but this action is not obvious and lacks visual cues. A more explicit option to open the support content in a new tab would improve accessibility, especially for users who prefer viewing help resources in a larger, separate window.

<img src="https://github.com/user-attachments/assets/7396d6e9-822f-4191-8c55-aef94d3255f9" width="348">

Possible solutions by @lucasmendes-design  [here](https://github.com/Automattic/wp-calypso/issues/96396#issuecomment-2477062991):

1)
![Image](https://github.com/user-attachments/assets/ea764f80-af74-4d3f-ba39-76f3cebe2a75)

2) 
let's just change the title color from gray to blue on hover. Also on hover, we can show the external icon.

**Context:** p58i-iGA-p2

**Comment by escapemanuele** [comment]
@lucasmendes-design I don't clearly remember that, but we used to have the external icon right to the title. Have we decided to remove it or was it by accident?

**Comment by lucasmendes-design** [comment]
> I don't clearly remember that, but we used to have the external icon right to the title. Have we decided to remove it or was it by accident?

I believe it was an accident. I haven't touched on these screens, and agree that we need a better affordance here. It's not clear to users that the title is clickable.

**Comment by escapemanuele** [comment]
The `ExternalLink` component accepts a iconComponent

![Image](https://github.com/user-attachments/assets/1584ca69-4565-4482-bca0-573ae13bd758)

But I don't know if I'm fully convinced by this

**Comment by lucasmendes-design** [comment]
Yep, it's not great. Plus, clicking on the heading is not a common UX pattern that we used to use. 

Can we do something like this? 
![Image](https://github.com/user-attachments/assets/b33ed670-5e35-412e-b5fe-e501f9fc7fea)

**Comment by escapemanuele** [comment]
That's not super immediate, since the part that starts from "A site icon, also..." is part of the content of the article already and comes from Support. 
But if needed we can do it, targeting the table of contents and inserting the link before that

**Comment by lucasmendes-design** [comment]
Got it. Let's do something simpler then. Do you think the solution below is simpler? 

![Image](https://github.com/user-attachments/assets/9cf6bfd1-4bda-4e7f-8b96-4527bc6dc796)

**Comment by lucasmendes-design** [comment]
If it's not, let's just change the title color from gray to blue on hover. Also on hover, we can show the external icon.
