### ISSUE TITLE
Purchases: Add ability to cancel Premium Theme

### ISSUE THREAD

**Issue by KokkieH** [Automattic/wp-calypso#9639]
#### Steps to reproduce
1. Start with a site that has a Premium Theme
2. Visit https://wordpress.com/settings/general/
3. Attempt to delete the site
4. A warning appears that the site cannot be deleted as it has Premium upgrades
   
- Until recently that warning did not show for sites that only have Premium themes, and there are two existing issues to add this warning in #4530 and #1251

5. Click the Manage Purchases button.

#### What I expected
To be able to cancel the upgrade from Purchases, as instructed in the warning on the Settings page.

#### What happened instead
Purchases does not show any option to cancel a Premium Theme upgrade, making it impossible to delete a site with a premium theme without staff help.

#### Screenshot / Video

Message on Settings page:

<img width="544" alt="site_settings_ _site_title_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/20621625/e7a25adc-b307-11e6-9f24-9f06b82a03e0.png">

Upgrade showing on Purchases, but not showing any option to remove the upgrade.

<img width="763" alt="purchases_ _manage_purchase_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/11873759/20621674/0c3b6d34-b308-11e6-81c4-80473b965d7e.png">

#### Context / Source

User posted in the [public forums](http://en.forums.wordpress.com/topic/organization-4) about being unable to delete their site due to this.

**Comment by KokkieH** [comment]
Had 3 requests in one week for help with this in 805706-f. It appears more people want to cancel upgrades/delete sites at this time of the year - this is a definite spike in support requests on this issue.

**Comment by eduardozulian** [comment]
Got this also on 3023393-t

**Comment by eduardozulian** [comment]
Another request on 3237820-t

**Comment by kriskarkoski** [comment]
3341653-t

**Comment by kriskarkoski** [comment]
I'm not sure if allowing users to cancel Premium themes will cause more support issues with it being accidentally deleted on a site they wanted to keep it on and we're intending to delete and we should instead just allow users to delete a site with a premium theme active with appropriate warnings.

**Comment by KokkieH** [comment]
Good point, @kriskarkoski. If I'm not mistaken, that's how it used to work - I've seen SAs showing Premium themes on deleted sites, so it must have been possible at one point.

**Comment by kriskarkoski** [comment]
For clarity on the above idea, I opened a new issue at #17012 to reflect the preferred option of allowing the site to be deleted with the theme active with proper warning rather than allowing premium themes to be canceled from Purchases, which could have unintended consequences with accidental cancelations on sites not intending to be deleted. Marking this issue as closed.
