### ISSUE TITLE
Layout broken on connection screen for existing passwordless users

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wp-calypso#96408]
## Issue description

Existing users with a passwordless account currently see a broken layout in the Woo connection screen.

![Image](https://github.com/user-attachments/assets/f43b72a2-7db6-4ebb-aa8f-f6d4a7273b73)

### Steps to reproduce

1. You will need two wordpress.com accounts. The second account must be passwordless.
2. Log-in to wordpress.com with the first account. 
3. Initiate the WordPress.com account connection screens from a new WooCommerce plugin installation.
4. Click "Sign-in as a different user"
5. Enter the email address for the second account and continue.
6. See the broken layout

**Comment by moon0326** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/96428
