### ISSUE TITLE
Janky transition to the loader on WooCommerce connection screen

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wp-calypso#96420]
## Issue Description

When connecting a store, the transition to the loader appears janky. This looks to be caused by a delay to show the first image, making the text re-position suddenly.

I have attached normal speed and slow motion video capture below:

### Normal speed video

https://github.com/user-attachments/assets/5126e37c-215c-453d-b1e3-f32990f90523

### Slow motion video

https://github.com/user-attachments/assets/7bd40cc2-85ce-4e74-8074-bafc8d484e25

## Steps to reproduce

1. After installing WooCommerce, select Jetpack in the core profiler and proceed to the connection screen
2. Select an account and click "Connect to WordPress.com"
3. Observe jankiness in the transition

**Comment by moon0326** [comment]
Fixed it with [Preload setup page on the authorize page #96558](https://github.com/Automattic/wp-calypso/pull/96558)
