### ISSUE TITLE
Me: When a site owner disables "Show Avatars" option, there are display issues with toolbar's "Me" link

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/wp-calypso#9643]
When a site owner disables "Show Avatars" option for comments, a user's Gravatar isn't displayed in the toolbar's "Me" link and there's an overlap on mobile devices.

#### Steps to reproduce
1. Starting at URL: /wp-admin/options-discussion.php (this option isn't currently available in Calypso.)
2. Under the Avatars section of the above page in your site's /wp-admin, uncheck the option next to "Show Avatars" in order to stop Gravatars from displaying next to comments. 
3. Save your changes and view your site. 

#### What I expected

While logged into WordPress.com, I still expected to see my Gravatar in the upper right of the toolbar when viewing the site and for that Gravatar to link to the "Me" section of WordPress.com:

<img width="100%" alt="screen shot 2016-11-25 at 11 18 42" src="https://cloud.githubusercontent.com/assets/2998162/20623770/27b8e368-b301-11e6-9711-f9c483b0a0a7.png">

#### What happened instead

My Gravatar no longer displayed in the upper right of the toolbar when viewing the site. It was replaced by a default Avatar outline, which was slightly off centre:

<img width="100%" alt="screen shot 2016-11-25 at 12 03 00" src="https://cloud.githubusercontent.com/assets/2998162/20624908/9748c486-b307-11e6-8185-77edd87e4667.png">

The Avatar also overlaps with another icon in the toolbar on mobile devices:

<img width="100%" alt="screen shot 2016-11-25 at 12 06 42" src="https://cloud.githubusercontent.com/assets/2998162/20624939/c93d0de4-b307-11e6-8c9e-f302ed456106.png">

This can also be replicated on some high profile sites, such as metro.co.uk.

#### Browser / OS version

Desktop: Chrome / macOS Sierra
Mobile: Chrome / Android 7

#### Context / Source

Reported here: http://en.forums.wordpress.com/topic/the-toolbar-buttons-wont-align-properly-on-mobile-browsers

#user-report

**Comment by kathrynwp** [comment]
User reports that the issue is no longer present.

**Comment by SiobhyB** [comment]
It looks like this was fixed by @lancewillett. :) Closing.

**Comment by lancewillett** [comment]
Thanks, yes: fixed in r146930-wpcom.
