### ISSUE TITLE
Fix wrong download buttons height on Studio landing page

### ISSUE THREAD

**Issue by stephanethomas** [Automattic/wp-calypso#96458]
### Steps to reproduce

1. Go to https://developer.wordpress.com/studio/
2. Notice that the download buttons don't have the same height

### What actually happened

![Image](https://github.com/user-attachments/assets/0494c507-70c5-4bab-ac51-88ec1e023b12)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

I tested this on Chrome and Edge on Windows.

**Comment by Robertght** [comment]
I can see this as well but I'll mark this as Triaged on our board as it's already been looked into.
