### ISSUE TITLE
Dyad2 theme, attempt to add Tags to post, they disappear.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#96466]
### Quick summary

When adding Tags to a post, either new or existing, after typing a character or two, the characters disappear. You must click into the Tags field again. This will repeat. I found when adding Tags, if the tag exists, and it pops up while trying to add, if you click the tag fast enough, it will populate the field. If not, they disappear.
![Image](https://github.com/user-attachments/assets/efbcb66b-aaa3-400b-8354-502ac586a762)

### Steps to reproduce

1. using Business Simple test site, added Dyad2 theme.
2. Added tags for posts.
3. created post, attempt to add tags, they disappear.

### What you expected to happen

The letters (characters) should stay in the field. If they  match a tag, the tag should pop up.

### What actually happened

If the tag exists, and you begin typing matching letters, the tags will show, but only for a second, then they disappear.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by radtechgh** [comment]
9046961-zen

**Comment by aisajib** [comment]
This issue may not be dependent on the Dyad2 theme. Possibly the larger issue (with more user reports) is here: https://github.com/Automattic/wp-calypso/issues/96469

**Comment by radtechgh** [comment]
Another report, this site uses 2010 theme: 9051014-zen
