### ISSUE TITLE
Tags vanishing when trying to be added to posts.

### ISSUE THREAD

**Issue by CodeAllNightNDay** [Automattic/wp-calypso#96469]
### Quick summary

Tag text is vanishing when trying to type them into post in the editor. The issue doesn't seem to be theme dependent, and can be reproduced on simple and Atomic sites.

### Steps to reproduce

1. Open up any simple or At site.
2. Start typing to add a new or existing tag.
3. The text will vanish before the tag can be added.

### What you expected to happen

For tags to be added to posts.

### What actually happened

The text tag vanished after entering some characters.

### Impact

Most (> 50%)

### Available workarounds?

Yes - use the classic editor:

![Image](https://github.com/user-attachments/assets/7b39c04c-843b-42ef-a2e0-0086b7be5496)

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Here is how the issue looks when trying to add tags
https://github.com/user-attachments/assets/0af4d7d2-4ae7-4794-a547-a24253f4e953

**Comment by CodeAllNightNDay** [comment]
9047987-zd-a8c Issue for this one.

**Comment by CodeAllNightNDay** [comment]
Same issue here 9048107-zd-a8c

**Comment by marutim** [comment]
Same issue here: 9049132-zd-a8c
Theme: Yoko (retired)

**Comment by marutim** [comment]
Another report: 9048871-zd-a8c
Theme: Traveler (Retired)

**Comment by mxhassani** [comment]
9049222-zen
Theme: Viral (non a8c)

## Workaround
Use the classical view and add the tags from the wp-admin posts list.

**Comment by mxhassani** [comment]
9048612-zen
Theme: Libretto

**Comment by ezebecke** [comment]
9050643-zen

Suggested workaround with Classic View

**Comment by Jaykame** [comment]
9050803-zen 
Theme: RecipeBook
Simple site
Suggested workaround with Classic View.

**Comment by wiesenhauss** [comment]
Multiple instances reported in the forums: 

https://wordpress.com/forums/topic/i-have-a-problem-with-adding-a-new-tag/?view=all
https://wordpress.com/forums/topic/cant-attach-tags-to-a-post/?view=all
https://wordpress.com/forums/topic/tags-265/?view=all
https://wordpress.com/forums/topic/cannot-use-tags/?view=all

**Comment by AriesJoseph** [comment]
9051708 - Zen

**Comment by supernovia** [comment]
Another case on multiple sites here:
9053846-zd-a8c

I was temporarily able to add tags, then it stopped working again

**Comment by kelasante** [comment]
Another report in 9054160-zen

**Comment by talldan** [comment]
There's an issue reported in the Gutenberg repo for this too - https://github.com/WordPress/gutenberg/issues/67058.

And some reports in the WordPress.org forums - https://wordpress.org/support/topic/wordpress-shaking-while-in-edit-mode/#post-18139467.

**Comment by Neha93517** [comment]
Zen-9056092
Shared workaround with Classic view.

**Comment by Robertght** [comment]
I can see there's a fix for it here: https://github.com/WordPress/gutenberg/pull/66625 

@ramonjd correct me if that's not the same, however, do we need to wait until Gutnberg 19.7 to be released? If yes, when should we see this released because I can see a lot of reports piling up.

**Comment by rajwpdev117** [comment]
Another report 9052042-zen.

**Comment by supernovia** [comment]
9053846-zd-a8c

**Comment by ahmadbaig1** [comment]
9050007-zd-a8c
Shared classic view "Quick Edit" work around.

**Comment by xavier-lc** [comment]
9057330-zd-a8c

**Comment by obenland** [comment]
9055153-zd-a8c

**Comment by paulopmt1** [comment]
We just got [the fix for this issue](https://github.com/WordPress/gutenberg/pull/66625) at [the Gutenberg 19.6.4](https://github.com/WordPress/gutenberg/releases/tag/v19.6.4) and started the Dotcom release process for fixing it on our sites.

**Comment by aisajib** [comment]
Another report here: 9054021-zd-a8c

Suggesting the wp-admin workaround for now.

**Comment by mdtanjid0** [comment]
- [ ] 9059883-zen (needs to be followed up).

**Comment by rosepajaroja** [comment]
9048546-zd-a8c

shared the Classic View workaround

**Comment by paulopmt1** [comment]
This fix was released to simple sites Yesterday and just released to all Atomic sites: p1732032544984469-slack-CBTN58FTJ

**Comment by LovingBrother** [comment]
Great work, team! I will test the fix on my end and follow up with users who are still asking about the status of the bug

**Comment by musicalcoderx1** [comment]
Which release of WordPress did this fix make it into?

**Comment by ramonjd** [comment]
> Which release of WordPress did this fix make it into?

6.7. The original [Gutenberg bug fix PR](https://github.com/WordPress/gutenberg/pull/66625), was included in the [6.7 RC3 package update](https://github.com/WordPress/wordpress-develop/pull/7693).
