### ISSUE TITLE
Tags disappear while trying to add them

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#96479]
### Quick summary

Adding tags changed over the last weeks and is currently unexpected.

### Steps to reproduce

1. Add a new post
2. Start typing a tag. When you give yourself a 2-3 second break, the tag disappears and you need to retype it. Second time it's okay
3. Add 2-3 tags
4. Add a word and then ","
5. Adding the "," removes the focus

### What you expected to happen

1. Tags should not disappear if I stop typing
2. The focus should not be lost when I use ","

### What actually happened

1. Tags disappear
2. The input loses focus

https://github.com/user-attachments/assets/1b8909ac-1ec8-4c71-bb43-ccadfd632cca

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome, Desktop

**Comment by nicolynramos** [comment]
Another report here: 9053375-zd. Also able to reproduce on testing sites.

**Comment by jerrysarcastic** [comment]
Reported in 9053574-zd-a8c (simple site) and also I was able to confirm on my test site (also simple)

**Comment by ricklabsdotn8** [comment]
9055201-zd

The workaround appears to be pressing Enter/Return immediately after typing the tag
https://github.com/user-attachments/assets/b537b15e-be9e-4c8e-a29d-19ffb3579bc3

**Comment by dzver** [comment]
> The workaround appears to be pressing Enter/Return immediately after typing the tag

Still loses the focus. I used to be able to just type
Travel, Blogging, Portugal - and it would just work without any clicks and disappearing tags

**Comment by devNigel** [comment]
Another report: 9055224-zd-a8c

The workaround suggested above appears unreliable and may be difficult for most users. 

For my user, I suggested using Classic View of the post list and assigning tag from the Quick Edit option. 

![Image](https://github.com/user-attachments/assets/8db3f6da-4a41-486e-9c27-e00a485aec1f)

**Comment by jromales** [comment]
9054740-zd-a8c - I suggested @devNigel's workaround to my user; to use Classic View and add tags in Quick Edit

**Comment by Robertght** [comment]
To prevent further confusion, I'm going to close this one in favor of this: https://github.com/Automattic/wp-calypso/issues/96469
