### ISSUE TITLE
Bug: Post Tag text disappears on creating/searching on the post editor

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#96475]
### Quick summary

When creating/writing an existing tag on the post editor, the tag text disappears. I was able to replicate the issue on the user's site as well as on my simple and atomic test site. 

User's site video: 
https://github.com/user-attachments/assets/aae60206-c9be-4e21-ba34-de1092e49359

User's site with console open video: 
https://github.com/user-attachments/assets/f50dae20-8c54-4466-94e5-4a8a388a07ff

Ticket: 9049647-zd-a8c

It is expected for the text written in the field to stay as it is and gets selected/created.

### Steps to reproduce

1. Open a post in the editor
2. Add an existing tag or create a new tag
3. After adding some characters, it gets disappeared

### What you expected to happen

When a new tag is created, it should be created and selected and shown on the post editor. And when an existing tag is searched, it should stay on the screen and should be able to select.

### What actually happened

The tag disappeared when typing.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by Robertght** [comment]
Thanks @galakhyati !

I'm closing this in favor of https://github.com/Automattic/wp-calypso/issues/96469
