### ISSUE TITLE
Typed texts get removed automatically when trying to add tag from the post editor

### ISSUE THREAD

**Issue by dev-sabbir** [Automattic/wp-calypso#96474]
### Quick summary

From the right sidebar of the post editor, we can create and/or add tags for a post. When typing in the tag input field, the typed texts get removed automatically. 

https://github.com/user-attachments/assets/3f50d11d-6b39-4e06-9b77-ec4e708e6f12

### Steps to reproduce

1. Open a post in edit mode.
2. Open the right sidebar 
3. Try adding a tag from the tag input field.

### What you expected to happen

If there are existing tags that matches the typed text it should show up as options, or I can press space to add a new tag.

### What actually happened

My typed text was removed automatically from the input field. 

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by LovingBrother** [comment]
- It seems a walkaround is to type fast and enter or user comma (,) to add the tag
- Which shows that the error is a result of the tag textbox refreshing per time

**Comment by coder-mahfuz** [comment]
zen-9051102

**Comment by coder-mahfuz** [comment]
9047863-zen

**Comment by coder-mahfuz** [comment]
9051288-zen

**Comment by elcristofue** [comment]
9050705-zen

**Comment by dsas** [comment]
Looks like the same issue as https://github.com/Automattic/wp-calypso/issues/96469 which has been escalated.
