### ISSUE TITLE
Comment Like-Hovers on WP.com Blog look odd

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#96496]
![Image](https://github.com/user-attachments/assets/49df4f42-1558-4509-abdb-565dbfa56ddb)

Noticed on the WP.com blog. 

- Chrome Version 131.0.6778.33
- MacOS 14.6.1

I expected something more refined like the sharing button popovers for likes:

![Image](https://github.com/user-attachments/assets/96e8a1f9-bc82-418e-a4ac-d4d3ee9bcf69)

**Comment by ianstewart** [comment]
@dzver I wasn't able to replicate this with other blogs so I think this might be a WP.com blog theme issue, which I think falls under your team. (But it might not.)

**Comment by briowill** [comment]
Added fix in https://github.a8c.com/Automattic/wpcom-a8c-themes/pull/155278
