### ISSUE TITLE
eCommerce onboarding: Fatal error after onboarding caused by WooCommerce

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#96499]
### Quick summary

After creating a new eCommerce flow, the user is redirected to a new Atomic site, in WP-Admin, that's crashed: There has been a critical error on this website. Please check your site admin email inbox for instructions. If you continue to have problems, please try the [support forums](https://wordpress.org/support/forums/).

After refreshing the page, the site starts working as expected. Nevertheless, this gives a bad experience to our users.

After doing some light debugging, it seems the error is triggered by WooCommerce:
```
[18-Nov-2024 14:48:59 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_task() on null in /wordpress/plugins/woocommerce/9.4.1/src/Internal/Admin/WcPayWelcomePage.php:595
Stack trace:
#0 /wordpress/plugins/woocommerce/9.4.1/src/Internal/Admin/WcPayWelcomePage.php(159): Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->get_active_payments_task_slug()
#1 /wordpress/core/6.7/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Admin\WcPayWelcomePage->register_menu_and_page('')
#2 /wordpress/core/6.7/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.7/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.7/wp-admin/includes/menu.php(161): do_action('admin_menu', '')
#5 /wordpress/core/6.7/wp-admin/menu.php(412): require_once('/wordpress/core...')
#6 /wordpress/core/6.7/wp-admin/admin.php(158): require('/wordpress/core...')
#7 /wordpress/core/6.7/wp-admin/index.php(10): require_once('/wordpress/core...')
#8 {main}
  thrown in /wordpress/plugins/woocommerce/9.4.1/src/Internal/Admin/WcPayWelcomePage.php on line 595
```

### Steps to reproduce

- Go to [WordPress.com/pricing](http://wordpress.com/pricing)
- Select eCommerce
- Create a new site
- Land in WP-Admin where you get the "There has been a critical error on this website. Please check your site admin email inbox for instructions. If you continue to have problems, please try the [support forums](https://wordpress.org/support/forums/)."
 - Refresh the page and it starts working.

### What you expected to happen

- I should get a working WP-Admin

### What actually happened

I got a crashed site.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

- Refresh the page

### Platform (Simple and/or Atomic)

Atomic

**Comment by dsas** [comment]
Was fixed in Woo 9.4.2
