### ISSUE TITLE
Set up a 10% holdout for the write/sell branch removal

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96519]

**Comment by p-jackson** [comment]
Follow up convo: p1732142110882399/1731454668.413339-slack-C07H21B2W59

This "test" won't exactly be a test. We'll implement a long-running 10% holdout. Changes like this one (removing Write and Sell), plus other changes (e.g. changing copy) will be shipped using the hold out.

I'll update the task title.

**Comment by p-jackson** [comment]
ExPlat experiment is being reviewed.

pbxNRc-4zR-p2
22115-explat-experiment

**Comment by p-jackson** [comment]
Experiment was approved.
