### ISSUE TITLE
Error when returning to the migration DIY flow

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#96510]
### Quick summary

This error was originally reported in p7DVsv-lGw-p2#comment-51714 by @cuemarie.

When we choose the DIY flow and continue later, sometimes it gives an error "Getting the migration key". I didn't find the exact reason, but I recorded a video with the error coming from the API.

https://github.com/user-attachments/assets/b3c90203-5a92-4117-b018-425bdefe6af2

### Steps to reproduce

1. Start a migration choosing the "I'll do it myself" option in the "How do you want to migrate?" step. This can be done following the steps:
  1.1.  Navigate to `/start`.
  1.2. Choose "Import existing content or website" in the goals step.
  1.3. Navigate through the flow, selecting to migrate from a WordPress site, and the "I'll do it myself" option.
3. When you are in the migration instructions screen, close the window.
4. Navigate to `/sites`.
5. Click on the site with the pending migration.
6. Click on "Start your migration".
7. I didn't identify the best way to reproduce it, but as you can see in the video I sent, it worked the first time it was loaded, but it was broken after the refresh with the error 403 - "Sorry, you are not allowed to do that" coming from the API.
### What you expected to happen

Return the key properly.

### What actually happened

An error happened while fetching it from the API.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by sixhours** [comment]
Added this to Serenity's board.

**Comment by sixhours** [comment]
Reducing this to High priority since, out of the entire WP.com user base, it's going to apply to a relatively small number of people.
