### ISSUE TITLE
Application Passwords on Migrations: Create success callback endpoint

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#96537]
More context: paYKcK-5B6-p2

In the migration flow, when users request authorization for the Application Password, they are redirected back to WordPress.com after confirming their request. In this case, we need an endpoint that will trigger the chain of jobs for the assisted flow. As the main one, create the admin user with the Application Passwords. Please remember that we'll not store the Application Passwords, and we should also queue the job to remove them once we successfully queue the chain of the Assisted Migration jobs.

We may want to protect the callback URL using nonces: https://developer.wordpress.org/apis/security/nonces/. Hence, making it necessary to generate the callback URL in the back end as I suggested here: p1731981573137839-slack-C0Q664T29

**Comment by andres-blanco** [comment]
diff for accepted/rejected endpoints here D167311-code
