### ISSUE TITLE
Sites: Jetpack link to WP-Admin always uses HTTPS

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9655]
#### Steps to reproduce

1. Starting with a Jetpack site connected to WordPress.com. That site must **not** be using HTTPS.
2. Go to wordpress.com and click on My Sites
3. Select the Jetpack site
4. Click on the WP-Admin link at the bottom of the sidebar.

#### What I expected
I expected to see the site preview without any errors.

#### What happened instead
The site loads using HTTPS, which may not be available if the site doesn't use HTTPS.

**Comment by lancewillett** [comment]
I can't repeat this one exactly, because Jetpack sites don't have a WP-Admin link in Calypso sidebar (only WP.com sites older than Sep 2015 do).

See https://github.com/Automattic/wp-calypso/issues/11108
