### ISSUE TITLE
Reader Refresh: feed header image can make follower count hard to read

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9656]
On feed streams that have a site header image, the follower count can be obscured by the image. For example:

<img width="948" alt="screen shot 2016-11-28 at 11 36 35" src="https://cloud.githubusercontent.com/assets/17325/20652530/fab5f9d0-b55f-11e6-8a94-20480fb29732.png">

from http://calypso.localhost:3000/read/feeds/26990 (private blog)

**Comment by fraying** [comment]
We show site headers on the Site View?

I don't see one here: https://wpcalypso.wordpress.com/read/feeds/26990

![screen shot 2016-11-30 at 9 37 10 am](https://cloud.githubusercontent.com/assets/24388/20763841/9893728c-b6e0-11e6-9ea1-cebbd76a1dd1.png)

**Comment by bluefuton** [comment]
Well, this is confusing! I see:

<img width="915" alt="screen shot 2016-12-01 at 09 01 29" src="https://cloud.githubusercontent.com/assets/17325/20768952/d1cd422a-b7a4-11e6-869e-276d8642333f.png">
