### ISSUE TITLE
Errors when setting up a plan on Pressable

### ISSUE THREAD

**Issue by davoraltman** [Automattic/wp-calypso#9658]
When setting up a plan for a Pressable site (id 119918475), this error was encountered on the installation page:

<img width="578" alt="screen shot 2016-11-28 at 8 43 54 am" src="https://cloud.githubusercontent.com/assets/10340370/20659991/522efaea-b547-11e6-93d4-b8a984d05bb1.png">

After taking a look at the WP Admin area, this is what it looked like:

<img width="679" alt="screen shot 2016-11-28 at 8 48 31 am" src="https://cloud.githubusercontent.com/assets/10340370/20660020/7914054c-b547-11e6-9841-cd10447d64fb.png">

**Comment by lancewillett** [comment]
This one would need re-testing as a lot of the underlying functionality has changed since end of November 2016. I'm going to close — feel free to re-open if you see it again in another test run or in real life usage.
