### ISSUE TITLE
Unable to try style variations for premium themes

### ISSUE THREAD

**Issue by fditrapani** [Automattic/wp-calypso#96595]
### Quick summary

During onboarding, I was unable to try the style variations on a premium theme. The copy incorrectly tells you that you can try it out and when you press decide later, it does nothing. If I try with a Free theme, then it works.

https://github.com/user-attachments/assets/a94fba85-2950-4904-9576-7acef7133198

See discussion: p9Jlb4-f6u-p2#comment-14380

### Steps to reproduce

1. Create a new site by visiting `/start`
2. Pick a free domain + plan
3. Pick a personal theme
4. Select a Style variation
5. Press Unlock theme
6. Press Decide later

Now try with a Premium theme for the expected behaviour.

### What you expected to happen

The copy says I can try the theme before upgrading so I would expect to be able to try it.

### What actually happened

Nothing

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Upgrade the plan or switch to a Free theme.

**Comment by fditrapani** [comment]
One option here would be to update the copy and call to action for premium themes so that it doesn't imply that you can try the theme. The other one is likely bigger left to allow people to try premium themes along with premium styles.

**Comment by dsas** [comment]
This is due to the global styles gating changes. For themes gated behind the Premium plan we don't mention global styles and don't show the global styles modal - because they're included with the Premium plan. We should do the same for themes gated behind the personal plan.

**Comment by rcrdortiz** [comment]
We have deployed a fix for the issue.

**Comment by fditrapani** [comment]
Thanks for the quick updates!
