### ISSUE TITLE
Copy Site: " You have no items in your cart "

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/wp-calypso#96590]
### Quick summary

When I copy a site and choose a free domain name, the Business isn't added to the cart/checkout page. I see the error message: `You have no items in your cart`.

I tried some workarounds, like connecting a subdomain (of a root domain mapped to WordPress.com). This time, I saw that the Premium plan instead of Business had been added to the checkout page. 

The issue was identified when trying to help a user who requested a migration service but only needed to duplicate one of their sites: https://github.com/Automattic/dotcom-migrations/issues/1623. On the user's account, when trying to use a subdomain like (copied.anvizent.biz) I see the source site changes mysteriously (from anvizent.com to itsupport21fdcc401d0.wordpress.com).

### Steps to reproduce

1. Go to My Sites: https://wordpress.com/sites
2. Find an Atomic site.
3. Click on the three vertical ellipsis and choose the "Copy Site" option.
4. Pick a free domain name.
5. Now, you should see the error: "You have no items in your cart"

You can try connecting subdomains and other workarounds. All seem to fail in different ways.

### What you expected to happen

I expected to have the Business plan added to the checkout page so I could proceed with copying the Atomic site.

### What actually happened

I got the error: "You have no items in your cart".

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

One possible workaround for this would be to export/import the site – manually or using Jetpack.

### Platform (Simple and/or Atomic)

Atomic

**Comment by dsas** [comment]
Verified 👍
