### ISSUE TITLE
Me / Account Settings: Are Fun, Instant Post Feedback, and Jabber Settings Still Needed?

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#966]
Reported by @kriskarkoski: While reviewing /me a few settings felt out of place and I'm wondering if their usage warrants them staying around. Specifically, Fun Mode/Surprise Me and Instant Post Feedback under Account Settings and Jabber under Notifications.

- **Fun Mode was introduced 5 years ago** and I think the last major addition to it was 3 years ago.
- **Instant Post Feedback only works in WP Admin**, so I'm not sure it makes sense to offer this setting in Calypso. I'm also not sure if the Feedback window is getting attention anymore. If we want to keep it maybe it could become a WP Admin-only setting, otherwise I think it makes sense to remove for now and maybe it will be revamped as part of our churn efforts in the future.
- Jabber is not widely used

**Comment by kriskarkoski** [comment]
Jabber is already tucked away in notifications, so removing Surprise Me and Instant Post Feedback will cleanup /me/account nicely 

(sidenote: I know we added the snow setting to Calypso recently. Is that something we hide outside of when snow's available in December?)

**Comment by lancewillett** [comment]
Yes, snow setting is hidden by a date range of Dec 1st to Jan 5th.

**Comment by lancewillett** [comment]
I'm working on WP.com API changes to go along with removing the UI of the Calypso settings — but that doesn't block removing the options now.
