### ISSUE TITLE
User: Main CTA in the invitation signup screen has wrong color

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#96633]
Issue reported during walkthrough: p58i-iKo-p2

When a user receives an invitation to join a site and click on the link, they see this screen whose main button has the old blue. It should be updated to the new WordPress blue.

![Image](https://github.com/user-attachments/assets/0aa0cd12-aafe-4043-af8c-1cc6840a5139)

**Comment by escapemanuele** [comment]
![Image](https://github.com/user-attachments/assets/493fb294-00bc-4f28-8989-5e9dc573b0f7)

Login page has the same blue, should we update that as well?

**Comment by mmtr** [comment]
I think so, but I'll let @matt-west to confirm.

**Comment by matt-west** [comment]
Yep, this blue should be replaced in all interfaces that are not influenced by the user’s theme setting in wp admin.

**Comment by escapemanuele** [comment]
Ok! So should it be `$blueberry-color: #3858e9;`?

**Comment by matt-west** [comment]
@escapemanuele Yep, you should be able to [reference it from color-studio](https://github.com/Automattic/color-studio/blob/9c58a746d8a5f58946e48900e417c7c6e2a84a03/dist/color-variables.scss#L152).

**Comment by escapemanuele** [comment]
Here we go https://github.com/Automattic/wp-calypso/pull/96914 (for the invite page)
