### ISSUE TITLE
Jetpack AI logo generator modal is in the wrong language and has text overflow

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/wp-calypso#96665]
When testing the Jetpack AI logo generator, I did the following:

1. Navigated to My Home and clicked on _Create a logo with Jetpack AI_ in the Quick Links section of My Home. 
2. Waited for the pop-up modal to load. 
3. Was presented with a prompt page in Spanish that also had overflowing text on the left margin. 
4. I closed the modal and clicked on the link again, and was presented with a modal that had less text, but all still in Spanish. 

Note:
* My site's language setting is in English, not Spanish. 
* My WPCOM language settings on the account level is also in English. 
* This is a non-Super Admin test account. 
* This is a site on the WPCOM Business plan with Woo installed. 

Screenshots: 

![Image](https://github.com/user-attachments/assets/79c58902-757e-4775-9774-4d7da1ede902)

![Image](https://github.com/user-attachments/assets/1edb0155-67e4-45ac-af86-e24204bb97da)

**Comment by zaguiini** [comment]
The "text overflow issue" happened because the image failed to load, and you're seeing the image title.

I'm working on getting the user language as the priority for the prompt response.
