### ISSUE TITLE
H3s need some space on top

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9667]
H3s could use some space above them.

For example: https://wpcalypso.wordpress.com/read/feeds/20830339/posts/1239277534

Currently:

![screen shot 2016-11-28 at 9 32 43 am](https://cloud.githubusercontent.com/assets/24388/20678958/a6df09d0-b54d-11e6-9d30-7f171d385b22.png)

cc @jancavan

**Comment by bluefuton** [comment]
Interestingly, we don't apply any top margin on h1-h4 at the moment. I suspect the problem in the above example is that the h3 is preceded by a `<div>` (which has no bottom margin) rather of a `<p>` (which does). I'll whip up a test post.

**Comment by fraying** [comment]
Oh interesting! If it's just a one-off, we can ignore.
