### ISSUE TITLE
Can't add widgets in customizer or widgets.php when Post Editor is Set to Write Mode

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#96694]
### Quick summary

After you publish a post in the block editor using Write mode you cannot add, edit, or remove widgets via /widgets.php or Customizer > Widgets in older non-FSE block themes. 

### Steps to reproduce

1. Install and activate Twenty Twenty-One
2. Go to posts > Add New post 
3. In the Post Editor click the arrow looking icon (top left by the + the tool tip is "tools" [see the video is that makes no sense]) and choose Write 
4. Type anything into the paste and publish
5. Navigate to Appearance > Widgets and try to add a widget or edit existing ones.

### What you expected to happen

I expect my widgets to work normally. 

### What actually happened

I can't edit anything. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Open any post, change it to Design mode, then publish. 

### Logs or notes

- The issue is not reproducible in Gutenberg's latest version (19.7.0), only 19.6.4 which Simple and Atomic are currently running. 
- The issue is not applicable to new FSE themes, only older themes with a Customizer > Widgets and /widgets.php
- Reproduced in various themes with widget areas Penscratch 2, Carnard, Astra, etc. 
- user reported in 9077778-zd-a8c 

https://github.com/user-attachments/assets/9d2cc15a-5dc7-420f-858c-d92f00d2c04c

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Closing as not planned. This is already solved in Gutenberg 19.7 as the write mode is not visible anymore (it will land as an experiment in 19.8). 19.7 will be available on Simple & Atomic soon.
- Context: p1732564644333499/1732392927.871849-slack-C03TY6J1A
