### ISSUE TITLE
Prototype Dogfoodable  Goals + Design Picker moved ahead of User Account screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96708]
Using phrasing from a call with @ianstewart  and @p-jackson, we will move the Goals screen and the Design picker to the front of the signup flow to be testable. We won't be focusing on polished visual design,.  This will be a dogfoodable flow we can play with while final product and visual design decisions are being made.

Now that we have confirmation that we are moving forward with the stepper framework, p1732484779832799/1732293653.862559-slack-C07H21B2W5, 9 this dev work can begin. 

This issue  covers work to get the feature flag set up and move the screens so that the work is testable internally. This issue does not cover shipping to customers. 

This issue can be closed when have a testable internal version:
- [ ] Work is behind a feature flag
- [ ] Goal screen and Design Picker moved ahead of account screen
- [ ] Goal selection persisted 
- [ ] Existing Launchpads work as expected (tailored for write flow)

**Comment by p-jackson** [comment]
This prototype is now available when going to `/setup/onboarding` when you're proxied.
