### ISSUE TITLE
Adding a Paypal Payment method doesn't respond

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/wp-calypso#96702]
### Quick summary

When going to Upgrades ⇢ Purchases, choosing a purchase and adding a payment method, if I choose Paypal and enter my postal code and then click the Paypal button, nothing is happening.  A customer reported this and I can confirm this on my account as well.  I see that if I go to the /me dashboard and click on Payments and Add Payment Method there, the Paypal option doesn't come up at all, so I'm wondering if it was removed there but not moved from Upgrades ⇢ Purchases.

### Steps to reproduce

1. Go from WordPress.com Dashboard on a site with active upgrades to Upgrades ⇢ Purchases
2. Choose an upgrade
3. Choose "Add Payment Method.
4. Choose Paypal, then enter a postal code
5. Click on Paypal button.

### What you expected to happen

Paypal popup should come up 

### What actually happened

Nothing comes up.  Error in console:

Uncaught (in promise) Error: No payment processor found with key: paypal-express
    at 35647.7502f0b4be3de881d356.min.js:1:13754
    at k (78027.88f439c8ebc36402507f.min.js:12:6362)
    at onClick (31323.ead7fc19a9f42794cee1.min.js:30:35548)
    at Object.eU (37055.e202c13cb6a95f354f1e.min.js:14:14949)
    at eW (37055.e202c13cb6a95f354f1e.min.js:14:15103)
    at 37055.e202c13cb6a95f354f1e.min.js:14:33409
    at n7 (37055.e202c13cb6a95f354f1e.min.js:14:33508)
    at re (37055.e202c13cb6a95f354f1e.min.js:14:33922)
    at 37055.e202c13cb6a95f354f1e.min.js:14:39378
    at aC (37055.e202c13cb6a95f354f1e.min.js:14:96290)

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by paxblueribbon** [comment]
Told customer we'd let them know when there's more information on this, ticket is zd9081589

**Comment by sirbrillig** [comment]
I believe this was fixed by https://github.com/Automattic/wp-calypso/pull/96703

**Comment by sirbrillig** [comment]
https://github.com/Automattic/wp-calypso/pull/96737 should notify the user and the developers if this happens again.
