### ISSUE TITLE
Marketing Connections: Frediverse Connection Status Not Updating After ActivityPub Plugin Installation

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/wp-calypso#96700]
### Quick summary

After installing the ActivityPub plugin via My Site > Hosting > Marketing > Frediverse, the plugin works as expected, but Calypso's Marketing Connection still indicates that Frediverse is inactive and continues to prompt the user to install the ActivityPub plugin. 

### Steps to reproduce

1. Start with any Atomic site that has a [custom domain set as primary](https://wordpress.com/support/domains/set-a-primary-address/). 
2. Navigate to My Site > Hosting or Tools (depends on your default dashboard) > Marketing > Connections > Frediverse (https://wordpress.com/marketing/tools/{yourdomain} )
3. Click the "Install ActivityPub" button.
4. On the ActivityPub plugin page click "Install and Activate" 
5. From the plugins page, navigate back to My Site > Hosting or Tools (depends on your default dashboard) > Marketing > Connections > Frediverse. 

### What you expected to happen

Since I started the connection process to Frediverse through the Calypso flow, I expect that after completing step 4, I would be taken back to the Marketing Connections page rather than being redirected to the Installed Plugins section, or just never leave the Connections page? 

I expect to see some configuration options for managing my Frediverse settings, similar to what is demonstrated in the support guide’s video at the 0:18 mark:
![Image](https://github.com/user-attachments/assets/a11f8bf0-4971-4ac0-810d-46d21e1e15d3)

### What actually happened

After completing step 4, I am redirected to the Installed Plugins page instead of being taken back to Marketing Connections. 

When I manually navigate back to Marketing Connections and click the dropdown on Frediverse, I am incorrectly prompted to install the ActivityPub plugin again, even though it is already installed and functioning.

![Image](https://github.com/user-attachments/assets/297845c2-fb8c-4740-b663-0a2511f9cb90)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The ActivityPub plugin works regardless of the Calypso Marketing Connections settings.

You just have to go to Tools > ActivityPub > Settings and change to "Both author and blog profiles" and save. With that set up, when I copy my Username or Profile URL from Tools > Activity Pub and search for them on https://mastodon.social/ my profile information is pulled in and newly published posts too:   

![Image](https://github.com/user-attachments/assets/fbf4f84f-31ba-4fc7-a1fa-f43000cb9451)

### Platform (Simple and/or Atomic)

Atomic 

### Logs or notes

- user reported: 9080553-zd-a8c

**Comment by jartes** [comment]
@ash1eygrace Thanks for reporting this one, Ashley! 

📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged

@Automattic/fediverse 👋🏻 Can you take a look at this broken experience as soon as possible? We are now prioritizing these reports. See pc4f5j-4Yq-p2. Thank you!
