### ISSUE TITLE
Bug: date range picker doesn't respect start/end params in URL

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#96714]
Looks good and work well 👍 

I do observated an issue where the date range picker doesn't respect the date range in URL, and would override it with its range when open -> close:

https://github.com/user-attachments/assets/015869c9-0a15-45db-86c6-603d54f8ca0e

I don't think it's related to the PR, so let's ship it :shipit:

_Originally posted by @kangzj in https://github.com/Automattic/wp-calypso/pull/96663#pullrequestreview-2456787924_

**Comment by a8ck3n** [comment]
Done!
