### ISSUE TITLE
Reader Refresh: Line clamp for cross-browser compatibility

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9672]
From a conversation that was sparked from this [comment](https://github.com/Automattic/wp-calypso/pull/9497#discussion_r89416349), the reader is using the css property `-webkit-line-clamp` which only works for webkit browsers.  Specifically we use this for post-excerpts that we want to restrict to 3 lines in cards.\
Here is an example of it broken in Firefox (non-webkit):
![FF broken](https://cldup.com/neLU5llkxo.png)

This issue can be closed when we've made a cross-browser compatible line clamping solution.
Implementation idea: [mixin from codepen](https://codepen.io/tymondesigns/pen/LKjwG)

**Comment by blowery** [comment]
We generally just use the `long-content-fade` sass function instead of line clamping.

**Comment by samouri** [comment]
We currently use line-clamp in both:
1. client/blocks/reader-related-card-v2/style.scs
2. client/components/post-excerpt/style.scss

This issue can be closed when they have been changed to `long-content-fade`.  
Turns out this is currently affecting Firefox

**Comment by samouri** [comment]
Closing because this will be fixed in: #9962
