### ISSUE TITLE
StepperTracking: Difference in tracking returning from Use My Domain

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96730]
In Stepper a `calypso_signup_step_start { step: domains} ` event is triggered when coming back from Use My Domain to Domains.
In Start that doesn't happen.

What's the best way to handle this?

**Comment by chriskmnds** [comment]
My advise would be to Keep logging it as done already if it's a redirection. This is the same as signup start event. A redirection should log the "start" or "restart" of the step. I'd really hate going back to those discussions again if that's the case (redirection)

**Comment by escapemanuele** [comment]
No, in Stepper's case it is not a redirection, 'use-my-domain' is part of the onboarding flow and moving through the steps should happen without any redirection

**Comment by chriskmnds** [comment]
> No, in Stepper's case it is not a redirection, 'use-my-domain' is part of the onboarding flow and moving through the steps should happen without any redirection

I'll need to take a closer look, but just from testing - it looks like we go from step `/setup/onboarding/domains` to  `/setup/onboarding/use-my-domain`. If for whatever reason we come back to `/setup/onboarding/domains` then I'd expect that to be logged as normal (it's a "redirection back to domains" - probably not using the term technically correct).

**Comment by escapemanuele** [comment]
Ah sorry, I thought you meant some "jumping". 

>  I'd expect that to be logged as normal

Yes, I also think that Stepper does it correctly. Here I state that the difference exists, so we may also want to add this to Start as well.
Or just ACK this if it doesn't cause the big discrepancies and we're moving to Stepper.

**Comment by escapemanuele** [comment]
Closing as fixed
