### ISSUE TITLE
Decision: Should the logged-out "skip to dashboard" take users to the Hosting flow?

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#96759]
The "skip to dashboard" button on the current Goals step can easily go straight to a dashboard because the site is already created and the user is logged-in. 

In the North Star flow the "skip to dashboard" button actually takes the user to the Hosting flow. Because there needs to be account creation and plan selection.

In our "dogfoodable flow", do we want to implement the North Star behaviour? Or is the dogfoodable flow just about implementing the minimum possible, so we could keep them on a streamlined version of the regular flow?

**Comment by autumnfjeld** [comment]
IMO the dogfooding flow, from our dev POV, should just be about setting up the flow.  This decision would be something different.   Having said that however, this is exactly the kind of detail that I assume is going to come up during dogfooding, along with many others.

But to me, this decision is done for now and there are other tasks already dedicated to the "Skip to dashboard" action: [Skip to WordPress Admin #95840](https://github.com/Automattic/wp-calypso/issues/95840)

**Comment by p-jackson** [comment]
https://github.com/Automattic/wp-calypso/issues/95840 is a better issue, tracking there.

**Comment by p-jackson** [comment]
> EDIT: I was misthinking. This decision is needed!

**Comment by autumnfjeld** [comment]
I'll close this in favor of  https://github.com/Automattic/wp-calypso/issues/97469, which explains the options we have for "Skip to Dashboard" for the EOY milestone as detailed in the PT https://quakep2.wordpress.com/2024/12/11/pt-onboarding-move-goals-design-picker/

No doubt the behavior of this link will be discussed many more times.  For the EOY milestone, as of the time of writing this, we are hiding the link and will bring it back in a January iteration.
