### ISSUE TITLE
Persist Goal selection from pre-account Goals screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96755]
Goals will be pre-account creation and thus must be persisted through the flow and then saved when the user has an account.

## Prior work
This is for information only, to review what has been done before
 
**Trail Map**
Work in Trail Map project is relevant to moving the goals screen: pdDR7T-1xi-p2
From @wongasy (We won't have a survey but the mechanics could be the same for recording goals.)

We can define survey questions and answers: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Suggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sfrtzragngvba%2Qfheirlf%2S-og
And use this component for rendering the survey: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Suggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Spnylcfb%2Spyvrag%2Spbzcbaragf%2Sfrtzragngvba%2Qfheirl%2Svaqrk.gfk%3Se%3Q50o9pnsr%2361-og (or create another component if the UI looks different, but the hook should still be reusable)

**Goals stored in site option**
And Phil's investigation here: pfYzsZ-w2-p2

**Comment by autumnfjeld** [comment]
## Prior work
Work in Trail Map project is relevant to moving the goals screen: pdDR7T-1xi-p2
From @wongasy (We won't have a survey but the mechanics could be the same for recording goals.)

We can define survey questions and answers: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sfrtzragngvba%2Qfheirlf%2S-og
And use this component for rendering the survey: uggcf%3N%2S%2Suers.yv%2S%3Suggcf%3N%2S%2Sbcratebx.n8p.pbz%2Sfbhepr%2Skers%2Spnylcfb%2Spyvrag%2Spbzcbaragf%2Sfrtzragngvba%2Qfheirl%2Svaqrk.gfk%3Se%3Q50o9pnsr%2361-og (or create another component if the UI looks different, but the hook should still be reusable)

**Comment by wongasy** [comment]
Also noting that the survey was built in a way that answers supplied _prior_ to account creation can be mapped to the newly created user account. You can reference the implementation for the E-commerce flow (https://wordpress.com/ecommerce), where users fill out a survey before account creation.

**Comment by vykes-mac** [comment]
This is me documenting the process similar to `/ecommerce` flow.

1. On the backend create a segmentation survey with the goal screen questions and answers. See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Sfrtzragngvba%2Qfheirlf%2Spynff%2Qjcpbz%2Qfrtzragngvba%2Qfheirl.cuc%3Se%3Q288np368%26sv%3Qfnir_fheirl_nafjref%23fnir_fheirl_nafjref-og
2. On the frontend fetch survey using the survey key created on the BE similar to what is done in [calypso](client/landing/stepper/declarative-flow/internals/steps-repository/segmentation-survey/index.tsx) to show ecommerce segmentation survey step. This uses the existing `SegmentationSurvey` component to fetch questions and answers from the backend. In this case we fetch the goal screen questions and answers and renders it.
3. The answers are submitted to the backend using endpoint `/segmentation-survey/answers` All this is already handled by the hooks in the `SegmentationSurvey` component. An anonymous id is created that's later used to link survey to user.
4. After account/site is created use the `useLinkAnswersMutation` hook to link the newly created user to the survey.

**Comment by p-jackson** [comment]
@vykes-mac I'm confused by the steps you documented above. Afaict we don't need to do anything with surveys. I think the "Prior work" described above might be throwing you off, because I think the work we're doing is quite different from that work.

The prior work that I think is more relevant is the `/setup/newsletter` flow. It doesn't have a step where the user selects goals, however it does persist the goals selection during site creation.

The `/sites/new` endpoint accepts a `site_goals` option, which can be used to set the site option during site creation.
fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qarj%2Qfvgr%2Qraqcbvag.cuc%3Se%3Qo5471o97%23350-og

Currently the `site-setup` flow is what updates the `site_goals` option on the existing site. However we should now persist it during the `onboarding` flow. Which means we can do it during the call to `/sites/new`.

**Comment by vykes-mac** [comment]
@p-jackson what you are describing seem different from what the task is asking. It seems your saying we should only save the goals as site options when the site is being created? 

But the task mentioned before account is created. Maybe we need to sync to get clarity.

**Comment by vykes-mac** [comment]
@autumnfjeld There was some confusion it seem with this task. The task is asking to persist the goals before account is created similar to the "Prior" work described. However after syncing with @p-jackson It seem we do not need to do that but rather just store the goals in the sites endpoint when the site is created. Goals are already stored locally in the onboarding data store and is accessible at all steps in the onboarding flow. I'm not sure if there is some other reason why this task wants it stored before account is created?

**Comment by autumnfjeld** [comment]
The prior work was only meant to be a possible path, not an absolute instruction to do so.    I should have also added what Phil summarized here as "prior work" here pfYzsZ-w2-p2, meaning both are possible paths forward.

I haven't seen any mention of data folks wanting to track pre-account goals, so using local storage is fine. 

>  after syncing with @p-jackson It seem we do not need to do that but rather just store the goals in the sites endpoint when the site is created. Goals are already stored locally in the onboarding data store and is accessible at all steps in the onboarding flow. 

Let's go with this.   

Thanks for looking at all the options.

**Comment by autumnfjeld** [comment]
I updated the issue description to reflect our discussion
![Image](https://github.com/user-attachments/assets/fa3abfd2-60cc-42c9-ba0f-5109a06838fc)
