### ISSUE TITLE
Reader FullPost: Video embeds in comments display issues

### ISSUE THREAD

**Issue by aaronyan** [Automattic/wp-calypso#9677]
The embedded videos in a FullPost comment have some alignment issues. The username on the comment is blank (maybe set to "Anonymous") and the video should be left aligned.

https://calypso.live/read/blogs/58006636/posts/28217

<img width="1439" alt="reader_refresh_fullpost_comments_video_embeds" src="https://cloud.githubusercontent.com/assets/4505888/20688101/34b99dd0-b574-11e6-8c20-5121e69dca0d.png">

**Comment by blowery** [comment]
@aaronyan can you check this one again? It looks OK to me...

<img width="794" alt="that s_not_how_this_works__ _the_bloggess_ _reader_ _wordpress_com" src="https://cloud.githubusercontent.com/assets/14350/20937381/b2a59848-bbb4-11e6-9da5-e455fa5efa2f.png">

**Comment by aaronyan** [comment]
Yep, I don't seem to have the problem anymore. Thanks @blowery!
