### ISSUE TITLE
Feature Request: Use consistent colors for Log Type switcher in Logs tab

### ISSUE THREAD

**Issue by wojtekn** [Automattic/wp-calypso#96788]
### What

The Log Type switcher (PHP error/ Web server) should be refreshed to be more consistent with the rest of the UI, e.g., should use blue like the switcher in the Performance tab.

![Image](https://github.com/user-attachments/assets/1ceec2c0-684c-4040-9480-690031a95d5c)

### Why

To keep UI consistent across the pages.

**Comment by Robertght** [comment]
@wojtekn I think we have this in here as well https://github.com/Automattic/dotcom-forge/issues/9527

I'm going to close it in favor of that one, but let me know if I misunderstood it.

**Comment by wojtekn** [comment]
@Robertght you're correct, it seems I've added issue that duplicates the other one.
