### ISSUE TITLE
Reader: clicking New Posts indicator loses current reading position

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#968]
Raised by @lancewillett 

(Anecdotal scenario that I wanted to track this after a conversation with @samuelsidler)

Screencast: 
![reader-position](https://cloud.githubusercontent.com/assets/66797/8262252/d3e85c82-1685-11e5-9af6-7ea2cbba3369.gif)

You leave Reader open in a tab, come back the next day. You see a "X New Posts" with an arrow, in orange, indicating you have new posts. 

You expect to just start scrolling up and reading them in order (oldest first). Instead of reading from right above the last position, however, you can’t because clicking that message takes you to the very top of the Reader stream. With no indication of where that last place was where you'd read the first of the new posts.

Suggested improvement: allow scrolling up directly without jumping to the very top of the screen.

Possibly related to 6750-gh-calypso-pre-oss.

Note from @samuelsidler 

> That improvement works, but I think it would be fine to require the user to click on the "X New Posts" link and have it load the posts. It should just load them above the current view and allow you to scroll up from there to see your new posts. One example of this that I like is Tweetbot on iOS, which shows you how many messages remain "above" the current message. (See screenshot below.)
> 
> <img src="https://cloud.githubusercontent.com/assets/4642604/8264669/3c326a18-16b7-11e5-8171-3a9790488897.PNG" alt="img_3006" width="400" />

Note from @csonnek

> Adding a +1000 onto this request. I'll start the day with 40+ unreads and I'd love to have the posts load above rather than have it jump all the way back up to the top. Reading oldest -> newest is important for my use of the Reader.

**Comment by alisterscott** [comment]
This is still an issue, so this enhancement is still applicable.

@blowery: is there any project work addressing this at present or planned?

**Comment by blowery** [comment]
@alisterscott yup, we have an upcoming project (High Water Mark) that should help address this.
