### ISSUE TITLE
Incorrect metrics on Ads Stats tabs

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#96817]
### Quick summary

The metrics shown in the Ads stats tabs are incorrect. Unlike the tabs in Traffic tabs which show the data of the selected date in the graph, the tabs in the Ads stats show the total of all days in the graph and don't update for date selections. 

Screenshot: ![Image](https://github.com/user-attachments/assets/75c1768e-3a02-4543-a1fc-765ccd6749e3)

While I do not have a test site with active WordAds to verify, there are multiple chats from confused users about the same. 

### Steps to reproduce

1. On a site with active WordAds, go to Stats > Ads.
2. Select the bars on the graph and observe that the stats on the tabs are not updated

### What you expected to happen

Selecting bars on the graph should update the stats on the tabs with data of the selected date as seen in Traffic stats: https://github.com/user-attachments/assets/80b5c832-e7cc-4524-9454-583657fb0cb4

### What actually happened

Selecting bars on the graph for Ads did not update the stats on the tabs with data from the selected date. Screen recording: https://github.com/user-attachments/assets/b89c2f0f-9cd5-4a11-a1f9-2991094a54a0

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

User reports: 9086087-zen

9091151-zen

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- Lowered priority from `Blocker` to `Normal`.

@Automattic/jetpack 👋🏻 Can someone take a look at this report at the earliest opportunity? We are prioritizing this reports now: pc4f5j-4Yq-p2 Thank you!

**Comment by dognose24** [comment]
@jartes Thanks for the report. I have [proposed a fix](https://github.com/Automattic/wp-calypso/pull/96839), and it will be shipped soon.

**Comment by dognose24** [comment]
[The change](https://github.com/Automattic/wp-calypso/pull/96839) has been deployed, so the issue should be fixed now. cc @devNigel @jartes @ouikhuan @kangzj

**Comment by jartes** [comment]
This is fantastic. Thank you so much for fixing this so quickly!
