### ISSUE TITLE
Create contact information edit page

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#96818]
`Will be unblocked when https://github.com/Automattic/wp-calypso/issues/96673 is done`

Create a page for editing the contact information of a domain.

It'll be this component `http://calypso.localhost:3000/domains/manage/<domain-name>/edit-contact-info/<site-slug>` or Go to Upgrades -> Domains -> Click a Domain -> click the Edit button in the Contact Information section

Tasks:

1. Show the Edit contact information page within the new middleware
2. Register a path for showing it for a specific domain

![Image](https://github.com/user-attachments/assets/0b2c3857-5fc3-41a7-aea3-64204ab82ebf)

ePfz53j71KKDLWtuSm567A-fi-4949_49077

**Comment by m1r0** [comment]
Because this is a sub-page, probably it makes sense to use the `SubPageWrapper` component that Paulo is [currently working on](https://github.com/Automattic/wp-calypso/pull/97368). I'm planning to use his branch as a base.
