### ISSUE TITLE
Show Emails page tab when users have Google mailboxes

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#96823]
`Will be unblocked when https://github.com/Automattic/wp-calypso/issues/96673 is done`

When the user creates or has google mailboxes we should show them the Google mailboxes in the Emails tab.

It has the following states -

**Configuring**
![Image](https://github.com/user-attachments/assets/65050741-a4a7-41da-8262-994a3c275822)

**Finish Setup**
![Image](https://github.com/user-attachments/assets/c75011fa-48ee-4a08-ba4b-2be3f4631e28)

**After Mailboxes Setup completed**
![Image](https://github.com/user-attachments/assets/ad922d37-276c-4787-8b8c-61e3822e59d7)

Tasks:

1. Show the Google mailboxes page under Emails tab when the user has google mailboxes
2. Match the styles for each state

**Comment by phcp** [comment]
I moved it back to **To Do** due to the overlap with https://github.com/Automattic/wp-calypso/issues/96820, which is in progress and should ideally follow a similar approach.
