### ISSUE TITLE
Load the breadcrumb component on top of the sub-pages

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#96832]
The breadcrumb component is already there and is shown in different Calypso pages in admin panel. For example, Upgrades -> Domains, Upgrades -> Emails etc inner pages.

Every sub-page will show a breadcrumb component on top.

![Image](https://github.com/user-attachments/assets/486b9988-a1a7-4c98-97ed-5d20669b5887)

Tasks

1. Load the breadcrumb on top
2. The area below should load any component passed by the context

**Comment by Imran92** [comment]
@m1r0 I'm updating the Title to not mention _middleware_ specifically. Feel free to just reuse the current breadcrumb component, or creating a middleware or any other way that seems most suitable.

**Comment by m1r0** [comment]
Sounds good, thanks!

**Comment by m1r0** [comment]
It looks like we could reuse the `DomainHeader`/`NavigationHeader` component.

Do we have a sub-page ready where I can add the breadcrumbs?
