### ISSUE TITLE
Bulk Plugin Management: Allow bulk upgrades

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#96834]
It should be possible to bulk upgrade plugins from the table view:

![Image](https://github.com/user-attachments/assets/4fa74a67-59df-48c6-be17-46e2bff0027f)

**Comment by paulopmt1** [comment]
We're planning to replace bulk actions [for this new interface navigation](https://a8c.slack.com/archives/C083VAJH7HD/p1733839043964349), so I'll go ahead and close this.
