### ISSUE TITLE
Enhancement: Improvements to WordPress.com/sites dashboard

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/wp-calypso#96836]
<br>

When a user accesses https://wordpress.com/sites and has one website only, if they click on themes, they are immediately taken to their only website's theme list. 

This is somewhat confusing and different from what happens under Domains or Sites.

It would also be nice if the behaviour was consistent when jumping from Sites, to Domains, Plugins, and Themes. At the moment, this is only consistent on Sites and Domains.

<br>

**Source Information:**

- Title: Sites — WordPress.com
- URL: https://wordpress.com/sites

**Comment by Robertght** [comment]
Thank you @filipanoscampos!

This was actually a bug and was fixed here: https://github.com/Automattic/wp-calypso/issues/96619
