### ISSUE TITLE
Atomic sites are not listed when registering a domain on an existing site

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/wp-calypso#96844]
### Quick summary

If you add/register a new domain from the Domains Management page (`wordpress.com/domains/manage`), you have an option to register it on an existing site on your account. Selecting this option shows only Simple sites.

This does not impact registering domains from an Atomic site's Calypso dashboard (Upgrades/Hosting > Domains).

### Steps to reproduce

1. Start at https://wordpress.com/domains/manage/
2. Click **Add new domain**
3. Select a domain to register, and click Continue
4. Select the **Existing WordPress.com site** option

### What you expected to happen

All WordPress.com sites on your account should be listed.

### What actually happened

Only Simple sites are listed. Atomic sites are missing from the list entirely.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Domains can still be registered on Atomic sites from the site's dashboard (at _Upgrades/Hosting > Domains_).

### Platform (Simple and/or Atomic)

Atomic

**Comment by vykes-mac** [comment]
@jp-imagines Could you attach a video recording of the issue?

Are you referring to this option to add domain to an existing site?

https://github.com/user-attachments/assets/04d98396-ee07-4725-afb2-b7d3ab1f2e82

**Comment by jp-imagines** [comment]
@vykes-mac My apologies – I was a bit rushed when I wrote this and I missed a step. Updated the steps in the issue report above.

Here's a video as well. This isn't about taking an existing domain and attaching it to an Atomic site, but rather registering a brand new domain on a site directly:

https://github.com/user-attachments/assets/c261d597-9f98-444f-bd67-3b9f9b7b72c3
