### ISSUE TITLE
Domains page lose styling when navigating using `All Domains` breadcrumb

### ISSUE THREAD

**Issue by vykes-mac** [Automattic/wp-calypso#96855]
The domains page styling is thrown off when navigating using the `All Domains` breadcrumb. It only happens from the `attach site page`

Steps to reproduce:

1. Go to the domains page
2. Use the ellipses menu and select `attach to an existing site`
3. Click the `All Domains` breadcrumb
4. See the page is not broken

![Image](https://github.com/user-attachments/assets/9c943c91-4948-480d-8e49-9afc636fbfcf)

**Comment by Robertght** [comment]
I'm going to mark this as Triaged on the One Board, as I can see we have someone assigned to it.

@vykes-mac feel free to do the same in the future with new issues. Thanks!
