### ISSUE TITLE
Design Picker: Selecting a Partner theme and removing the theme in the checkout screen results in a failed atomic transfer

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#96864]
### Quick summary

When users select a Partner theme in the onboarding design picker and decide to remove it from the checkout cart, the following step of the onboarding fails. See recording for reference.

https://github.com/user-attachments/assets/227f3433-887a-403c-bc20-f8adc1ae46a4

### Steps to reproduce

1. Head to the onboarding design picker.
2. Select any Partner theme.
3. Continue the flow until arriving at the checkout screen.
4. Remove the Partner theme from the cart.
5. Purchase the Business plan.
6. You'll be taken to the Atomic transfer processing screen, but it will get stuck in step 1 due to API error.

### What you expected to happen

The Atomic transfer to be successful, and the default theme installed.

### What actually happened

The Atomic transfer failed.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested the onboarding flow on the platform
- 
📌 FINDINGS/SCREENSHOTS/VIDEO

This is what I'm seeing as well:

![arqXIVjw6UfXXI8P2o7do0nTP9hNgVWrwgl1S2Z8.jpg](https://github.com/user-attachments/assets/4a5709a2-8346-4f25-a717-4062259ab575)

📌 ACTIONS
- Triaged
- Raising priority as it's a blocker for potential paid customers.

**Comment by BogdanUngureanu** [comment]
Deployed a fix with the take 2 PR.
