### ISSUE TITLE
Stepper: Browser back from Checkout to Plans does not reach Domains

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96888]
When you go back from Checkout using the browser back button, you land in Plans.
It is impossible to return to domains.

That doesn't happen in Start.

It's probably because of the logic introduced to go to Plans when back from Domains, before when going back from Checkout you'd land on domains.

**Comment by alshakero** [comment]
I landed in Domains

https://github.com/user-attachments/assets/17e60de5-77f3-49d0-b387-afbb592c1d43
