### ISSUE TITLE
Goals step moved and fully functioning for MVP release

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96905]
### Details

- [x] logged-out DIFM flow
- [x] logged-out Import flow
- [x] logged-out Skip to Dashboard flow
- [x] Goals persisted
- [x] Tracks events verified

### Checklist

- [ ]
- [ ]

**Comment by lsl** [comment]
Closing this as I think the things we want covered for 20dec are covered.

I'm addressing the unit test issue: https://github.com/Automattic/wp-calypso/issues/96599 with: https://github.com/Automattic/wp-calypso/pull/97541

And I've listed the remaining issues on the follow up issue https://github.com/Automattic/wp-calypso/issues/97430

We may still need to handle big sky see this question: p1734408462559429-slack-C085HCWCEDN
