### ISSUE TITLE
Design Picker step moved and fully functioning for MVP release

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#96906]
### Details

Design Picker is moved, meets feature specs, and is ready to ship to customer.

### Checklist

- [ ]
- [ ]

**Comment by autumnfjeld** [comment]
@fditrapani  You have these shown as "other plans pages" 4z6QzOQmmO7mhQAtQHQJR7-fi-9041_21001 but it isn't clear in what scenarios each of these three will show.

I'm guessing it is something like this:
* If user chooses only free features, show the plans grid with all plans
* If user chooses a feature that requires the Personal plan (like custom colors & fonts, Global Styles) then show the plans grid with Personal as the minimum plan
* If user chooses a premium theme, show the plans grid with Premium as the minimum theme
* If user chooses a feature that requires business plan (like a partner theme), show the plans grid with Business as the minimum plan


Are these specs correct?

![Image](https://github.com/user-attachments/assets/9a7b23c7-38fb-4581-9307-b9b85af4bf08)

**Comment by fditrapani** [comment]
That is correct!

> If user chooses a feature that requires the Personal plan (like custom colors & fonts, Global Styles) then show the plans grid with Personal as the minimum plan

From what I understand, there are some premium themes available on the Personal plan too
![Image](https://github.com/user-attachments/assets/d34e62fa-1185-483d-9ac3-970d7e56f3c6)

**Comment by arthur791004** [comment]
Closing it as all tasks have been completed.
