### ISSUE TITLE
In-Stream Recs busted at narrow width

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9690]
I'm sure this is a known issue (hi @jancavan!) but I wanted to post an issue just to track it.

In-Stream Recs are busted at narrow width.

![screen shot 2016-11-29 at 9 23 03 am](https://cloud.githubusercontent.com/assets/24388/20720867/b36c79b2-b615-11e6-989e-6705db9c3676.png)

**Comment by jancavan** [comment]
Yup, this is a know issue. Still trying to fix it.
