### ISSUE TITLE
Stepper: Fix accessibility issues

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#96926]
I ran a Lighthouse test on /setup/onboarding and saw that there is room for improvement.

![Image](https://github.com/user-attachments/assets/3bbb6ec6-6bd5-4a90-88cb-c10c6c236bfc)

Comparing it with Start, I saw that Stepper has a lower accessibility score. We should fix this.

**Comment by MicBosi** [comment]
I also ran a few tests 4X for `/start/user-setup` and 4X for `/setup/onboarding/user` and one thing that captured my attention was the `Largest Contentful Paint` figure. 

For Start I have: 10s, 10.2s, 10.4s, 9.6s
For Stepper I have: 17.9s, 16.1s, 13.1s, 13.1s

Granted these numbers are a bit volatile but they match another manual test I had done refreshing Stepper and Start in Chrome, using 3G and 4G Slow Network Throttling (to accentuate the differences) and tracking how many seconds it takes for the various social options to appear on the. page:

3G/Start: ~27s (~3.2MB downloaded)
3G/Stepper: 36s (~4.5MB downloaded)

I would say these are just preliminary figures but it might be worth looking into some of these key performance metrics to make sure Stepper is as optimised as Start before the next A/B test.

**Comment by escapemanuele** [comment]
Thanks @MicBosi, I opened this issue https://github.com/Automattic/wp-calypso/issues/97337

**Comment by alshakero** [comment]
PR https://github.com/Automattic/wp-calypso/pull/97371
