### ISSUE TITLE
Domain Management: Enable Inter-Registrant Transfer

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#9694]
This an umbrella issue for enabling transfer of domains to different users on the same site.

**Comment by klimeryk** [comment]
@umurkontaci This one was fixed by https://github.com/Automattic/wp-calypso/pull/9863, right? Or is there something else you want to add under this issue?

**Comment by umurkontaci** [comment]
Yes it was fixed by #9863, I forgot to close this. Thanks for noticing 👍
