### ISSUE TITLE
Showcase: Fonts and style variations thumbnails not appearing correctly.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/wp-calypso#96977]
### Quick summary

On [the theme showcase page for Streamer](https://wordpress.com/theme/streamer), some fonts and the style variation thumbnails don't appear as they should.

The fonts used in the two variations, Persimmon and Plunge, don't appear on the iframe preview on the right. But the fonts appear correctly if you click to see the demo site.

Persimmon (what you see on the left is the demo site with the variation.)
![Image](https://github.com/user-attachments/assets/8fc1e7ed-06f0-4b73-a1ec-e4d2bc45e079)

Plunge (what you see on the left is the demo site with the variation.)
![Image](https://github.com/user-attachments/assets/9318f3ad-6514-475f-a75a-c1b2fe5505d4)

The style variation items/thumbnails appear very differently.
![Image](https://github.com/user-attachments/assets/049036a7-f768-484d-b519-0cd0700153f5)

I haven't seen this issue in other themes, there might be something wrong in the theme. My apologies and kindly let us know if that's the case. Thanks in advance!

### Steps to reproduce

You can see[ the showcase page](https://wordpress.com/theme/streamer) and try to see the two style variations.

### What you expected to happen

They should appear as intended.

### What actually happened

They look different as you see in the screenshot above.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by iamtakashi** [comment]
This is happening with Psychedeli, too https://wordpress.com/theme/psychedeli

**Comment by arthur791004** [comment]
Proposed 169322-ghe-Automattic/wpcom to resolve this issue.

**Comment by arthur791004** [comment]
Closing it as it'completed.
