### ISSUE TITLE
Follow Management: Possible to (temporarily) get duplicate entries in the list

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#97]
I could follow “danroundhill.com”, tap the unfollow button, then follow “www.danroundhill.com”. Resulted in two entries in the list, one followed one not.
<img width="678" alt="screen shot 2015-11-18 at 9 31 28 am" src="https://cloud.githubusercontent.com/assets/1435271/11246120/df34aba4-8ddb-11e5-9a91-5fc936fd968b.png">

**Comment by blowery** [comment]
Refs #749

**Comment by bluefuton** [comment]
This is no longer an issue in the revamped Following Manage 🎉
