### ISSUE TITLE
Reader: single view is sparse and lacking description in the index view

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#970]
Raised by @kwight 

I'm not really sure what info is intended for the single view in the Reader, but the single view seems lacking for this post, compared to what led me to it in the Reader's index view. A few things that jump out:

* Are styles missing from both the masterbar and the video player?
* No even sure if that's supposed to be a functional player
* Only the title is clickable
* The URL on hover in the index view showed the direct link (with the wordpress.tv domain), but I got the single view; a little confusing
* The index view had a description that is trailed off, but the single view has no description at all

Related: #747 

Index view:

![index](https://cloud.githubusercontent.com/assets/349751/8607255/9cd6738e-2646-11e5-88d0-f5a4df5ee03d.png)
<sup>Seen at https://wordpress.com/read/post/feed/34277</sup>

Single view:

![single](https://cloud.githubusercontent.com/assets/349751/8607264/ac28b716-2646-11e5-87b9-a8657d7b043f.png)
<sup>Seen at https://wordpress.com/read/post/feed/34277/748247632</sup>

Note from @blowery 

> Videopress is busted there because wordpress.tv is still using the old player, until they get caption support. Should be switching pretty soon.

Note form @shaunandrews 

> > The index view had a description that is trailed off, but the single view has no description at all
> 
> This is because there is an excerpt—which we show in the stream—but no text in the post content. We could show the excerpt in the full post view, but then you'll often have repeating content.

**Comment by blowery** [comment]
Closing because this is a particular issue with wordpress.tv and they've since switched over to using the new player. We can't show excerpts when there's no body text because that's not a consistent patten used across many blogs.
