### ISSUE TITLE
Themes: Support long title names

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#9700]
Currently we assume all theme names fit on a single line. If we ever have a theme name that breaks to two lines, we won't have access to the theme action ( 3 dots ) or if the theme is activated, the active label is not visible. 

It would be useful to add in a max-width or content fade that prevents this from happening. Note that we also need to leave room for price information.

<img width="876" alt="screen shot 2016-11-29 at 11 31 09 am" src="https://cloud.githubusercontent.com/assets/1270189/20725683/80adc7bc-b627-11e6-88ef-a0d15105e388.png">

To reproduce, navigate to https://wordpress.com/design and manually edit the name using dev tools.

**Comment by folletto** [comment]
Not likely, but might be related to https://github.com/Automattic/wp-calypso/issues/10661

**Comment by folletto** [comment]
Fixed in #11229.
