### ISSUE TITLE
Design: Map Logged-in flows

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#97050]
## Details

For users who are already logged in and want to create a new site, we propose to guide them directly to the Goals screen so they can select which type of site they want to create. Then the flow will be exactly the same as the logged-out experience, but without going through the account step. So:

`Add new site` → `Goals Step` → `Design Choice` (Design Picker or Big Sky) → `Domains` → `Plans` → `Launchpad` 

![Image](https://github.com/user-attachments/assets/99cc5bdc-a3a2-44d8-9d57-ebed06b3213c)

See Figma: W9xI27S6Swvw5Ku21EbZvn-fi-8321_6169

If users select "Skip to admin" we will follow [same approach](https://github.com/Automattic/wp-calypso/issues/96055#issuecomment-2519341271) than logged-out (minus the account step):

`Add new site` → `Goals Step` → `Skip to admin →` `Domains` → `Plans` → `Launchpad` 

### Future iterations:

@lucasmendes-design Explored here (p9Jlb4-fgB-p2) how to better manage this "add new site" option, reusing the A4A flyout. This opens the opportunity to add goal-oriented options as entry points (e.g. Blog, Newsletter, Store, Portfolio...):

![Image](https://github.com/user-attachments/assets/33d7d4a2-6af3-40e4-b09e-e38988eefefe)

**Comment by lucasmendes-design** [comment]
> Explored here (p9Jlb4-fgB-p2) how to better manage this "add new site" option, reusing the A4A flyout. This opens the opportunity to add goal-oriented options as entry points (e.g. Blog, Newsletter, Store, Portfolio...):

I'll share a new proposal considering this option as well :)
