### ISSUE TITLE
My Home: Alignment issues and inconsistencies on mobile

### ISSUE THREAD

**Issue by m1r0** [Automattic/wp-calypso#97066]
### Quick summary

On the My Home screen there are a few styling issues on mobile.

Could be related to https://github.com/Automattic/wp-calypso/issues/96936.

### Steps to reproduce

1. Go to https://wordpress.com/home/YOUR-DOMAIN
2. Scale the screen to a width of 599px (mobile resolution).
3. There are some styling inconsistencies like inconsistent/missing paddings and missing/extra separators. Please take a look at the screenshot below.

### What you expected to happen

To have consistency in the design.

### What actually happened

The spacings and some of the elements are inconsistent as shown in the screenshot:

![Image](https://github.com/user-attachments/assets/7cfa2ebc-845e-4f96-8167-dc613133f9b9)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by supernovia** [comment]
I'm marking this as in-triage since it's likely related to this issue which is also in triage. 
https://github.com/Automattic/wp-calypso/issues/96936
