### ISSUE TITLE
Stepper: Back from Checkout to Domains resets the website

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97077]
IN START:

If you Domains -> Plans -> SITE CREATION -> Checkout -> Browser back to Plans -> Domains

You will still see the old domain chosen. 

IN STEPPER:

If you Domains -> Plans -> SITE CREATION -> Checkout -> Browser back to Plans -> Domains

You **will not** see the old domain.

We should remember the old website chosen. This will probably avoid creating a new website if returning to checkout.

**Comment by alshakero** [comment]
> We should remember the old website chosen. This will probably avoid creating a new website if returning to checkout.

Luckily the site is not being recreated and the same site is used.

**Comment by alshakero** [comment]
I can't reproduce either of these issues.

**Comment by escapemanuele** [comment]
STEPPER:
![Image](https://github.com/user-attachments/assets/cac700f5-b257-47ad-b8a2-213c37619a27)

I tried going back to Domains using your [PR](https://github.com/Automattic/wp-calypso/pull/97074), and I don't see the website selected as in Start

START:
![Image](https://github.com/user-attachments/assets/9724f758-6ef0-4340-b8b9-721e74c81c1e)

**Comment by alshakero** [comment]
@escapemanuele let's huddle tomorrow to have this sorted. I really can't repro.

**Comment by escapemanuele** [comment]
@alshakero I tried reproducing this and:
- This doesn't happen for a custom domain
- This happens for free domains, not a big problem I think, but...
- Every time I go back to checkout I see a new website [URL].wordpress.com in the URL

**Comment by alshakero** [comment]
OK I finally understand the issue now!

**Comment by alshakero** [comment]
PR https://github.com/Automattic/wp-calypso/pull/97369
