### ISSUE TITLE
Stepper: Missing indication on current plan when back from checkout

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97078]
In START:

If you Domains -> Plans -> SITE CREATION -> Checkout -> Browser back to Plans

![Image](https://github.com/user-attachments/assets/501f002c-ac90-425e-8432-13c7882b38f1)

(Given that you didn't proceed with the checkout, your current plan will be the FREE one)

IN STEPPER:

This doesn't happen. It should.

We don't have the correct `selectedSite` here https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/plans/index.jsx#L459

**Comment by alshakero** [comment]
Ugh missed your assignment and [sent a PR](https://github.com/Automattic/wp-calypso/pull/97361)! Yours looks better though.

**Comment by escapemanuele** [comment]
This has been fixed in https://github.com/Automattic/wp-calypso/pull/97375
