### ISSUE TITLE
Stepper: Figure out why the wide discrepancy on signup start referrer between start and stepper during the experiment

### ISSUE THREAD

**Issue by MicBosi** [Automattic/wp-calypso#97073]
Slack conversation: p1732718523042509-slack-C073776NJ66

It appears that stepper is getting the majority of the traffic from the LOHP without locale suffix, while control is getting most of its traffic from the LOHP with the locale suffix.

Control also gets practically all the other referring traffic (google, bing, random sites etc.) and stepper appears to be getting none of it.

However, if we look at the distribution of languages (based on the browser lang reported by Tracks) we appear to see languages roughly evenly distributed between the two variations.

We would like to understand the mechanics of how this happens so that we can explain whether there is a qualitative difference between the traffic sent to stepper vs the one sent to control that can explain the SRM issue at the signup start step.

**Comment by skim1220** [comment]
### Another investigation Result (for Context): 

We investigated whether participants assigned to ExPlat’s exposure strategy actually experienced exposure events after their assignment. Interestingly, the control group had significantly more participants who lacked an exposure event post-assignment (43,635 vs. 2,678). This suggests that many unintended participants may have been included in the control group, indicating a potential issue with the experiment setup.

Further analysis revealed that most participants in the exposure strategy who didn’t experience an exposure event after assignment had already triggered one within the 5 seconds _before_ their assignment. In fact, the majority of these events occurred just milliseconds before assignment ([screenshot](https://d.pr/i/nBqRma)). More details can be found [here](https://analyticsorienteddata.wordpress.com/2024/10/16/investigation-sample-ratio-and-registration-anomalies-in-calypso_signup_onboarding_stepper_flow-experiment/#comment-4897).

Although this aligns with ExPlat’s 5-second grace period, it raises an important question: **why did the control group have a higher proportion of users triggering an exposure event within the -5-second window before assignment?** The shares should be similar across both control and treatment groups.

**Comment by MicBosi** [comment]
I think we might have found the cause of the issue being the fact that all Stepper traffic in the experiment is redirected in JS/Calypso using `Referrer Policy: origin` which truncates the referrer to just be the domain, in this case wordpress.com

See full explanation in Slack: p1733786423894269-slack-C073776NJ66

**Comment by MicBosi** [comment]
@escapemanuele I'm closing this issue as per Slack conversation mentioned above I think we have a satisfactory explanation.
