### ISSUE TITLE
Application Passwords: Inconsistency on the Figma design

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#97082]
We noticed that we have two different designs for the Authorization step. We should confirm which we should be using.

The one I applied was the following: F8foKv974Gc5dTHSh0i0Wo-fi-680_6572

However, we also have this model: F8foKv974Gc5dTHSh0i0Wo-fi-680_6536

More context: p1733335064729919/1733315236.570409-slack-C0Q664T29

cc @fditrapani @andres-blanco

**Comment by fditrapani** [comment]
Thanks for the ping @valterlorran. The one you were working on was an older version. It was an oversite on my part and missed updating it after I updated the new one. This is the correct one for the copy + icons: [F8foKv974Gc5dTHSh0i0Wo-fi-680_6536](https://href.li/?https://www.figma.com/file/F8foKv974Gc5dTHSh0i0Wo/?node-id=680-6536)

The one you shared is still good for the error message. I'm going to update it with the right icons + copy.

**Comment by valterlorran** [comment]
Thank you very much! I will apply it then!
