### ISSUE TITLE
navigation URL doesn't update when primary domain changes. URL from another site.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/wp-calypso#97090]
### Quick summary

website, personal plan, Appleton theme. User had custom domain which expired and no longer exists. User chose another domain. Homepage navigation will not update when the primary domain is updated. Navigation URL remains the original domain.

### Steps to reproduce

1. started with Personal test site using default WP.com domain.
2. added Appleton theme. 
3. connected custom domain.
4. switch custom domain to primary.
5. Navigation on homepage has the same menu items, but all URLs are going to a completely separate site, another test site on premium plan.

### What you expected to happen

When switching domain to primary, all internal links in site should update with primary domain.

### What actually happened

The initial links go to another domain. Updating the primary domain does not update internal URLs for Navigation block.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

manual editing of URLs in navigation block/site editor.
Once URLs are manually edited, they do update with domain primary change. URLs that are not edited, do not get updated with domain primary change.

### Platform (Simple and/or Atomic)

Simple

**Comment by radtechgh** [comment]
9125465-zen

**Comment by supernovia** [comment]
📌 ACTIONS
- Closed as duplicate
- Noted case in the other issue so it can be fixed


📌 Message to Author
Hi @radtechgh , this one's a known issue unfortunately.  I'm closing in favor of this issue & have noted the case there.
https://github.com/Automattic/wp-calypso/issues/94034
