### ISSUE TITLE
Reader: Mesh embeds look squished

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#971]
Raised by @mjangda 

Mesh embeds include some styles to enforce a `min-width` and `min-height`. Looks like the Reader might be stripping those out which results in the embed looking a bit squished.

<img width="783" alt="screen_shot_2015-08-06_at_12 02 06_pm" src="https://cloud.githubusercontent.com/assets/86105/9121348/a93adad8-3c4f-11e5-83bb-4d74850a1543.png">

The post with the embed: https://wordpress.com/read/post/feed/165883/772649996

Note from @jasmussen 

> Deployed a fix to the Mesh embed code, so at least it doesn't collapse into a thin line like that. Now, if styles are stripped, it'll be 100% x 500px.
> 
> Would still be nice to keep the oEmbed styles.

**Comment by blowery** [comment]
We generally cannot trust style attributes on an iframe, because CSS can execute code and certain styles can break our layout. We do let some things through though...

**Comment by jasmussen** [comment]
I think we can probably close this for now, and open a new one in the future. But the fact that iframes strip out tags in general seems to suggest we need a different approach.
