### ISSUE TITLE
Global Styles tab not working as expected for some themes after it was moved to top level menu

### ISSUE THREAD

**Issue by Neha93517** [Automattic/wp-calypso#97104]
### Quick summary

The global Styles tab is unresponsive and does not open for some themes after it was moved to top level menu following the Gutenberg version 19.7 update. Currently, two FSE themes are affected:
- Creatio 2
- Craftfully

Happening on both simple and atomic sites, and it's WordPress.com specific.

### Steps to reproduce

1. Go to Appearance > Themes
2. Find and activate Creatio 2 theme
3. Go to editor and click on Styles tab

### What you expected to happen

The style tab should open as shown here: ![Image](https://github.com/user-attachments/assets/ed9c729a-0ab7-47e1-86ec-7bd89f650666)

### What actually happened

Tab is unresponsive and doesn't open. Screenshot here: ![Image](https://github.com/user-attachments/assets/c0ee43ef-3c9c-4693-a36c-4a54fe2be8d3)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The workaround for now is to share a direct link to open the Styles tab:
https://yourddomain.com/wp-admin/site-editor.php?path=%2Fwp_global_styles 

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes
Related to
Zen-100301

**Comment by rosepajaroja** [comment]
Similar issue here: 

9143692-zen

It's also still accessible through "Styles" icon on the top right corner of the Site Editor.

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple / Atomic / Core; replicated with certain themes


📌 FINDINGS/SCREENSHOTS/VIDEO
This needs a core fix, which has a fix coming soon! I set status accordingly 
https://github.com/WordPress/gutenberg/issues/67532


📌 ACTIONS
- Switched to Needs Core Fix

**Comment by annezazu** [comment]
Closing this out as it should be fixed two weeks ago :) https://github.com/WordPress/gutenberg/issues/67532 This fix landed in 19.9 which is live on WordPress.com.

If that's not the case, please let me know and reopen.
