### ISSUE TITLE
Sites dashboard: Clicking a site as non-admin leads to a broken flashing state

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#97109]
### Quick summary

If I'm a non-admin of a site, and I click on that site from `/sites`, I'm supposed to get redirected to My Home immediately. However, I see a flashing screen of broken flyout panel.

### Steps to reproduce

1. Invite a test user to a site as Contributor / Editor.
2. Log in as that user.
3. Go to /sites.
4. Click on that site.

### What you expected to happen

I see My Home immediately.

### What actually happened

I see a broken intermediate state:

https://github.com/user-attachments/assets/6a3f7981-fa27-457b-ba99-24955f3c9f66

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Logs or notes

It's similar to https://github.com/Automattic/dotcom-forge/issues/7311.

I think it's a regression when we decouple the sites dashboard logic from A4A.

**Comment by okmttdhr** [comment]
Thanks for fixing this, @fushar 🙏
