### ISSUE TITLE
Reader: Inconsistent layout on empty posts

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#97135]
### Quick summary

Check Joseph's feed:

https://wordpress.com/read/feeds/36/posts/5479464312
![Image](https://github.com/user-attachments/assets/596f7471-94ff-4ce5-bea7-3819406a164a)

This doesn't look great.

### Steps to reproduce

Visit https://wordpress.com/read/feeds/36/posts/5479464312

### What you expected to happen

See a reader post page, recognizable sidebar and main section

### What actually happened

It looks like an HTML table that half-loaded.

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by Robertght** [comment]
It looks like there might be something else at play there, as my empty post came up as this:

https://wordpress.com/read/feeds/162201801/posts/5491207520

![Image](https://github.com/user-attachments/assets/74b483b6-d0e5-49b2-b46f-63cbb72e2d81)

@Automattic/loop I can see this is in your inbox, but I'm leaving it as a low priority for now.

**Comment by davemart-in** [comment]
Looks like we just need to apply `flex: 1` to the content container:

https://github.com/user-attachments/assets/3dfc6434-2acd-4a50-a16a-e92a7a254366

Adding this to our list.

**Comment by allilevine** [comment]
> Looks like we just need to apply `flex: 1` to the content container:

I opened a PR: https://github.com/Automattic/wp-calypso/pull/97521

Do we know why Joseph's feed returns empty posts? It's a disconnected Jetpack site, but that shouldn't stop the RSS from loading.

**Comment by allilevine** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/97521
