### ISSUE TITLE
`Invalid scope: user_profile` in Instagram blocks due to deprecation of Instagram Basic Display API

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#97151]
### Quick summary

We have users reporting an error when connecting to Instagram via `Instagram latest posts` block or `Tools > Marketing > Connections`. The error message is: "Invalid Request: Request parameters are invalid: Invalid scope: user_profile".

### Steps to reproduce

- Connect an Instagram account at Tools > Marketing > Connections
- Or try setting up the `Latest Instagram posts` block on any part of the site: page, post or widget

### What you expected to happen

Able to set up Instagram connection without an error.

### What actually happened

An error appears with the message `Invalid Request: Request parameters are invalid: Invalid scope: user_profile`.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Seems to be due to deprecation of Instagram Basic Display API: https://developers.facebook.com/docs/instagram-platform

![Image](https://github.com/user-attachments/assets/cba35c52-546a-420f-8c44-22386fd54443)

cc @pablinos

**Comment by arunsathiya** [comment]
- 9137482-zen
- 9132451-zen
- 9135055-zen
- 9134764-zen

**Comment by happychait** [comment]
9137136-zen

**Comment by arunsathiya** [comment]
9132352-zen
9134399-zen
9133714-zen
9135313-zen
9135845-zen
9136681-zen
9136229-zen
9136603-zen
9135888-zen
9134242-zen
9133548-zen

**Comment by daria2303** [comment]
9140082-zd-a8c

**Comment by dragstor** [comment]
9140160-zen

**Comment by susanjanec** [comment]
9132352-zen

**Comment by jorpdesigns** [comment]
9140768-zen

**Comment by jorpdesigns** [comment]
9141912-zen

**Comment by chad1008** [comment]
9142721-zen

**Comment by Robertght** [comment]
Marking this as "In progress" as it's actively being worked on.  I pinged [here](p1733516273706619-slack-C0840HT84MA)

**Comment by hacchism** [comment]
Another report: 9147405-zen

**Comment by mdtanjid0** [comment]
Another report here: 9148455-zen.

**Comment by donalirl** [comment]
9148481-zen

**Comment by mdtanjid0** [comment]
9133548-zen (needs to be followed-up).

**Comment by pablinos** [comment]
By way of an update, I have a patch D168000-code which swaps over to using the new Instagram API, for test users. That can be reviewed first thing tomorrow, and then I can submit to Facebook's app review. How long that takes is anyone's guess, but it's been a few hours before. I'll also email a previous contact we had there, in case they help with expediting it.

Once we're approved, we can swap to the new API for all users and then everyone will need to reconnect. They'll only be able to do that if they are using Instagram Creator/Business accounts.

**Comment by jordesign** [comment]
Another report in 9150745-zd-a8c

user would like to be notified when resolved.

**Comment by filipanoscampos** [comment]
Another report here: 9152145-zd-a8c

**Comment by filipanoscampos** [comment]
Another one 9151483-zd-a8c

**Comment by pauljacobson** [comment]
I'm unsure whether this is related but I have a user who has tried to connect their site to a Business Instagram profile, seemingly for the first time, and they encountered this error:

```
There was a problem exchanging an Instagram access token for a long lived one
```

9152578-zen

**Comment by mdtanjid0** [comment]
- [ ] Another one 9155278-zen ( needs to be followed up).

**Comment by khristiansnyder** [comment]
9158959-zen

**Comment by arunsathiya** [comment]
9161151-zen

**Comment by devNigel** [comment]
9161762-zd-a8c

User wants to be notified by email when the issue is resolved.

**Comment by lailagmelo** [comment]
9160469-zen

**Comment by pablinos** [comment]
The fix is live now, so it should be possible for customers to start reconnecting to Instagram

**Comment by arunsathiya** [comment]
I informed all customers from [this list](https://github.com/Automattic/wp-calypso/issues/97151#issuecomment-2521931105).
