### ISSUE TITLE
Copy Site: overlapping header

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#97155]
### Quick summary

In Copy Site feature, the heading overlaps with the back button.

### Steps to reproduce

1. Go to `/settings/genera/:siteSlug`.
2. Scroll down and click "Copy site":

![Image](https://github.com/user-attachments/assets/27b4653c-177d-49ea-95b7-dc973d1e1674)

### What you expected to happen

In narrower screen width, the header looks good.

### What actually happened

In narrower screen width, the header overlaps with the back button:

![Image](https://github.com/user-attachments/assets/fa552776-2dc1-4e8a-98ff-0222c094263f)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- only Business Plans have this feature, so tested on Atomic


📌 FINDINGS/SCREENSHOTS/VIDEO
This happens on a pretty wide range of widths
https://github.com/user-attachments/assets/b04246b3-c7eb-4d4c-816d-922261ef25d6


📌 ACTIONS
- Triaged
