### ISSUE TITLE
Stepper: Mobile doesn't show selected domain near the bottom when back from Plans

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97176]
Start | Stepper

![Image](https://github.com/user-attachments/assets/cea985d0-d3ad-4e18-8461-a12a94b68c9f)

This happens when coming back from Plans

**Comment by heavyweight** [comment]
https://github.com/user-attachments/assets/89f50b2e-c364-4247-835a-320470e1ffeb

This works fine for me. @escapemanuele can you reproduce this issue?

**Comment by escapemanuele** [comment]
Sorry @heavyweight, this should happen when you go back to Domains from Plans, can you check that?

**Comment by alshakero** [comment]
PR https://github.com/Automattic/wp-calypso/pull/97375
