### ISSUE TITLE
Help Center: show "loading" instead of "Nothing found" in chat history window

### ISSUE THREAD

**Issue by alshakero** [Automattic/wp-calypso#97170]
### Quick summary

Currently, the Help Center shows "Nothing found" instead of a loading indication in the chat history window. It's a bit unpleasent and easy to fix.

### Steps to reproduce

1. Open the Help Center.
2. Click History

### What you expected to happen

A "Nothing found" message is briefly shown.

### What actually happened

A loading indicator should be shown instead.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by alshakero** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/97181

**Comment by supernovia** [comment]
Ah thank you @alshakero ! Since you're assigned I'll go ahead and mark this as Triaged, but if you need any testing/triaging from PAs just let us know. Cheers!
