### ISSUE TITLE
Typo on /move LP

### ISSUE THREAD

**Issue by sailerbe** [Automattic/wp-calypso#97183]
### Quick summary

On one of the variations of the default domain search field, "place-hodler" instead of "place-holder."

### Steps to reproduce

Visit https://wordpress.com/move/ and refresh the page to cycle through options until the following appears (though I'm assuming there's a better way to track down the actual source of the issue on the backend):

![Image](https://github.com/user-attachments/assets/0b041337-1985-41f1-ac01-ca4063e75624)

### What you expected to happen

All copy on our site should be error-free.

### What actually happened

I found a typo.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- replicated!

📌 ACTIONS
- Triaged
- Pinged in slack: p1733532866284489-slack-C06H9KE62DS

**Comment by cpapazoglou** [comment]
Fixed in D168074-code and deployed r310370-wpcom
