### ISSUE TITLE
The add-on menu item doesn't appear in the admin menu of an Atomic site

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#97227]
### Quick summary

An example screenshot on my test Atomic site:
![Image](https://github.com/user-attachments/assets/a5bc5b5d-147a-4099-84b2-c39d55c7866d)

It should be there just like on Simple sites. 

Note: it worths to also check how it looks on a site choosing the wp-admin interface. 

### Steps to reproduce

1. Log in to an Atomic site
2. Expand the Upgrades menu item

### What you expected to happen

There should be the add-on menu item

### What actually happened

There is no add-on menu item

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

* Access the add-on page by directly accessing `/add-ons`
* For storage add-ons, they can still purchase through the drop-down in `/plans`

### Platform (Simple and/or Atomic)

Atomic

**Comment by fushar** [comment]
After doing some archeological code digging it seems that this behavior is "expected", though I'm not sure why:

- https://github.com/Automattic/jetpack/pull/25085

> The new add-ons menu, for now, should only appear for simple, non-atomic/jetpack sites.

@chriskmnds / @jeherve / @coder-karen / @fgiannar, could you check if this is really expected? Thanks!

**Comment by jeherve** [comment]
I believe it made sense at the time ; you couldn't purchase add-ons on a WoA site, that didn't need any add-on. 
Are add-ons necessary on a WoA site today?

**Comment by Robertght** [comment]
I don't know if this is expected, but we're surely allowing users to purchase extra storage if needed:

https://wordpress.com/support/space-upgrade/

Right now this can be accessed only through a direct link or from https://wordpress.com/overview/[site-name] and click on "Need more storage?".

**Comment by southp** [comment]
Yes, as @Robertght said :) It looks like an expected behavior like @gmovr clarified here: pau2Xa-6Ad-p2#comment-16486 . However, as I followed up in pau2Xa-6Ad-p2#comment-16489, we'd still need it particularly for the storage add-ons. The "Need more storage?" button links to `/plans`, but it won't help the users on a 2Y/3Y plan: Automattic/martech#2614. Before we have something better, it'd be the best to bring back the add-on menu item for them.
