### ISSUE TITLE
Reader: deal with network errors better on streams

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9722]
If there's a network error, we produce a page like this:

![screen shot 2016-11-30 at 9 28 40 am](https://cloud.githubusercontent.com/assets/24388/20763736/300e0b3c-b6e0-11e6-935f-80c2f1ae8fc7.png)

@blowery sez: "file a thing. we should deal with errors better."

**Comment by fraying** [comment]
@blowery Is this sill an issue?

**Comment by blowery** [comment]
Yup, still an issue.

**Comment by bluefuton** [comment]
We now show placeholders and an error notice.
