### ISSUE TITLE
The lower-tiered storage add-ons comparing to the owned one can't be purchased but appears to be available.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#97225]
### Quick summary

Since the storage add-on is a tiered product, users can't purchase a higher-tiered one and then purchase a lower one. e.g. they can't purchase a 100G and then purchase a 50G, since under the hood they are the same product at different tiers. Currently we prevent this illegal operation only at the checkout step:

https://github.com/user-attachments/assets/dbb15241-8925-47ad-8970-4912d259d5a3

Ideally, we should prevent it from happening right from the start. I suspect this issue has always been there but was shadowed by https://github.com/Automattic/wp-calypso/issues/86150. 

### Steps to reproduce

1. Purchase a 100G storage add-on from `/add-on`.
2. Purchase a 50G storage add-on from `/add-on`
3. Go through the checkout 

### What you expected to happen

I should not be able to pick the 50G add-on from the first place.

### What actually happened

The action was only prohibited after clicking "pay" in the checkout.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Simple

**Comment by fredrikekelund** [comment]
After working on this issue for a bit, I can confirm that it only happens when storage add-ons are purchased in the store sandbox.

Currently looking into if we can simplify/improve how add-on availability is calculated…

**Comment by fredrikekelund** [comment]
Closing this as not planned and pursuing the refactoring separately.

**Comment by fredrikekelund** [comment]
I found a case where this actually applies to production: free sites.

**Comment by southp** [comment]
> After working on this issue for a bit, I can confirm that it only happens when storage add-ons are purchased in the store sandbox.

@fredrikekelund I'm not sure what we have done differently, but I can produce this on a Premium site with 100G storage add-on purchased by wpcom credits:

![Image](https://github.com/user-attachments/assets/645220b2-8f57-43a7-af86-853288b14f59)

![Image](https://github.com/user-attachments/assets/c06b0388-8ab2-4615-b9ee-dfc8d1a56ee6)

So at least from my experience, it's not only about the free sites :)

**Comment by fredrikekelund** [comment]
> I can produce this on a Premium site with 100G storage add-on purchased by wpcom credits

Thanks for confirming that, @southp 👍 After my comment on this issue, I realized that this likely affects Premium plans, too (I even mentioned it briefly in the PR description)
