### ISSUE TITLE
Community themes: with-theme onboarding flow is broken

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#97248]
### Quick summary

The onboarding flow for Community themes is currently broken. I've found two related issues:
1. It displays all plans in the plans page, not just the required ones (business and ecommerce). This means that users coming from the Logged out ThemeShowcase (https://WordPress.com/themes), after they sign up, they are able to select an incompatible plan with their theme.

2. No matter what plan I select, the onboarding gets stuck in setup/site-setup/processing with a JS error - selecting a compatible plan (Business), will still redirect to a loading screen - without the theme being installed on their site.

### Steps to reproduce

1. Open incognito
2. Go to https://WordPress.com/themes
3. Search for Astra
4. Click pick this design
5. Signup/login
6. Create a new site
7. Notice that all plans are displayed, including "Free", "Personal", "Premium" - giving the users the impression that they're able to use Astra with a non-business plan
8. Select free/Business/etc
9. Notice that you're stuck in a loading screen in setup/site-setup/processing

### What you expected to happen

- I should get only Business and eCommerce plans since those are the only ones compatible with a community theme
- The onboarding shouldn't get stuck

### What actually happened

I don't get the Community theme installed.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by gabrielcaires** [comment]
I could reproduce the bug.
![Image](https://github.com/user-attachments/assets/56abf6cf-bee9-412c-a6b7-d7a78e91da4b)
