### ISSUE TITLE
Stop Tag pages from Reloading when Followed

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9727]
#### Steps to reproduce
1. Starting at any tag page that you're NOT following, like: http://wpcalypso.wordpress.com/tag/whatever (the bug exists on live site, too)
2. Click "Follow Tag" at the top.

#### What I expected

The "Follow" link to turn to the "Following" state without a page reload.

#### What happened instead

The page reloads and the "back" link appears. But clicking the back link does nothing (just links to the page you're already on).

#### Browser / OS version

Safari 10.0.1 / macOS 10.12.1

**Comment by blowery** [comment]
I think what's happening is we're redirecting to the tag stream when we subscribe to the tag. Probably need to stop doing that, or notice that we're already on the target and skip it.

**Comment by samouri** [comment]
^ went with notice we are on the target
