### ISSUE TITLE
Task: Update Design Picker theme pricing labels

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97295]
### Details

See this P2 discussion p9Jlb4-fea-p2#comment-14576  and check in with @fditrapani with design questions and design approval.

Themes can be:
* Free
* Premium
* Partner

We need to reflect this in the labels on each theme for the logged-out Design Picker

![Image](https://github.com/user-attachments/assets/27f800b7-e9c5-4415-a3f6-1a540b5f3bdc)

### Checklist

- [ ]
- [ ]

**Comment by autumnfjeld** [comment]
@fditrapani    Can you add Figma links or verify that this is correct:

* Free -> no label
* Premium -> Premium badge  with star
* Partner -> Partner badge with star


This is a badge:
![Image](https://github.com/user-attachments/assets/b8921122-d703-4798-8952-2ca7263cc1ce)

**Comment by fditrapani** [comment]
@autumnfjeld I've documented the ideal behaviour in this issue: https://github.com/Automattic/wp-calypso/issues/95471#issuecomment-2529511388

Let me know if you think that's possible for the scope of our MVP. Otherwise, we can figure something out that's simple and then follow up with what's outlined in the issue.

**Comment by autumnfjeld** [comment]
@fditrapani  your designs cover the logged-in theme showcase.  

For the logged-out onboarding Design Picker the following mockup could apply, but maybe we need some further discussion.


> An upgrade badge that shows Available on {plan name} for any themes available on higher plans. For partner themes, we'll show Available on Business unless you're on the Business or Commerce plans, in which case, we'll just show the price:
![Image](https://github.com/user-attachments/assets/232d47d8-7371-4960-8369-56f52918cb3c)


* The user will not yet be aware of the concept of "plans" 
* Can you add specifics here so we know exactly what copy and style to implement
* For example
  * Free -> light blue badge with "Free"
  * Premium themes -> ?
  * Partner themes -> Show start icons with price/month

**Comment by fditrapani** [comment]
Thanks for checking that out @autumnfjeld.

> The user will not yet be aware of the concept of "plans"

That is true. The language with the plan names is intended to prime them for what's coming up soon on the plans page. Alternatively, for the design picker, we can keep it more generic and say `Available on paid plans` for any non-free theme.

> Can you add specifics here so we know exactly what copy and style to implement

Here's how I can see it breaking down:
- Free themes: Show free blue badge.
- Included with plan: If you happen to be logged in and on a paid plan, any non-free themes that are available to you will say "Included with plan".
- Premium themes: any theme that's not free should show "Available on {Plan name}" where plan name is the name of the plan it's available on (eg Available on Personal, ... Available on Commerce, etc.). Alternatively, we can use "Available on paid plans" if we want to keep it generic while you're logged out and on a free plan.
- Partner themes: similar to your comment of the plans, I think the partner concept is even harder to grasp at this stage. Especially with the added fee. I don't think we should include any extra badges and only show the price if you're on the business plan or higher. We can communicate the price on the following screen when people are looking at the theme details.

Let me know what you think.

**Comment by vykes-mac** [comment]
@autumnfjeld @fditrapani Do we have a decision on this? Will the logged-in version remain as is?

**Comment by paulopmt1** [comment]
> Free themes: Show free blue badge.

For that we have a [new Badge component from Gutenberg](https://wordpress.github.io/gutenberg/?path=/docs/components-badge--docs) which is this blue:

<img width="249" alt="Image" src="https://github.com/user-attachments/assets/b904fff2-8540-435c-bb60-e7b58d14bb30" />

Are you referring to that one @fditrapani? 

If so, unfortunately, we can't use it right now since it's too new (p1734617665728429-slack-C45SNKV4Z). Should we stick with the [the Calypso Badge implementation](https://wpcalypso.wordpress.com/devdocs/design/badge) until we have the Gutenberg one available for us? 

That would prevent us from adding custom CSS to meet this requirement. Once we have the new Gutenberg component in place, we can simply replace it.

**Comment by fditrapani** [comment]
> Will the logged-in version remain as is?

@vykes-mac for the scope of this project, we should leave the logged in view as is. We can implement these updates into the design picker which include hiding the swatches and moving the free/paid messaging in their place.

> Should we stick with the [the Calypso Badge implementation](https://wpcalypso.wordpress.com/devdocs/design/badge) until we have the Gutenberg one available for us?... 

Thanks for the question @paulopmt1. Let's go with the Calypso component for now!

> That would prevent us from adding custom CSS to meet this requirement.

Can you expand on this? I'm curious why we wouldn't be able to override it in this case. The blue isn't the right blue and I've seen us override it in some other areas like in the migration flow:

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/2d87c026-34f4-46a7-b0be-51b5a44c93f7" />

> Once we have the new Gutenberg component in place, we can simply replace it.

That would be nice!

**Comment by fditrapani** [comment]
Awesome! Thanks for these updates. I'm fine with not using the border radius at the moment. That can come when we swap out the components. Any chance we can update the colour of the badge to match what I have in the design. It's very prominent right now and doesn't need to be. We want it to stand out but not at the expense of everything else.
