### ISSUE TITLE
Action Bar: Login link redirects to empty site when site has no posts

### ISSUE THREAD

**Issue by dereksmart** [Automattic/wp-calypso#97290]
### Quick summary

On a wordpress.com site with: 
- a mapped primary domain
- no posts

This login link ends up on a blank white page. 

![Image](https://github.com/user-attachments/assets/62aa2105-d4b4-4de3-9caf-877399b45d91)

### Steps to reproduce

1. Map a domain to a wordpress.com simple site
2. Delete all the posts from the site
3. Log out of the site, visit the front end
4. Click "Log In" in the actionbar, and follow the flow

### What you expected to happen

To be redirected back to the site after logging in. 

### What actually happened

https://r-login.wordpress.com/remote-login.php?action=link&back

![Image](https://github.com/user-attachments/assets/27b5bff5-28fa-471b-8cf6-ee954b0f30b1)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The workaround is to publish a post. 

This is "easy" from a technical perspective, but users sometimes don't have or want any posts on their site. 

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Seems to have been introduced in D61523-code, which updated the `back` param to use get_permalink(), which returns false when there's no posts. That diff was related to 3rd party cookies work: https://github.com/Automattic/wp-calypso/issues/33077

Also of note, it doesn't seem to happen on sites on *.wordpress.com subdomain. Those have the `action=account` in the login, which works.

**Comment by Robertght** [comment]
I managed to replicate this with a mapped domain too. It's not happening with a registered one, though.

I'm raising priority to High as well.

**Comment by epeicher** [comment]
Diff deployed r311118-wpcom
