### ISSUE TITLE
Plugins: Single Plugin view - sites not grouped in a network

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#9729]
Currently when you visit a single plugin view and you have a WP network. We do not show the network associated with the site. 

Create a WP Mu network connect multiple sites to Jetpack. 
#### Steps to reproduce
Go to http://wordpress.com/plugins/akismet

#### What I expected
To be see a grouping of sites in the same network and only the main network site should be able to toggle the autoupdates.  

#### What happened instead
I was all the sites that were connected but there was no relationship between then. They did however have the right permission to do things. 

#### Screenshot / Video

![screen_shot_2016-11-30_at_10_39_26](https://cloud.githubusercontent.com/assets/115071/20766111/f41b56f2-b6e9-11e6-947c-8579b2540657.png)

cc: @johnHackworth and @tyxla :)

**Comment by tyxla** [comment]
Seems like this one is already resolved:

![](https://cldup.com/eHLWAPg9ul.png)
