### ISSUE TITLE
Me: it's possible to save a non-url as a web address

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#973]
A user can save total gibberish in this field at Me > Account Settings:
https://wordpress.com/me/account

![screen shot 2015-04-15 at 10 52 39 am](https://cloud.githubusercontent.com/assets/260253/7165641/aacfc426-e35d-11e4-948d-b3b724d2c07f.png)

When leaving comments with settings like mailto: and tel: saved as the web address, the commenter's username is not linked at all. It is only linked when the web addresses starts with http:// or https://.

**Comment by lancewillett** [comment]
In other words, validate input for this field and make sure it's a valid URL.

I'd say we should make HTTP(S) is optional so people can enter just a plain web link and we'll make it work.

**Comment by hoverduck** [comment]
07Apr16 Bug Scrub

Confirmed that this is still a bug.  Personally I'm not worried about being able to put gibberish in the field...the fact that it automatically puts the 'http://' at the start is good enough for me there.  But the fact that mailto: links aren't generated successfully bugs me.  Although that may not be in the Calypso side of things, but when the post is displayed.  Not sure.

**Comment by BandonRandon** [comment]
This still looks to be a problem here are some recent Screenshots:
![screenshot_19-05-2016-19 11 00](https://cloud.githubusercontent.com/assets/150348/15415141/9752d9fa-1df5-11e6-92f9-0821508be604.png)

Then upon saving:
![screenshot_19-05-2016-19 11 32](https://cloud.githubusercontent.com/assets/150348/15415145/9f3d136a-1df5-11e6-9bd8-73cc7d856f0a.png)

>  But the fact that mailto: links aren't generated successfully bugs me
I don't think we should allow `mailto:` here as this can be annoying when leaving comments.

**Comment by rachelmcr** [comment]
Confirmed that it's still possible to add text that is not a valid URL.

If we wanted to go beyond validating the URL, we might also consider other confusion that arises over this web address field. Users sometimes contact support because they entered a site address that doesn't exist, expecting it to change their site's address to the new one they entered. Perhaps we could also do a check to see if a site exists at the web address entered here?

**Comment by rclations** [comment]
I think this can be solved by switching that input to use an HTML5 url input type, which has native browser validation. Proposed updating the field type in #19129
