### ISSUE TITLE
Task: Show the correct "Free plan" modal

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97300]
### Details

While proceeding through the flow, the user may select a non-free feature (theme or domain) and then may choose the "Free plan" link in the Plans page.  To handle this we need show the appropriate information in the modal.   

We can start by using the existing modal component and its default design/buttons.   

## Existing modal component
https://github.com/Automattic/wp-calypso/blob/b71679c8e430e95f5ce63b64bb0063f95f9e0e22/client/components/theme-upgrade-modal

## Ideal design 
See Figma 4z6QzOQmmO7mhQAtQHQJR7-fi-9042_4133

![Image](https://github.com/user-attachments/assets/7e88fa44-1b7c-4d6a-8982-dd7cf1bea897)

### Checklist

- [x] Implement models per design
- [x] Get design review from @fditrapani 
- [ ] Implement tracks events for new modals, new UI and get a metrics review from @isatuncman-auto

**Comment by autumnfjeld** [comment]
@fditrapani :   For the Dec 20 prototype (and maybe for the first iteration shipping to customers) it makes sense to use the default modal and its confirm buttons.  Thanks for calling this out @lsl .   

https://github.com/Automattic/wp-calypso/blob/b71679c8e430e95f5ce63b64bb0063f95f9e0e22/client/components/theme-upgrade-modal

![Image](https://github.com/user-attachments/assets/11ca59a9-7597-4b7f-85d2-6f8aafcbe738)


We can revisit a new design in the near future.

**Comment by autumnfjeld** [comment]
@lsl  Can we repurpose the "cancel" and "upgrade" buttons to be choices of plans, like the ideal design shows:
![Image](https://github.com/user-attachments/assets/d2ac7860-46d3-4676-9e77-a99bbb1bf77c)


If not, then we'll just surface the minimum plan needed as is done currently in production.  Whatever is the most straightforward dev implementation.

**Comment by fditrapani** [comment]
> We can revisit a new design in the near future.

No problem! Let's keep it moving forward. 

How do you see the modal work if someone presses upgrade? Will we take them to checkout or to the domains screen?

**Comment by taipeicoder** [comment]
@autumnfjeld I've assigned this task to @arthur791004 to work on next week, any concerns?

**Comment by arthur791004** [comment]
> If not, then we'll just surface the minimum plan needed as is done currently in production.

I'd prefer this way. We can simply show a warning notice on the top to explain the reason for the minimum plan and allow people to go back or go to the specific step to change their selection. Does it make sense 🤔

**Comment by arthur791004** [comment]
**UPDATE**

Currently, the Plan screen has already supported the paid domain, so the modal will be shown when the user clicks ”start with the free plan”. We may just need to refine the copy to cover the following situations:
* paid theme
* paid theme + paid domain

**Comment by arthur791004** [comment]
<img width="656" alt="Image" src="https://github.com/user-attachments/assets/2ee26ae3-0078-4105-8285-465c1b2f6d9c" />

@fditrapani Do you have any idea on the above modal (this modal is ready on the production when you select a paid domain and click "start with the free plan") to cover the following situations:
* a paid domain is selected
* a paid theme is selected (personal, premium, business, etc)
* a paid styles is selected (i.e. global styles, colors, fonts)
* 2 of above are selected
* all of above are selected

Thank you!

**Comment by lsl** [comment]
@arthur791004 I think it makes sense here to copy the current implementation into a new modal behind the feature flag and refactor to the figma design in the description above. Treat global styles as if a theme was included for now.

**Comment by fditrapani** [comment]
What @lsl said :D 

These are the conditions we'll need to show the new modal:

- a paid domain is selected
- a paid theme is selected (personal, premium, business, partner, store)
- Global styles on a paid theme
- all of above are selected

Global styles on a free theme should be treated as a free theme since we show adequate upsells after the site is created.

**Comment by fditrapani** [comment]
Just wanted to make a note that we've updated the copy in Figma (4z6QzOQmmO7mhQAtQHQJR7-fi-9042_4133) to better reflect that you will be switched to a free theme:

![Image](https://github.com/user-attachments/assets/711a9bea-a955-4cf3-9709-a02e4317b393)

**Comment by isatuncman-auto** [comment]
@autumnfjeld @fditrapani 
I have a question (just to double-check): In the [Figma file](https://www.figma.com/design/W9xI27S6Swvw5Ku21EbZvn/Dotcom-Onboarding?node-id=8689-8480&t=iL5iHZLaVLGDt3Bp-0), I don’t see any specific details regarding the domain page escape hatch experience. Could you confirm if we’re treating the escape hatch click the same as a subdomain selection? When a user skips domain step, they are assigned a subdomain based on their username. So, selecting a free subdomain and skipping the domain step should have same impact on plans step modals.

Referring to the '**choose my domain later**' selection:
<img width="661" alt="Image" src="https://github.com/user-attachments/assets/fbfcdb27-2e95-45a5-bdf5-06b8700d333a" />

**Comment by arthur791004** [comment]
> selecting a free subdomain and skipping the domain step should have same impact on plans step modals.

Yes.

**Comment by fditrapani** [comment]
>  I don’t see any specific details regarding the domain page escape hatch experience. Could you confirm if we’re treating the escape hatch click the same as a subdomain selection? When a user skips domain step, they are assigned a subdomain based on their username.

Thanks for the question @isatuncman-auto. We aren't making any changes to the domain step in this iteration so we can treat it the same as we have been up until now.

**Comment by arthur791004** [comment]
It's completed by https://github.com/Automattic/wp-calypso/pull/97587.
