### ISSUE TITLE
Reader Refresh: Fix narrow breakpoints for recommended posts on Search

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9730]
In the [Refreshed Search Page](https://github.com/Automattic/wp-calypso/pull/9497) the recommended posts look wonky for the smallest breakpoint:
![example](https://cldup.com/2rKszHnDkm.png)

This issue can be closed when the breakpoints are fixed.

**Comment by blowery** [comment]
Should probably just drop down to 1 column of recs when it's narrow?

**Comment by fraying** [comment]
+1 on dropping to one column
