### ISSUE TITLE
Logs: labels not responsive in other languages

### ISSUE THREAD

**Issue by Robertght** [Automattic/wp-calypso#97316]
### Quick summary

Labels translated in other languages could overlap with the date column

### Steps to reproduce

1. Switch your website language to German
2. Access an AT site Hosting dashboard
3. Go to Logs
4. Check the labesl

### What you expected to happen

The labels should not overlap the date

### What actually happened

![Image](https://github.com/user-attachments/assets/56738a88-db95-4729-b0e0-c365fa6ecc1e)

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Saw it in an unrelated customer case.

**Comment by valterlorran** [comment]
Hey @Robertght, I think we should make the label container stretch to fit the label. But I have two other options, let me know what you think.

1 - This is my favorite option, we should be able to stretch the first column to fit the label:

![Image](https://github.com/user-attachments/assets/c85092b0-b7a3-4130-a7fa-1842682f3364)

2 - Add ellipses

![Image](https://github.com/user-attachments/assets/caf91efb-6690-4cf2-94ac-991ba1062928)

2 - Break the work

![Image](https://github.com/user-attachments/assets/24785d73-9376-42b3-ab61-da1aae20e680)

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on WordPress.com: replicated

📌 ACTIONS
- Triaged
- Downgrading priority from `Blocker` to `Normal`

📌 Message to Author
Thanks for reporting this one, @Robertght 

@valterlorran I agree that the first option is the best one here!

**Comment by gabrielcaires** [comment]
@valterlorran I assigned you just to keep the board up to dated

**Comment by Robertght** [comment]
Thanks @valterlorran ! I agree the first option looks better.

The ellipses option might work if it somehow renders the element in full when hovering over that element, but this sounds complicated and I don't know if it's suiting our design.
