### ISSUE TITLE
Stepper: Improve performances

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97337]
https://github.com/Automattic/wp-calypso/issues/96926#issuecomment-2533163210

By @MicBosi 

I also ran a few tests 4X for /start/user-setup and 4X for /setup/onboarding/user and one thing that captured my attention was the Largest Contentful Paint figure.

For Start I have: 10s, 10.2s, 10.4s, 9.6s
For Stepper I have: 17.9s, 16.1s, 13.1s, 13.1s

Granted these numbers are a bit volatile but they match another manual test I had done refreshing Stepper and Start in Chrome, using 3G and 4G Slow Network Throttling (to accentuate the differences) and tracking how many seconds it takes for the various social options to appear on the. page:

3G/Start: ~27s (~3.2MB downloaded)
3G/Stepper: 36s (~4.5MB downloaded)

I would say these are just preliminary figures but it might be worth looking into some of these key performance metrics to make sure Stepper is as optimised as Start before the next A/B test.

**Comment by alshakero** [comment]
We're now at 10.2, 10.7 s, 10.9 s, 10.3 s.

**Comment by alshakero** [comment]
After https://github.com/Automattic/wp-calypso/pull/97326, 

We're now at 8.4 s, 10.2 s, 8.0 s, 8.8 s, 8.4 s.

🚀
