### ISSUE TITLE
Stepper: New experiment avoiding double Calypso loading

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97331]
Context: p1733917930046279/1733914920.729849-slack-C073776NJ66

"the other issue for the Stepper variation is not just that Stepper loading might be a bit slower to load on slow connection, but also that we load Calypso twice, first to load the basic controller logic and then a second time to jump into Stepper because of the direct setting of window.location which initiate a full page reload"

**Comment by MicBosi** [comment]
Basically we need to figure out a way to setup the experiment in a way that the re-routing evaluation/execution does not favour either variation. 

Is there a way to forward users to the appropriate Stepper URL without reloading the page but in a more SPA (Single-Page App) like way?

---

A closely related but somehow separate issue is the following challenge:
- In theory the exposure event should happen _before_ users are exposed to either variation.
- However, when testing a new onboarding flow from it's first step (whether it's `user` or other) there's nothing "before" that and any Calypso event we chose as exposure event (eg `calypso_signup_start`) ends being fired from one of the two variations - which in theory is exactly what we shouldn't do.
- This challenge will always be present for any ExPlat experiment testing the first step of Calypso's onboarding flow.

We'll discuss with the ExPlat folks and see if they have concrete guidance on this, I suspect our options might be:
- Ignore the exposure event and just use the non-exposure strategy for experiment analysis.
- Same as above but keeping an eye on the exposure event to asses whether the new code/routing logic has fixed/improved the current SRM issue.

**Comment by escapemanuele** [comment]
We'll redirect both Start and Stepper in the new experiment: https://github.com/Automattic/wp-calypso/pull/97672
