### ISSUE TITLE
Reader Refresh Tag Headers - going to the right post onclick

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#9734]
As part of the reader refresh, we've created beautiful new tag page headers (see: #9704).
Currently when clicked, the tag header has two clickable areas:
1. Author name:  directs you to the blog that features the image
2. Blogs name: directs you to the blog that features the image

This PR aims to:
1. [x] Remove the blog name so it only reads: Photo by `author`
1. [x] Make the `author` text direct you to the post instead of the blog

**Comment by fraying** [comment]
Note that the credit should link to the post in Reader (not on parent blog). This is to keep it consistent with the link behavior of names in cards.
