### ISSUE TITLE
Stepper: Coupons are not applied

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/wp-calypso#97355]
Context: https://github.com/Automattic/wp-calypso/pull/96786#issuecomment-2532632328

Coupons provided from url query params aren't applied to checkout when visiting /setup. Additionally, the discount UI badges don't appear either.

#### `/start`

<img width="1693" alt="Screenshot 2024-12-10 at 11 21 24" src="https://github.com/user-attachments/assets/5071a35f-9ac6-4b4e-9591-8c3aabf4a3f8">

#### `/setup`

<img width="1700" alt="Screenshot 2024-12-10 at 11 21 31" src="https://github.com/user-attachments/assets/9728ec6d-fb70-4340-8fac-11fc54c5e3b6">

**Comment by alshakero** [comment]
Fix is here https://github.com/Automattic/wp-calypso/pull/97359
