### ISSUE TITLE
Theme Showcase: Remove the Support card in the logged-out detail page

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#97381]
### Quick summary

Currently, in the logged-out Theme Showcase we show the following support card:

![Image](https://github.com/user-attachments/assets/dacd1c10-c9a7-4326-a297-6c9ec885bfda)

This card is not clickable and provides no value to users. Let's just remove it.
For reference, this is what the card looks like when logged-in:

![Image](https://github.com/user-attachments/assets/6fbe3c6c-90fd-4f21-8835-aefd95802c61)

### Steps to reproduce

1. Open any theme detail page while logged-out, e.g.: https://wordpress.com/theme/twentytwentyfive
2. Scroll to the bottom and see the "support" card

### What you expected to happen

To at least be linked to some support resources.

### What actually happened

Nothing in the card is clickable.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by fditrapani** [comment]
Plus one for removing this!

**Comment by Robertght** [comment]
I was able to replicate this.

Marking as Triaged.

Flagging this for @Automattic/t-rex
