### ISSUE TITLE
Feature Request: Improve theme thumbnail tooltip

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#97380]
### What

Hovering a theme thumbnail shows its description, which can sometimes be verbose and even spammy. 
See the following screenshots for reference:

![Image](https://github.com/user-attachments/assets/3095f22f-b4b8-49cd-95ab-fd747f2750be)

![Image](https://github.com/user-attachments/assets/601ffabe-6062-4039-99c3-6225bf0a44f3)

Consider only displaying the first sentence and test the results.

### Why

Makes the tooltips less overwhelming and thus more digestible.

**Comment by fditrapani** [comment]
I've been wondering how helpful displaying this is. I haven't seen it in any other theme galleries. Before we test a shorter version, can we test removing it all together?

**Comment by Robertght** [comment]
It looks like the tooltip description from our themes look fairly ok in comparison to the third party ones.

Astra:

![Image](https://github.com/user-attachments/assets/abe2992f-d6c8-4c09-a6a6-bc246bdc7f4b)

Ours:

![Image](https://github.com/user-attachments/assets/eeefc361-6a7b-4727-852d-66cda1f86963)

![Image](https://github.com/user-attachments/assets/4eb71867-90a3-4c3d-a166-461d746e00f9)

@Automattic/t-rex I'm flagging this for your team and setting it as a low priority.

**Comment by dsas** [comment]
> @Automattic/t-rex I'm flagging this for your team and setting it as a low priority.

Thank you, but I don't think you need to flag this and add it to our board if it's a low priority :) Adding it to the Dotcom Marvel Maintenance should suffice and also means that any of the Marvel teams can find it and work on it.
