### ISSUE TITLE
Reader: make "in-stream" comment bubble more useful

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#974]
Raised by @shaunandrews 

When viewing your Reader stream, there's a handy comment count shown for posts that support it:

![screen shot 2015-11-29 at 11 03 37](https://cloud.githubusercontent.com/assets/1119271/11458166/ef7ab2e6-9688-11e5-842e-5bb69f9e2e6e.png)

Unfortunately, this icon doesn't do anything when you click on it—well, it opens the full post view, but it feels like it should do something else. The easy solution is to have it open the full post view and scroll down to the comments. But this has issues, since we don't load the comments instantly when the full post view is opened. Anyways, it feels a little weak. Here's a solution that I think makes it easier to read and post comments quickly, without needing to open the full post view:

![screen shot 2015-11-29 at sun nov 29 11 04 48 am](https://cloud.githubusercontent.com/assets/1119271/11458174/0d2e79d0-9689-11e5-9cc4-d550641d84d5.png)

Clicking on the comment bubble would open a popover with the comment list. For longer threads, the popover will have its own scrolling. Thoughts?

Notes from @blowery 

> One niggle with inlining comments: we don't currently have a way to load more than the first "page" of comments. Because of how comments work in the API, our first page is the most recent 10 replies and all their replies.
> 
> This isn't great for the comment list in either place, but i feel like it's especially weird here, as we can't use IS to load more comments, like we were potentially planning to do on the full post view. We'll need some kind of button to initiate the load. Probably a "load earlier comments" button at the top of the list?

Note from @shaunandrews 

> > Probably a "load earlier comments" button at the top of the list?
> 
> Ah yes, I recall exploring this earlier:
> 
> <img width="672" alt="screen shot 2015-09-14 at 11 12 15 am" src="https://cloud.githubusercontent.com/assets/191598/9853427/85fb3c2a-5ad1-11e5-91b5-c6d152857bde.png">

Additional discussion in 9911-gh-calypso-pre-oss but the notes above are the gist and the end result of the conversations to date.

**Comment by lizkarkoski** [comment]
#2726 was closed as duplicate, but this issue does not mention mobile view. Right now on mobile, clicking the comment icon does not do anything. Whereas on desktop it opens the single post view.

**Comment by blowery** [comment]
oldy-but-a-goody

**Comment by worldomonation** [comment]
Hi! I'm performing triage on older bugs as part of Quality Squad's efforts to cut down on backlog issue counts.

I tried on both Desktop and Mobile web versions and found that clicking on the Comment icon from Reader view did open up the article in question and scrolled down to the comments field. 

In light of this, I propose that this issue be closed as `Closed - Not Reproducible`.
