### ISSUE TITLE
Tag Page Headers: Credit text fugly in Safari

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9741]
Looks fine in Chrome, but in Safari...

![screen shot 2016-11-30 at 2 05 36 pm](https://cloud.githubusercontent.com/assets/24388/20773335/1ad506dc-b706-11e6-85e1-18cb2d6b0e31.png)

cc @jancavan

**Comment by jancavan** [comment]
@fraying: Tried adding `-webkit-font-smoothing: antialiased;` and changing the font-weight to 500 and it gets rendered better in Safari:

![screenshot 2016-11-30 15 31 12](https://cloud.githubusercontent.com/assets/4924246/20775872/0b784c2e-b712-11e6-8192-7365f7e8950e.png)

But with the properties applied to both browsers, the text becomes a bit thinner Chrome...

**Before (Chrome):**
![screenshot 2016-11-30 15 31 45](https://cloud.githubusercontent.com/assets/4924246/20775894/25b36e5c-b712-11e6-8d6e-300b910840cf.png)

**After (Chrome):**
![screenshot 2016-11-30 15 32 35](https://cloud.githubusercontent.com/assets/4924246/20775911/3a799bc2-b712-11e6-9b56-7e40707ac330.png)

Which isn't bad and it does make them more uniform, just that the default in Chrome is better.

**Comment by fraying** [comment]
@jancavan Nice! I think they both look better. Or, at least, good enough. Thanks for the screenshots.

**Comment by jancavan** [comment]
@fraying Created a PR for it: https://github.com/Automattic/wp-calypso/pull/9747

**Comment by bluefuton** [comment]
Fixed in #9747.
