### ISSUE TITLE
Fix having both Sites and Domains icons being shown as selected

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#97444]
When the feature flag is enabled and we open any domain, both the Sites and the Domains menu items on the left sidebar are selected. Only Domains icon should be selected.

![Image](https://github.com/user-attachments/assets/9663b44b-1163-49e8-b48c-f950b1ec7055)

**Comment by donnapep** [comment]
Lego will disable the feature flag in the dev environment, which will help. Continuing with resolving this issue.
