### ISSUE TITLE
"Publishing failed. An unknown error occurred" while publishing a blog post when account is not verified

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#97449]
### Quick summary

We see a "Publishing failed. An unknown error occurred" error while publishing a blog post when account is not verified. I found this while finding https://github.com/Automattic/wp-calypso/issues/97448

![Image](https://github.com/user-attachments/assets/639226dd-2a69-43f4-9019-53e7cc58ac0b)

### Steps to reproduce

- Create a new account and a new site as part of the flow: https://wordpress.com/start
- Don't verify account just yet
- Unaware of the account verification requirement, try publishing a blog post and you'd see the error

### What you expected to happen

That error needs to be clearer, that account verification needs to be completed first

### What actually happened

An error "Publishing failed. An unknown error occurred" occurs while publishing a blog post when account is not verified

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by ramonjd** [comment]
I've been trying to reproduce this and can't. 

1. Create a site with a branch new account
2. Do not verify the account by clicking on the link in the welcome email
3. Create a post and publish

My posts are always published 🤔 and my email address isn't verified. Am I missing steps?

**Comment by arunsathiya** [comment]
Thanks for testing @ramonjd. It's odd that you are unable to see the same behavior. The reproduction steps are sufficient. I can share a video recording of the issue in a while.

**Comment by ramonjd** [comment]
Thanks! Here's me having another go:

https://github.com/user-attachments/assets/0079a4e4-00f3-4523-9ba1-e5f666409aba

**Comment by arunsathiya** [comment]
It worked okay for me too. 

https://github.com/user-attachments/assets/9864e165-22a1-4268-8743-f7ac8d337225

I am not sure what changed between the time of original report and now. I'll close this for now, but we can reopen if there's more concrete reproduction steps.
