### ISSUE TITLE
Bug: Creating an account does not send the account verification email automatically

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-calypso#97448]
### Quick summary

Creating an account does not send the account verification email automatically. Currently, it needs to be manually initiated from https://wordpress.com/me

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/90c9d174-d6b0-4a09-8e29-1578fcb31d7e" />

### Steps to reproduce

- Start at https://wordpress.com/start
- Sign up with an email address, create a site, complete site setup
- At this point, you'd reach the dashboard but there's no indicator of account verification email being sent unless manually initiated from https://wordpress.com/me

### What you expected to happen

Account verification email is automatically sent out, without having to request manually.

### What actually happened

Account verification email needs to requested manually at https://wordpress.com/me

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by rcrdortiz** [comment]
Just went through the steps you mentioned on an incognito window. I'm getting the account activation email without needing to do anything else. Can you double-check if there's something on your side?

**Comment by arunsathiya** [comment]
Ugh, sorry about the trouble here, you are right. The activation email was misclassified in a hidden folder in my email account, due to an email filter. I was looking only at inbox and spam box earlier.

Everything is working as expected!
