### ISSUE TITLE
Feature Request: Make "WordPress Speed Test" badge text consistent across pages

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#97457]
### What

The text in the badge at the top of the page is different on the two pages.

| Landing page | Results page |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/d047461b-51e0-43ba-815d-4ec44d061694) | ![Image](https://github.com/user-attachments/assets/38699b3c-93e7-4471-8dff-29ff7b40ca5d) | 

### Why

This will reduce confusion when navigating between pages.

### How

Update the badge text to be the same across all pages.

**Comment by cpapazoglou** [comment]
I tacked the fix in https://github.com/Automattic/wp-calypso/pull/97506
