### ISSUE TITLE
Feature Request: Redirect to the "Create an account" page instead of "Log In"

### ISSUE THREAD

**Issue by gcsecsey** [Automattic/wp-calypso#97464]
### What

Currently, when clicking the CTA, users are redirected to the Log In page.

### Why

We discussed on the walkthrough that the "Create an account" page surfaces social login options more prominently. It also logs the user in if they already have an account.

### How

Update the redirection to use the "Create an account" page instead of "Log In"

**Comment by cpapazoglou** [comment]
I thought we can tackle this as a low hanging fruit.
