### ISSUE TITLE
Decision: "Skip to Dashboard"

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97469]
### Details

This issue is purely about the "Skip to Dashboard" link (not general skip behavior) 

<img width="910" alt="Image" src="https://github.com/user-attachments/assets/5a82c18f-ba24-4e0c-8b57-c7f47beadfca" />

There are essentially four choices for "Skip to Dashboard" on the Goals screen.    We can track which decision we are making for which milestone:

| Milestone | Skip to Dashboard  |
|--------|--------|
| Dec 20 | Remove the "Skip to Dashboard" link |
| EOY ship to customers | TBD, but likely keep it removed | 

## 1
* Remove the link.   (For a quick solution, then later bring it back.)

## 2
* Keep the link
* Action: skips to Account Screen
* Then move to Domains & Plans

## 3
* Keep the link
* Action: skips to Account Screen
* Then also skip Domains & Plans
  *   Give user free plan and default  *.wordpress.com subdomain
* Do not add anything to Launchpad, let the user find domains and plans UI

## 4
* Keep the link
* Action: skips to Account Screen
* Then also skip Domains & Plans
  *   Give user free plan and default  *.wordpress.com subdomain
* Add Domain and Plans tasks to Launchpad

### Checklist

- [ ]
- [ ]

**Comment by autumnfjeld** [comment]
@fditrapani   I documented our choices here for clarity.   

At the time of writing this, the decision is #1, remove the link.    

I realize this decision may change again. 😄

**Comment by fditrapani** [comment]
Thanks for creating this issue @autumnfjeld, my take from the call is that we go with #2 but with a little more detail:

- Keep the link: Add it to all the screens on the top right with the label "Skip setup".
- Action: skips to Account Screen and then move to Domains & Plans (Sounds good!)
- Remove the link from the bottom of the goals screen so it looks like this:
  ![Image](https://github.com/user-attachments/assets/2e0e0e1e-fa96-49db-9ee5-e000204e881c)

**Comment by autumnfjeld** [comment]
Let's keep this issue strictly about the "Skip to Dashboard" UI element
<img width="910" alt="Image" src="https://github.com/user-attachments/assets/b51f89c9-810a-4b9e-8e6c-9f3e32e6ced6" />


Which means we go with #1.  We don't show it.

We'll specify the top right Skip behavior in another issue. 😄

**Comment by fditrapani** [comment]
Sounds good — option 1 it is!

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/pull/97500
