### ISSUE TITLE
Tag Pages: De-cap the tag name in header

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9748]
Ok, this one's my bad. I'm sorry.

As pointed out by @bluefuton and @martinremy, there are too many tags where intercaps are required (not least of which is WordPress), so it'd be better to let all the tag headers be lowercase just to avoid the issue. At least, lowercase, they match the case used in the cards.

So, please remove the CSS that caps the first letter of the tag in the header of the tag pages. I'm sorry to see it, go, but....

**Comment by fraying** [comment]
How hard would it be to make a list of special case tag names? Like WordPress, iPhone, DevOps, etc...?

**Comment by blowery** [comment]
Not trivial. We need to build up the list, then add it to the API response, then teach everything to pick it up.
