### ISSUE TITLE
Me: validate email before saving, and show better notice when saving

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#975]
This issue happens on Me > Account Settings: https://wordpress.com/me/account

**Issue 1**: there is no validation for the email address - a user can save a bogus email like `eg@example.com1`

![screen shot 2015-11-29 at 11 10 20 am](https://cloud.githubusercontent.com/assets/11487924/11458215/e3aeaa66-9689-11e5-926e-c0a155c201a5.png)

**Issue 2**: when an email is saved, a success message is shown, even though the email change does not take place right away. Instead, the user must confirm the change from the new email address. We should display a pending (yellow?) notice instead that says something like

"We got your new email, but it still needs to be confirmed. Please check your inbox at <new email> for a confirmation link."

![screen shot 2015-11-29 at 11 13 35 am](https://cloud.githubusercontent.com/assets/11487924/11458237/41100768-968a-11e5-8181-8d5498d0a2d7.png)

**Comment by v18** [comment]
There is already some validation done for the email (for example - when the '@' is missing). In that case the user sees this error message:

![](https://cloud.githubusercontent.com/assets/11487924/11319221/824eebd4-903d-11e5-8b01-ffa5b97f6be0.png)

Instead, we should:
1. Display a more specific error message
2. Display the message inline - before the user attempts to save the new email

**Comment by v18** [comment]
This is related to #685 - a suggestion for how to improve email update process

**Comment by ebinnion** [comment]
I believe this is being address by @enejb in #1472.

**Comment by ebinnion** [comment]
@enejb added validation before saving an email address in #1472. Let's create a separate issue to track better error message when a setting fails to save.
