### ISSUE TITLE
Replace Calypso "Custom Post Type" screen with the standard WordPress one

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#97524]
As part of the Untangling Calypso epic, let's remove the custom implementation of the wordpress.com/types/:postTypeSlug/:siteSlug view, in lieu of the standard WordPress /wp-admin/edit.php?post_type=:postTypeSlug view—for all users.

This will keep everything consistent with the other changes within the project.

There shouldn't be any links to these CPT views in the menu, so no changes to navigation are required.

Requirements

 * Visiting wordpress.com/types/:postTypeSlug/:siteSlug redirects to /wp-admin/edit.php?post_type=:postTypeSlug if you are part of the experiment treatment group

**Comment by mmtr** [comment]
Is this not the same as https://github.com/Automattic/wp-calypso/issues/96183?

**Comment by dsas** [comment]
> Is this not the same as https://github.com/Automattic/wp-calypso/issues/96183?

No. That issue redirects specific CPTs, Jacopo would like us to tackle the generic case too, for consistency. Even though it's doubtful that anyone is ever visiting them because so far as I know we never ever generate links for them :).

**Comment by mmtr** [comment]
> tackle the generic case too

I think we already did that? 

https://github.com/Automattic/wp-calypso/blob/860e3eea3eb8631aebc7b5455436a8059c4cceba/client/my-sites/types/index.js#L16

We currently redirect all the `/types/:type` routes, not only Testimonials/Portfolio.

**Comment by dsas** [comment]
Oh yeah! I must have made a mistake while testing the other day. Thank you @mmtr
