### ISSUE TITLE
Task: Persist `styleVariation` and `globalStyles` on site creation

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/wp-calypso#97550]
Follow-up of https://github.com/Automattic/wp-calypso/issues/97208

From [this discussion](https://github.com/Automattic/wp-calypso/issues/97208#issuecomment-2548317581), we want to persist `styleVariation` and `globalStyles` on site creation after choosing that from a theme like `Sunderland`

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/wp-calypso/pull/97552

**Comment by paulopmt1** [comment]
We're saving [the store data here](https://github.com/Automattic/wp-calypso/pull/97552) and have code in place [to persist it on backend](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/site-setup-flow.ts#L711-L724) after the checkout.
