### ISSUE TITLE
Back button on design step

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#97579]
And maybe more parts of the flow, e.g. I think the domains step goes back to /sites

**Comment by p-jackson** [comment]
This adds "Back" from the signup step https://github.com/Automattic/wp-calypso/pull/97627

This adds "Back" from the domains step https://github.com/Automattic/wp-calypso/pull/97592

**Comment by lsl** [comment]
I ran through the flow end to end, every back button I could find works as expected now.
