### ISSUE TITLE
Task: Gracefully continue the flow if the user leaves checkout

### ISSUE THREAD

**Issue by zaguiini** [Automattic/wp-calypso#97571]
### Details

It's currently failing:

![Image](https://github.com/user-attachments/assets/c32b842b-3f44-4209-aceb-178c62941a97)

**Comment by autumnfjeld** [comment]
We want to gracefully handle this, but we shouldn't redirect to the DP.
Let's keep consistency with this discussion: p1734461517368039/1734432996.311899-slack-C085HCWCEDN
