### ISSUE TITLE
Jetpack Stats show - for subscribers

### ISSUE THREAD

**Issue by dzver** [Automattic/wp-calypso#97601]
### Quick summary

The subscribers stats no longer includes the starting date of each subscription

### Steps to reproduce

1. On a site that has any subscribers, go to https://wordpress.com/stats/subscribers/[SITE]

### What you expected to happen

See dates

### What actually happened

Saw "-"
<img width="503" alt="Image" src="https://github.com/user-attachments/assets/4f10bd95-25a0-4a28-88ab-c2955f42bdfe" />

The followers endpoint returns the dates but they are not visualized.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Confirming that something in https://github.com/Automattic/wp-calypso/pull/97289 causing this.

**Comment by simison** [comment]
Fix in https://github.com/Automattic/wp-calypso/pull/97700
