### ISSUE TITLE
Plugins page sidebar may obscure content

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#97614]
### Quick summary

On some viewport widths, the content of the plugins page displays below the sidebar.

![Image](https://github.com/user-attachments/assets/7fd56cfe-02da-4831-bcd2-fadaecf3ff41)

### Steps to reproduce

1. Visit `https://wordpress.com/plugins/{{ SITE }}`
2. Ensure the sidebar is open and visible
3. Change the window size until the bug is triggered

### What you expected to happen

The content should be next to the sidebar, not under.

### What actually happened

Content is obscured.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by epeicher** [comment]
I am able to reproduce this on the Arc browser by hiding and enabling the sidebar

![Image](https://github.com/user-attachments/assets/d80aac75-5ad4-436e-bd52-e9080a3b4f99)

**Comment by Robertght** [comment]
I was able to replicate this too, however, it seems to involve the "Collapse menu" button more often than not:

[link]()

Another bug that I discovered is that the sidebar is not scrollable if you're on the Plugins page so you can't go past the "Templates" section from the video. You have to either increase the height of the window or access another section.

@epeicher is this something Groundskepeing can work on or should we ping another team?

**Comment by epeicher** [comment]
Thanks @Robertght, for the video with some additional detailed steps! To add more context, which Browser were you using?

I think this task can be tackled as part of the Groundskeeping

**Comment by Robertght** [comment]
Chrome  131.0.6778.140

**Comment by epeicher** [comment]
Thanks! It reproduces consistently in Chrome by opening this URL https://wordpress.com/plugins/<site-url> in a viewport of 1146px. Working on it.

**Comment by epeicher** [comment]
This PR introduced the changes that make this fail https://github.com/Automattic/wp-calypso/pull/93505
