### ISSUE TITLE
Disambiguate the sources for rec clicks for tracks

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9762]
Add a bit of context to rec tracking so what we can track when a rec was clicked (to fullpost) and when a follow comes from a rec.

(As discussed with @blowery and @martinremy)

**Comment by samouri** [comment]
tldr: we need to be able to differentiate between:
1. in-stream recs
2. empty search page recs
3. full-post recs

**Comment by samouri** [comment]
now that #9864  is merged, we can fully disambiguate the source of recs that were _clicked_.
Sadly, _following_ is not as much a first class citizen in terms of knowing _from where_ the follow came. 

Currently, we only know from which page a follow came, but not from which kind of post.  This only has a real effect in one place:
 - we cannot distinguish between follows made on search results + search page recommendations]


We can close this issue when we can distinguish between whether a follow came from a search result vs. a search rec.
