### ISSUE TITLE
Classic Themes & Site Editor: remove "Launch banner" from site preview for unlaunched and Coming Soon sites

### ISSUE THREAD

**Issue by jartes** [Automattic/wp-calypso#97648]
### Quick summary

[Gutenberg 19.9 introduced](https://make.wordpress.org/core/2024/12/18/whats-new-in-gutenberg-19-9-19-december/#style-book-in-classic-themes) the new `Design` screen where you can see the Style Book for classic themes. On Dotcom, when a site is not launched or is in the Coming Soon mode, the Launch Bannes is displayed. And it doesn't work.

### Steps to reproduce

1. On a Simple or Atomic site, activate a classic theme like "Twenty Seventeen".
2. Use the 19.9 of Gutenberg as explained on pdtkmj-3dr-p2.
3. Go to Appearance → Design (or Patterns). 
4. Ensure you are on the Site Editor main home: `/wp-admin/site-editor.php`
5. Check the site preview

### What you expected to happen

See the site preview without the Launch Banner

### What actually happened

The Launch Banner is displayed on the site preview: 

![Image](https://github.com/user-attachments/assets/67080f9d-8150-4a04-ae47-059381f9bf67)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by fushar** [comment]
This is fixed in Simple and Atomic edge sites running GB 19.9.
