### ISSUE TITLE
Virtual themes are all marked as active in the Design Picker and can't be selected

### ISSUE THREAD

**Issue by candy02058912** [Automattic/wp-calypso#97643]
### Quick summary

1. The user picked a virtual theme (Link in Bio) during onboarding
2. User lands in launchpad with a "Select a design" task
3. Click on "Select a design" to see the Design Picker again

If user would like to select a different virtual theme at this point, it wouldn't be possible as all of them are marked as active.

![Image](https://github.com/user-attachments/assets/327f605f-43e9-4a88-bcfb-1e0514cbda9d)

### Steps to reproduce

1. Onboarding at /start
2. Select a free wordpress.com domain
3. Start with free on plans page
4. Pick any goal
5. Select Link in Bio category in the Design Picker and pick a theme prefixed with Link in Bio:
6. In the Launchpad click on "Select a design"
7. In the Design Picker select Link in Bio category

You'll see all the Link in Bio: themes marked as active

### What you expected to happen

I can select another Link in Bio theme.

### What actually happened

I cannot select another Link in Bio design.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

User can pick the design after exiting the launchpad.

**Comment by Robertght** [comment]
I managed to replicate this on the platform as well.

I'm raising this as a high-priority and pinging @Automattic/t-rex about it.

**Comment by arthur791004** [comment]
I don't think there is a way to check whether the current design is a virtual theme... Maybe we have to disable this feature for all virtual themes.

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/wp-calypso/pull/97682 to disable the active theme feature for virtual themes on the Design Picker screen.

**Comment by paulopmt1** [comment]
Thanks to @arthur791004, we landed a [good fix for it](https://github.com/Automattic/wp-calypso/pull/97682) super quickly, which was great!

> I don't think there is a way to check whether the current design is a virtual theme.

Ideally we want to show the selected theme, even being a virtual one. 
Can you expand more on why it's not possible @arthur791004?

**Comment by dsas** [comment]
Something somewhere will have a `selectedDesign` prop, this will have a `recipe.slug` which uniquely identifies a virtual theme. Each DesignCard will already have a `design.recipe.slug`, so **_if_** you can get the selectedDesign to it, it can compare them to find the active one.

**Comment by arthur791004** [comment]
> Ideally we want to show the selected theme, even being a virtual one.
> Can you expand more on why it's not possible

The virtual theme is a based theme + preselected patterns. When users activate a virtual theme, we just switch theme to the based one and update their homepage with the preselected patterns. So, we won't have any information to know whether the active theme is a virtual one and whether it's the same as a specific virtual theme.

> Something somewhere will have a selectedDesign prop, this will have a recipe.slug which uniquely identifies a virtual theme. Each DesignCard will already have a design.recipe.slug, so if you can get the selectedDesign to it, it can compare them to find the active one.

I don't think we can use the selectedDesign since
* When you preview a design, we'll update the selectedDesign
* The selectedDesign may not equal to the active theme

**Comment by arthur791004** [comment]
Closing it as it's fixed by https://github.com/Automattic/wp-calypso/pull/97682. We can open another issue to triage how to mark a virtual theme active if we want.
