### ISSUE TITLE
Omit Recs that don't have excerpts

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9767]
As discussed with @gibrown, we should not be sending post recs that do not have excerpts. It's a bad experience and they're unlikely to get clicked.

**Comment by gibrown** [comment]
@aaronyan is working on an A/B test that filters on content length

**Comment by fraying** [comment]
Hooray for testing! I'm all for testing. But this is a bug, really. We should not be showing recommendations that do not have excerpts. If we can fix this bug now, please, let's just fix the bug now. No need to test it. Let's test other things. cc @aaronyan @gibrown

**Comment by aaronyan** [comment]
Sounds good. We will be requiring content length of a minimum size on all of our Recs.
