### ISSUE TITLE
Task: Launchpad task "Select a design" should lead to the correct version of the Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97717]
### Details

Flows from the Launchpad should have a compatible UI experience: : pass variables from the LP to the Design Picker to indicate the flow (flow = onboarding , not update-design) to render the correct version of the Design Picker.

See p1734703861594629/1734703386.072169-slack-C085HCWCEDN

### Checklist

- [ ] 
- [ ]

**Comment by candy02058912** [comment]
This one is done after merging https://github.com/Automattic/wp-calypso/pull/97734
