### ISSUE TITLE
Jetpack Stats: post list opens old screen instead of new one

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#97736]
When opening stats for a post from wp-admin version of post list for a simple site, it opens an old screen:

<img width="1872" alt="Image" src="https://github.com/user-attachments/assets/115283ef-1ac4-4e32-8150-0a4fca4d9359" />

<img width="1871" alt="Image" src="https://github.com/user-attachments/assets/9dc62600-0e91-4e00-b02c-233082b8eb67" />
 
Works as expected in Jetpack self hosted wp-admin so seems to be just WP.com issue.

The link should open modern stats screen for the post:

<img width="1852" alt="Image" src="https://github.com/user-attachments/assets/d6144907-ff4b-433a-bbad-13413ccfc82b" />

**Comment by fushar** [comment]
Fixed via 169318-ghe-Automattic/wpcom
