### ISSUE TITLE
Randomize Recs

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9779]
We should randomize recs (in stream and search page). Seeing the same recs in the same order over time is a bummer (and will encourage dismissing when it's available).

ccing @blowery and @gibrown to discuss where to do it (front or api)

**Comment by aaronyan** [comment]
Greg and I talked about potential solutions and we came up with this:

How about the client provide a seed in the API request and we will return posts accordingly? That way, we won't have problems paging given the same seed.  And the client will get to choose when to scramble the results.

**Comment by bluefuton** [comment]
Fixed in #9881.

**Comment by samouri** [comment]
@bluefuton how are you so quick!
