### ISSUE TITLE
Create the manage DNS records page

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#97798]
Create page for managing DNS records

<img width="1565" alt="Image" src="https://github.com/user-attachments/assets/3dd08edd-cc55-49b7-9d4e-732bb1e88d24" />

**Comment by bogiii** [comment]
@Imran92, Isn't it already done here: https://github.com/Automattic/wp-calypso/pull/97673?

**Comment by Imran92** [comment]
Ah right, closing it
