### ISSUE TITLE
Reader: scope generic tags for Reader content only

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#978]
Raised by @MichaelArestad 

The other day I removed some extra element styles that were unused, but @blowery made a good point that Reader content might use them (10389-gh-calypso-pre-oss). We should keep them, but scope them to reader content. There is no reason for us to be using these elements for styling including elements like `em` and `strong`. There are definite benefits from removing global element styles to prevent cascading and unexpected styles.

List of elements to remove from a global scope and add to reader content only:
- [ ] `hr`
- [ ] `p` (will probably break many things)
- [ ] `ul`, `ol`
- [ ] `dt`, `dd`
- [ ] `b`, `strong`
- [ ] `dfn`, `cite`, `em`, `i`
- [ ] `blockquote`
- [ ] `address`
- [ ] `pre`
- [ ] `code`, `kbd`, `tt`, `var`
- [ ] `abbr`, `acronym`
- [ ] `mark`, `ins`
- [ ] `small`, `big`
- [ ] `figure`
- [ ] `table` (debatable)
- [ ] `th` (debatable)

CC @shaunandrews

**Comment by bluefuton** [comment]
Reader now scopes any generic styles in full post to `.reader-full-post__story-content`:

https://github.com/Automattic/wp-calypso/blob/20b63c670ec36b29a593798ad0d1ef5c0a4a531a/client/blocks/reader-full-post/_content.scss
