### ISSUE TITLE
Tag Headers: Use same tag format as in cards

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9781]
In cards, we're using different display text than we're using in the tag header. Note the difference between "higher-education" in the header and "Higher Education" in the card below.

![screen shot 2016-12-01 at 2 47 15 pm](https://cloud.githubusercontent.com/assets/24388/20816051/4e6f4dde-b7d5-11e6-931f-30cd7cbaaaea.png)

https://wpcalypso.wordpress.com/tag/higher-education

So, question: Can we use the same format in the header as in the cards?

**Comment by fraying** [comment]
@blowery But we *can* use whatever we're using in the card, right? My goal was just to get them to match.

**Comment by samouri** [comment]
I guess we could remember what they clicked..

Aka:
1. user clicks tag hiGHER education
2. we present it as hiGHER education on the tag header for the user this instance

There would be strange side-effects like:
1.  If they send one of their friends to the same url the title would appear differently for them which wouldn't be good 🤔 
2. if they get to the same url via a different method the title will appear differently
