### ISSUE TITLE
"Add forward" button takes user to legacy screen

### ISSUE THREAD

**Issue by Imran92** [Automattic/wp-calypso#97821]
The add forward button in the forward email list page in revamped flow takes to the legacy screen instead of the revamped one

<img width="1565" alt="Image" src="https://github.com/user-attachments/assets/570a71ce-f019-4378-a5f9-7e6fce7aa6b6" />

**Comment by bogiii** [comment]
I can not reproduce this issue. @Imran92, could you let me know if you have the feature flag turned on?
