### ISSUE TITLE
Search default: names/avatars misaligned

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9783]
![screen shot 2016-12-01 at 3 40 42 pm](https://cloud.githubusercontent.com/assets/24388/20817447/a3e8e14c-b7dc-11e6-8b73-76a9a2b2e8d5.png)

cc @jancavan, who probably knows this already

**Comment by jancavan** [comment]
This always happens because even though we reuse components, we have custom positioning set on gravatars :( I'll fix it.
