### ISSUE TITLE
Reader: prevent autoplay for our audio shortcode

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#980]
Raised by @blowery 

Looks like autoplay's for our own audio shortcode slip through.

This is because we're not checking `<audio>` tags when changing autoplay attributes. Probably need to alter those, along with `<video>` elements

Reported in 665240-f

**Comment by blowery** [comment]
Test post showing the issue https://wordpress.com/read/post/feed/25320833/877160808

**Comment by blowery** [comment]
We just need to strip autoplay attributes on audio and video elements in `client/lib/post-normalizer`
