### ISSUE TITLE
Editor: Pages not showing Links when you click on "Preview", but they are Published properly.

### ISSUE THREAD

**Issue by dromero20** [Automattic/wp-calypso#9815]
You can't Preview the links posted on Pages but you can publish them perfectly. Once the page is published, you can "Preview" them properly.

Screenshots of the editor:

![srxlqlgyjj-3000x3000](https://cloud.githubusercontent.com/assets/426388/20880272/954f8cf0-bad7-11e6-87a5-de9723cf0fea.jpeg)

When you click on Preview, you'll see this:

![42qtv8dfmx](https://cloud.githubusercontent.com/assets/426388/20880275/9d966e06-bad7-11e6-9f57-792ce158e307.jpg)

I've tried to reproduce the issue on my test site by using the same Theme, but I can't replicate the problem.

![yzrhmol4re](https://cloud.githubusercontent.com/assets/426388/20880288/a861fefe-bad7-11e6-9143-1015e51a7bdb.jpg)

When I click on "Preview", I can see my link perfectly.

![_j8bkfzrxs](https://cloud.githubusercontent.com/assets/426388/20880300/b33da968-bad7-11e6-8abf-8eeed58cc1f0.jpg)

#### Steps to reproduce:

1. Log in to WordPress.com
2. Edit the page set up as home page.
3. Add a link below the existing content.
4. Try to preview the changes before updating.

If you add a link by editing his Posts, it previews the link properly. So it's related only to Pages.

<hr />

Reported in 535971-chat. Blog ID 117044761
How urgent is this? Not quite urgent.

#manual-testing

**Comment by lancewillett** [comment]
I can't reproduce this, either. My guess is maybe the URL wasn't valid, or the editor didn't create the link correctly so the preview ignored it. Could also be Custom CSS or some other thing happening on the front-end of the site.
