### ISSUE TITLE
Sharing on Jetpack sites: Reblog should not appear

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9816]
Reblog buttons are not supported on Jetpack sites. However, the Reblog option still appears when loading https://wordpress.com/sharing/buttons/ for a Jetpack site.

1. It first appears when loading the page, and then disappears.
2. It also appears in the Likes settings section title.

![screen recording 2016-12-05 at 11 32 am](https://cloud.githubusercontent.com/assets/426388/20881904/d4e91e9c-bade-11e6-95bd-690be6091cfe.gif)

**Comment by lancewillett** [comment]
I saw this one today during a #dogfooding session on a Jetpack-connected site. I was editing Sharing settings and was surprised to see the "Reblog and Like" setting label when I was pretty sure Jetpack sites don't have reblogging capabilities.

**Comment by tyxla** [comment]
I'm tackling this as part of the final Jetpack Settings v1 sprint, as it's very closely related with #12386.

#16501 tackles the necessary title changes for Jetpack sites.
#16502 updates the placeholder to remove the Reblog button.
