### ISSUE TITLE
Checkout: incorrect notice shown after mapping domains already using our name servers

### ISSUE THREAD

**Issue by ranh** [Automattic/wp-calypso#9818]
After adding a domain mapping, we seem to always show this notice, regardless of the actual state of the domain:

![ranimac3 screenshot 2016-12-05 at 12 50 41](https://cloud.githubusercontent.com/assets/426518/20882568/4e12029c-baea-11e6-9918-07c99093a399.png)

This notice is only relevant when the domain is not already using our name servers. If the domain is already correctly set up before mapping it, the notice is incorrect and confusing. This may happen if users read our [docs for domain mapping](https://en.support.wordpress.com/map-existing-domain/) and make the necessary settings in advance, if their domain was set up automatically to use WordPress.com name servers by get.blog, if the domain was already mapped to a WordPress.com site in the past and the name servers were never changed, or for other reasons.

We should only show this notice when the domain is not already correctly configured to work with WordPress.com. 

#### Steps to reproduce
1. Have a domain that is set to use WordPress.com name servers and that is not already mapped to WordPress.com.
2. Add domain mapping for this domain.
3. After paying, you will see a notice like the one above.

**Comment by scruffian** [comment]
@aidvu raised some concerns with this approach. The name servers returned by the API will be inaccurate if they have recently been changed. On top of this, simply having name servers pointing to WordPress.com isn't enough, we need to do other checks to make sure that the domain works. We should invest some time into working out a better way to determine if the domain will already work or not.

**Comment by fabianapsimoes** [comment]
I don't think this change is worth the amount work we're discussing here. I've explored a bit changing the Thank You page for users coming from the `getdotblog` flow, but I don't like the idea of introducing get.blog-specific code to Calypso. I'm closing this one as a won't fix -- cc @breezyskies.

**Comment by ranh** [comment]
@fabianapsimoes Did you mean to close this issue or the PR #9950? 

This issue is for a bug in Calypso, it's not related to get.blog. Keeping it open for now.

**Comment by aidvu** [comment]
@ranh Same comments as on the `getdotblog` specific issue. I'd rather change the wording than depend on NS propagation at the time of mapping/registration. The accuracy of the result wouldn't be 100% true. We have DNS checks in the `Domains` module anyway, that do exactly what you're asking.

**Comment by ranh** [comment]
@aidvu Here is a more "generic" version of the above copy that may be less confusing for users who don't need to make NS changes:

> Thanks you for your purchase!
>  
> Your domain example.com was added to your site. It may take a little while to start working – see below for more information.
>  
> Your domain example.com has to be configured to work with WordPress.com. If you already did this yourself, or if the domain was already configured for you, no further action is needed. 
> 
> If not, you will need to log into your registrar’s site (where you purchased the domain originally) and change the “Name Servers” to:
>  
> > ns1.wordpress.com
> > ns2.wordpress.com
> > ns3.wordpress.com
>  
> Once you make the change, just wait a few hours and the domain should start loading your site automatically.
>  
> Button: Learn more

**Comment by aidvu** [comment]
PR here: https://github.com/Automattic/wp-calypso/pull/10208

**Comment by klimeryk** [comment]
Fixed by https://github.com/Automattic/wp-calypso/pull/10208
