### ISSUE TITLE
Reader: check if ReactCSSTransitionGroup behaves well

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#982]
Raised by @gwwar 

> In some components ReactCSSTransitionGroup may leave transition css classes on elements in IE11. Search for usages of ReactCSSTransitionGroup and swap out with TimeoutTransitionGroup if needed.

Note from @aduth 

> Related: In React 0.14, ReactCSSTransitionGroup now accepts an explicit timeout value, which is a more reliable means to determine when the transition ends. See https://github.com/facebook/react/pull/4561 and [Animation docs](https://facebook.github.io/react/docs/animation.html)

**Comment by blowery** [comment]
Depends on getting us to React 0.14.

**Comment by ockham** [comment]
Closed by #2041.
