### ISSUE TITLE
Customizer: Add indicator when additional widget areas are hidden

### ISSUE THREAD

**Issue by chad1008** [Automattic/wp-calypso#9822]
In the Customizer the only widget areas available are the ones visible on the currently loaded page. Accessing other widget areas requires navigating to a page where the user can see the missing widget area.

While this makes sense, it's sometimes confusing for users - they see only that the widget area they need is missing.

A note indicating there are other widget areas are available, and they the user can change pages to see them might ease this part of the flow a bit.

[Example forum thread](https://en.forums.wordpress.com/topic/edin-missing-sidebar-widget?replies=8)

**Comment by folletto** [comment]
That's interesting for Core! Is there a matching ticket there? :)

**Comment by chad1008** [comment]
[There is now](https://core.trac.wordpress.org/ticket/39087#ticket) :)
