### ISSUE TITLE
Checkout: /checkout shows nothing

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#9842]
## Issue

Landing on [wordpress.com/checkout](https://wordpress.com/checkout) shows no content.

<img width="749" alt="checkout" src="https://cloud.githubusercontent.com/assets/4335450/20998739/1ee4d716-bd64-11e6-984a-527be80e4b15.png">

😕

As you'll see from the image, this is in prod. I guess that this is a bit of an edge case since there will be no linking to /checkout but it would be great to see this handled in some way.

**Comment by lancewillett** [comment]
Agreed, this would be a UX dead-end if someone types it in. Should it redirect to /plans maybe?

**Comment by spen** [comment]
@lancewillett plans seems sensible, should be an easy fix - I'm happy to get a PR up in the next couple of days :)
