### ISSUE TITLE
Business users can't activate premium themes 

### ISSUE THREAD

**Issue by cecilerainon** [Automattic/wp-calypso#9844]
As reported by trial HE Hadrien Thine, Business users can't activate premium themes.

Here is how it can be reproduced with a Business plan:

1. Go to https://wordpress.com/design/premium/siteonbusinessplan.wordpress.com
2. Click on a theme/"Info"
3. You'll get to the theme's landing page
4. Click on _Pick This Design_
5. Nothing happens (and there's nothing in the console)

#### What I expected

To be able to go through and activate the theme

#### What happened instead

Nothing when I click the button

#### Browser / OS version

Tried several browsers and the result is the same, so it's not browser specific

#### Screenshot / Video

https://cloudup.com/cP3bTBQPlA3

**Comment by folletto** [comment]
Woah. Thank you, that's bad. We'll look into it!

**Comment by ockham** [comment]
@cecilerainon Thanks for reporting, should be fixed now. If it isn't, let us know!

**Comment by cecilerainon** [comment]
Worked on my test site, thanks! 🎉
