### ISSUE TITLE
Framework: WebPreview should resize full width on wide desktop views (Themes, Editor, ...)

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#9846]
#### Steps to reproduce

1. go to a theme's details, i.e. to a URL like http://calypso.localhost:3000/theme/THEME_NAME/SITE_URL
2. resize browser to be ~1140px wide
3. click "Open Live Demo"

#### What I expected

I expected the theme preview to fit into the browser window. 

#### What happened instead

The theme preview did not fit into the browser window. 

#### Browser / OS version

Safari / Chrome on macOS 10.12.

#### Screenshot / Video

<img width="1140" alt="screen shot 2016-12-06 at 1 45 07 pm" src="https://cloud.githubusercontent.com/assets/23619/20926107/09a04b38-bbbb-11e6-9167-1ed18927656d.png">

**Comment by folletto** [comment]
Ref: quick link to test this → https://wordpress.com/theme/ixion

This isn't a theme-level choice, this is a design choice we did on the preview component. It applies everywhere the desktop size is picked and we use `WebPreview` (i.e. posts/pages preview too, site preview too).

I wouldn't as such categorize this as a bug, but we can have a discussion on WebPreview behaviour. :) 

Visual reference:

![screen shot 2016-12-15 at 13 48 28](https://cloud.githubusercontent.com/assets/4389/21226391/32245b1c-c2cd-11e6-966d-432651ea0497.png)
![screen shot 2016-12-15 at 13 48 29](https://cloud.githubusercontent.com/assets/4389/21226392/33af572a-c2cd-11e6-8531-2cfac38c5f39.png)
![screen shot 2016-12-15 at 13 48 31](https://cloud.githubusercontent.com/assets/4389/21226395/35f5e3fa-c2cd-11e6-9d7e-229a0048408c.png)

**Comment by folletto** [comment]
The preview window seems cut only in a range of resolutions, which is why I didn't notice it before. Specifically, on Chrome, I see it between ~1248px and ~962px.

**Comment by lsinger** [comment]
I didn't get a notification for the first comment, only for the second one. 

Half of the "activate" button is hidden for me, which felt very unintentional to me, which is why I categorized it as a bug. 

Can I help any further with this?

**Comment by folletto** [comment]
Just needs to be debugged and fixed I guess, happens on everything that uses the `WebPreview` component it seems.

**Comment by lsinger** [comment]
Can't reproduce anymore — closing.
