### ISSUE TITLE
Reader: repeating featured image

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#985]
Sometimes the featured image appears twice in a row.

Raised by @ebinnion 

![screen shot](https://cloud.githubusercontent.com/assets/1126811/10954289/1fe3bba6-8312-11e5-98d9-480dfb260420.png)

<sup>Seen at https://wordpress.com/read/post/feed/4734485/854116085</sup>

Note from @blowery 

> Yeah, this is a pain. We detect when the feature is in the body of the post, but sometimes the feature, while the same logical image, is a different crop or upload altogether. I would bet the two images in this report have different URLs.
> 
> When that happens, there's not much we can do.

**Comment by blowery** [comment]
Verified that we're trying to suppress the feature when we think it's the same image. Closing because there's no good solution to this problem currently.
