### ISSUE TITLE
Reader: Loading placeholders need to match content

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9852]
Loading placeholder currently looks like this for every single post:

![screenshot 2016-12-06 09 17 48](https://cloud.githubusercontent.com/assets/4924246/20935763/ea49730c-bb94-11e6-840d-2bc8964e2d3d.png)

The content (that have thumbnails) being loaded doesn't match it:
![screenshot 2016-12-06 09 17 44](https://cloud.githubusercontent.com/assets/4924246/20935770/f4dd5b76-bb94-11e6-9f7e-ec353d3282d1.png)

**Comment by fraying** [comment]
Note that the "post about" button is a rarity, so ignore that for the placeholder. (Obvs.)

**Comment by bluefuton** [comment]
We generally don't know the post type until well after we've rendered the placeholder - it is only shown while we're waiting for the post object to load. This means that we have to choose a generic placeholder to cover all cases unfortunately.
