### ISSUE TITLE
Safari Bug with YouTube Fullscreen Mode

### ISSUE THREAD

**Issue by fraying** [Automattic/wp-calypso#9857]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com
2. Find a video post.
3. Click the thumb to start the video.
4. Once video is playing, click the fullscreen icon (bottom, right)

#### What I expected

Video to show fullscreen and continue playing.

#### What happened instead

Video shows fullscreen briefly, then disappears and you're back to the Reader, scrolled up.

#### Browser / OS version

Safari Version 10.0.1 / macOS 10.12.1

#### Screenshot / Video

[safari-fullscreen-bug.mov.zip](https://github.com/Automattic/wp-calypso/files/634855/safari-fullscreen-bug.mov.zip)

**Comment by fraying** [comment]
I just testing this again and it worked, so it's an intermittent Safari bug.

**Comment by samouri** [comment]
@fraying I tested it out on my laptop as well (in safari) and also couldn't repro

**Comment by fraying** [comment]
Closing since we can't repro.
