### ISSUE TITLE
Reader: Search bar/suggestions cropped and missing clear button

### ISSUE THREAD

**Issue by jancavan** [Automattic/wp-calypso#9861]
In narrow widths:

1. Search bar is being cropped
2. The clear (x) button is missing when you type in a search term

![screenshot 2016-12-06 16 15 08](https://cloud.githubusercontent.com/assets/4924246/20949648/531c9c44-bbcf-11e6-9b48-c533e168d2ca.png)

**Comment by samouri** [comment]
Note: I don't think the X is missing, its just cropped!

**Comment by samouri** [comment]
I tested out a few things, and I don't think this is actually cleanly possible in CSS.  Dynamically setting the width of a `position: fixed` object is tricky!

**Comment by samouri** [comment]
Fixed in #9889
