### ISSUE TITLE
Reader: Vevo videos not playing

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#987]
Raised by @ebinnion 

I scrolled through the reader today and noticed that the videos for https://wordpress.com/read/post/feed/18743358/864952576 were just rendering a grey square.

![screen shot 1](https://cloud.githubusercontent.com/assets/1126811/11192609/a908ed6c-8c67-11e5-9877-6de5b38fdd6c.png)

When I opened up the console, it mentioned: `Blocked script execution in 'data:text/html,chromewebdata' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

That post is on Time.com: http://time.com/4114639/justin-bieber-purpose-video/

I'm not sure if this issue is happening for all videos, or just the Vevo player that Time.com is using.

Notes from @blowery 

> We rewrite all embeds to https, no matter what the source used. This usually works, but in this case, vevo is using a URL that doesn't pass normal SSL checks (the cert is for $someedge.akamai.com, not cache.vevo.com). I tried rewriting to scache.vevo.com, which appears to be the secure hostname counterpart, but it also doesn't work. The iframe embeds and the script loads, but the player is just blank.
> 
> Vevo doesn't have an SSL cert for cache.vevo.com.
> 
> https://cache.vevo.com/assets/html/embed.html?video=USUV71503356

**Comment by alisterscott** [comment]
The post links not longer work, and I can't find a post that has an embedded Vevo clip (that isn't on YouTube), so I'm closing this out for now.
