### ISSUE TITLE
Reply to comment notification pops up different notification after sent

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-calypso#9897]
#### Steps to reproduce
1. Find any comment notification.
2. Click it to bring it up in the left panel.
3. Reply to the comment notification and submit it.

#### What I expected
The focus should be set back to the comment I replied to or dismiss the second panel and go back to the primary.

#### What happened instead
The notification above or below (typically below) is selected and shown. The replied gridicon is not show immediately afterwards on the notification I did reply to.

#### Browser / OS version
Safari 10.0.1, macOS 10.12.1 (but this bug has been around for some time - I keep forgetting to report it)

#### Screenshot / Video
![2016-12-08_06-42-19](https://cloud.githubusercontent.com/assets/373903/21010596/925c5e6e-bd12-11e6-87f3-735e5cff2633.png)

#### Context / Source
#dogfooding

**Comment by lancewillett** [comment]
I think this should go in our notifications repo since it's not specific to Calypso — also, could be intentional behavior.

Moved to 613-gh-notifications-client
