### ISSUE TITLE
Follow Management: Crazy follow/unfollow site shenanigans

### ISSUE THREAD

**Issue by aerych** [Automattic/wp-calypso#99]
This was a fun one.. From the list management screen I followed “danroundhill.com”. I opened up the site page in the reader and unfollowed there. (https://wordpress.com/read/blog/id/4836651)
Back on the management screen I’m still shown as following so I toggled open the follow options, toggled on email, and choose weekly.  I refreshed the reader page and noticed I’m once again following the blog.  I refreshed the management page and while I’m still shown as following, my subscription options are toggled off. 

Not sure what the bug is but the behavior is pretty weird. (tho I can't imagine anyone would actually try this in the wild.)

**Comment by blowery** [comment]
Too edgy. Closing.
