### ISSUE TITLE
Editor: Mobile: toolbar does not stay pinned to top

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#991]
Raised by @sandymcfadden 

> What I Did:
> Tried scrolling the editor window in Chrome on Android
> 
> What I Expected:
> Expected the toolbar to remain fixed at the top
> 
> What Actually Happened:
> The toolbar disappeared to the top of the screen. When I scrolled back up it came back down into place.
> 
> https://cloudup.com/cnEc3k-4-un

Note from @rachelmcr 

> This also happens on iOS (8.4.1, iPhone 6) in Safari and Chrome. It's especially disruptive because as soon as you focus on the editor the cursor scrolls to the top of the screen, hiding the toolbar from view.

Note from @mtias 

> This is intended behaviour, pinning the toolbar in mobile didn't work well.

**Comment by ryanboren** [comment]
Has troubles staying pinned on Macnchrome too.

https://test.wordpress.com/2016/01/25/editor-toolbar-leaves-editor-when-scrolling-up-macnchrome/

**Comment by ryanboren** [comment]
I've developed the unfortunate habit of inducing elastic bounceback to "reset" the editor. Scrolling all the way up is necessary to unstick the toolbar. When the Visual and HTML tabs are on screen and the toolbar is not below it, I have trouble finding. I scan around the content and title area until remembering, oh yeah, I have to scroll to top to reset. This hitch in editing flow is felt daily, repeatedly.
<img width="830" alt="screen shot 2016-02-08 at 11 30 55 am" src="https://cloud.githubusercontent.com/assets/2047747/12893652/ec640948-ce57-11e5-883f-f53bd5ae6e66.png">

**Comment by aduth** [comment]
Mobile toolbar pinning was removed in 9569-gh-calypso-pre-oss with improvements in #1452. Remaining issues with desktop toolbar pinning are better covered by #337 and #4792, and are expected to be resolved by #4824.
