### ISSUE TITLE
Reader Refresh: full-length excerpts (used on Discover) overlap card actions on IE11

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9916]
For Discover cards, we don't limit the length of the excerpt shown, so it's possible that it can run to four lines. On IE11, this means that it runs into the card actions below:

<img width="882" alt="screen shot 2016-12-09 at 15 21 33" src="https://cloud.githubusercontent.com/assets/17325/21035588/0b05699c-be25-11e6-8f29-d465ac559fb4.png">

**Comment by samouri** [comment]
I just tested this out and it isn't repro-able anymore.
It was fixed by @jancavan  [here](https://github.com/Automattic/wp-calypso/pull/9912#issuecomment-266101151)
