### ISSUE TITLE
Testimonials: Testimonials menu label is untranslated on My Site is opened from front-end

### ISSUE THREAD

**Issue by naokomc** [Automattic/wp-calypso#9918]
**Steps to reproduce**
1. Switch your UI to Japanese (or any of well-translated locale).
2. Go to any page on a site using a theme with the Testimonial CPT.
3. Click "My Site" on the admin bar.
4. "Testimonial" Menu label is not translated.

This only happens when My Site side menu is shown on the frontend. If I fully enter Calypso, it looks fine.

![untranslated-testimonials](https://cloud.githubusercontent.com/assets/34067/21036296/46dbddd8-be08-11e6-9492-aeed6a253fab.jpg)

![translated-testimonials](https://cloud.githubusercontent.com/assets/34067/21036295/46da765a-be08-11e6-964e-4b02953e9077.jpg)

Tested on Sela and Ixion themes.

**Comment by yoavf** [comment]
This should be fixed with r147130-wpcom. @naokomc can you confirm?

**Comment by naokomc** [comment]
<img width="407" alt="2016-12-12 11 11 10" src="https://cloud.githubusercontent.com/assets/34067/21086043/17693b94-c05c-11e6-9a1a-645b8b81609a.png">

Now I'm not seeing CTP from the front-end.

**Comment by naokomc** [comment]
My bad, in the screenshot above I was testing as a wrong user.
It's working perfectly fine now on the front-end.

<img width="371" alt="2016-12-12 16 37 31" src="https://cloud.githubusercontent.com/assets/34067/21091420/577d1bc4-c089-11e6-9278-1a022c57ef86.png">
