### ISSUE TITLE
Editor: double scrollbar (v/h) appearing when not necessary

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#992]
Raised by @folletto 

> ![screen shot 2015-08-05 at 15 17 33](https://cloud.githubusercontent.com/assets/4389/9087939/83f9f86e-3b85-11e5-9f7d-6b0a9df025e5.png)
>
> Two issues, probably unrelated, but both involving scrollbars.
>
> ### Vertical Scrollbar
>
> This should be a consequence of TinyMCE auto-expanding when you write. Initial height of the editor should fit the window, thus showing the ["p" status bar](https://cloud.githubusercontent.com/assets/4389/9087970/abddd3fa-3b85-11e5-9d98-71606ac2bb1f.png) attached to the bottom of the window and no scrollbar until the content of the post is more than the page height.
>
> Note that the expanding behaviour should account for keeping always some whitespace at the end of the content area, otherwise writing gets too cramped and always at the edge of the screen, which isn't good.
>
> ### Horizontal Scrollbar
>
> This is probably related to the interplay of `width` and `max-width` in `.post-editor__inner`, happens just at sizes that are smaller than our wide view, and disappears once the screen touches the mobile screen breakpoint.

Note from @rachelmcr 

> I tested and see the same behavior in Chrome, Safari, and Firefox. The vertical scrollbar is more disruptive to me than the horizontal scrollbar, because there is so much unexpected blank space in the editor as I scroll down and it is always there.
>
> I noticed that the editor always defaults to a height that's just enough for me to scroll down so that the sidebar menus are fully hidden when collapsed. Is that the intention behind the height of the editor and the scrollbar?

Note from @designsimply

> Quick screencast for ref: [51s](https://cloudup.com/cuyMdxgaygV)
<sup>Showing that a horizontal scrollbar appears when the viewport is anywhere from 680px to 1080px wide, seen at https://wordpress.com/post/design5279.wordpress.com/9251 using an incognito view in Chrome 46.0.2490.71 on Mac OS X 10.10.5</sup>

Note from @kriskarkoski 

> In Chrome and Firefox I only see the horizontal scrollbar between 1040 and 1055px, which is the breakpoint where the main content area gets wider, but once I go beyond either end of that it goes away again. I could not see the scrollbar in Safari

**Comment by aduth** [comment]
Fixed by #2131
