### ISSUE TITLE
Taxonomy Manager: can't create child categories

### ISSUE THREAD

**Issue by jeherve** [Automattic/wp-calypso#9929]
#### Steps to reproduce
0. On a Jetpack site;
1. Starting at URL: https://wpcalypso.wordpress.com/settings/taxonomies/category/
2. Create a new category.
3. Give it a parent category.
4. Save your changes

![screen shot 2016-12-09 at 13 47 30](https://cloud.githubusercontent.com/assets/426388/21049589/128ee382-be16-11e6-8c6c-4c3b71aaafc1.png)

![screen shot 2016-12-09 at 13 47 58](https://cloud.githubusercontent.com/assets/426388/21049597/1ce6f9d2-be16-11e6-871d-305f614137fc.png)

![screen shot 2016-12-09 at 13 48 15](https://cloud.githubusercontent.com/assets/426388/21049606/27c1394e-be16-11e6-878a-9798571b5c7e.png)

Although the form data includes the parent ID, the data received in response doesn't:

![screen shot 2016-12-09 at 13 49 38](https://cloud.githubusercontent.com/assets/426388/21049643/6452005a-be16-11e6-8621-8557229f8ddb.png)

```json
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"ID":12,"name":"Very random","slug":"very-random","description":"","post_count":0,"parent":0,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/119868818\/categories\/slug:very-random","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/119868818\/categories\/slug:very-random\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/119868818"}}}}
```

**Comment by timmyc** [comment]
I confirmed this on a JP site as well.  Working fine on wpcom sites.

**Comment by timmyc** [comment]
Digging a bit deeper, here is some output from logging - first snippet is from my sandbox with my request prior to being sent to a remote JP site, note `parent` is set at this point

```
[12-Dec-2016 20:51:31 UTC] Array
(
    [url] => https://public-api.wordpress.com/rest/v1.1/sites/71257737/taxonomies/category/terms/new?http_envelope=1
    [blog_id] => 71257737
    [user_id] => 7611930
    [oauth_client_id] => internal
    [oauth_external_user_code] => 
    [external_user_id] => 
    [pass_wpcom_user_details] => 
    [method] => POST
    [body] => name=child+of+projects&parent=4&description=blah+blah+blah+blah
    [language] => 
)
```

Now output of some logging statements in `class.wpcom-json-api-update-term-endpoint.php`, at this point `parent` is no longer set in the `$input` array, so the default logic of setting `parent=0` is triggered:

```
[12-Dec-2016 20:51:31 UTC] new_term
[12-Dec-2016 20:51:31 UTC] Array
(
    [name] => child of projects
    [description] => blah blah blah blah
)

[12-Dec-2016 20:51:31 UTC] set parent to 0
[12-Dec-2016 20:51:31 UTC] calling wp_insert_term
[12-Dec-2016 20:51:31 UTC] Array
(
    [name] => child of projects
    [description] => blah blah blah blah
    [parent] => 0
)
```

Through this I discovered that `parent` is missing from the `request_format` in the Jetpack JSON endpoint file -> fixed in https://github.com/Automattic/jetpack/pull/5856
