### ISSUE TITLE
Editor: Media: modal should disable background scrolling

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#993]
Raised by @codebykat 

Scrolling within the modal scrolls the background window (once at the end of a scrollable window, or at any time if focused on a non-scrollable section). I wouldn't expect the modal to pass scroll events to the editor.

Note from @mtias 

> I think we lost this in all dialogs at some point, and we should restore it everywhere. It may conflict with how the reader uses dialog.

Note from @rachelmcr 

> I confirmed that there is background scrolling in other places:
> 
> * Media: Add media & Set featured image
> * Keyboard shortcuts
> * Add a new category

**Comment by designsimply** [comment]
Related: #110

**Comment by aduth** [comment]
Fixed by #1293
