### ISSUE TITLE
Reader: iframe embed with percentage width

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#9932]
#### Steps to reproduce
1. View a blog with an iframe embed that has 100% width (https://wordpress.com/read/feeds/152994)

#### What I expected

A visible embed

#### What happened instead

The width is set to 0 in the Reader making it invisible

#### Browser / OS version

Any

# Screenshot

![testomattic_site_s_ _reader_ _wordpress_com](https://cloud.githubusercontent.com/assets/1277682/21045496/8adc3984-bdf8-11e6-9e5e-1afc6d21ffaf.jpg)

#### Source
I think the problem is because the [`detectEmbed`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/post-normalizer/rule-content-detect-media.js#L115) function doesn't understand percentage widths:

`const width = Number( iframe.width );` - sets width to `NaN` when `iframe.width = '100%'`

On the other hand, `embed-helper.jsx` does understand percentage widths, although I don't think it would ever be provided with one because `detectEmbed` strips it out.

The `NaN` goes into EmbedHelper and spits out a width of 0

A quick catch-all could be that EmbedHelper detects `NaN` for width and sets it to availableWidth

Maybe related: https://github.com/Automattic/wp-calypso/issues/8692

**Comment by blowery** [comment]
FYI, the refreshed streams are going live soon, and we no longer embed any old embed in the stream. See https://wpcalypso.wordpress.com/read/feeds/152994 for the current look of that test stream. 

Sadly, a bit bleak currently. /cc @fraying @samouri

**Comment by samouri** [comment]
Closing because this is less relevant now that we don't even support most embeds
