### ISSUE TITLE
Editor: autosave removes trailing space from title

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#994]
When writing a title and thinking of what word to type next, a draft was saved and my trailing space was removed. 

It would be nice if my trailing space stayed.

Note from @kellychoffman 

> > However, if we wanted to avoid this, could we avoid trimming the trailing space while the focus is still on the title field?
> 
> Yeah I think this is a good solution. I can see it being annoying while typing, but not so much if you happen to write your title after your post, the autosave kicks in, and then you hit Publish.

**Comment by timmyc** [comment]
Confirmed that nothing in calypso is stripping out this trailing whitespace, but the returned object from the auto-save does not have the trailing slash in the title.  Trailing whitespace in the title is also stripped in wp-admin upon save... so this appears to be a default core behavior.

As such I'm going to close this out.  If it does become a pain point, we could possibly modify the auto save behavior to not save with empty content perhaps.
