### ISSUE TITLE
Post List: Allow Filtering Posts by Term

### ISSUE THREAD

**Issue by timmyc** [Automattic/wp-calypso#9942]
From feedback on the Taxonomy Manager project ( pbg9X-bkY-p2 ), it was mentioned that it would be nice to have a link from a Term ( category or tag ) to a post listing within Calypso for all posts that are attached to the term.

The current [post-list](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/posts/post-list.jsx#L44-L50) implementation does not support this, nor does the [post-list-fetcher](https://github.com/Automattic/wp-calypso/blob/master/client/components/post-list-fetcher/index.jsx#L27-L38) allow passing in a `term` object to the API call.

[QueryPosts](https://github.com/Automattic/wp-calypso/blob/master/client/components/data/query-posts/index.jsx) appears it will accommodate this scenario, so perhaps updating the post-list to use `QueryPosts` would be a good way to move forward here.

**Comment by folletto** [comment]
Note that we're also building an enhanced search form that allows token for themes, once that's ready, using `tag:name` and `category:name` should be possible in the Posts search field ;)

**Comment by designsimply** [comment]
This came up in Slack recently: 

> I noticed that on our posts list, there’s not a good way to see what categories/tags are associated with published posts. That’s helpful for those themes where you need to set a certain tag for the post to show in a featured content area.
—@dcoleonline

<sup>(internal ref: p1487017254000891-slack-triage)</sup>

**Comment by lancewillett** [comment]
Project check-in: in progress with #15614
