### ISSUE TITLE
Banner: Upgrade button text misaligned at intermediate/tablet width

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#9945]
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/banner
2. Resize your browser window to ~1024px
3. Observe the difference in the two Buttons for the last two banners

#9653 cc: @Copons 

#### What I expected
The text to be center-aligned on both buttons

#### What happened instead
The second button appears fine, but the first one (with the same text) appears right-aligned.  It actually looks fine on an iPad, but other tablets with slightly different screensizes may show the problem.

#### Browser / OS version
OSX Chrome

#### Screenshot / Video
![screen shot 2016-12-09 at 1 10 22 pm](https://cloud.githubusercontent.com/assets/7233112/21059795/2dfdf102-be12-11e6-8474-1e3d7b75d30c.png)

#### Context / Source
#automated-testing #visdiff

**Comment by Copons** [comment]
Good catch!
I was sure I checked that, but likely got lost in some design iteration.
