### ISSUE TITLE
Editor: improve the editing experience for non-reachable Jetpack sites

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#995]
Raised by @jkudish

Unreachable Jetpack sites or any other kind of REST API failure to reach a site should be handled with better grace and provide a useful error message to users. 

Currently if I have an unreachable Jetpack site, I get the following js error, and the interface only semi-loads:

I'm getting `Uncaught TypeError: Cannot read property 'categories' of undefined` and 
`Uncaught TypeError: Cannot read property 'tags' of undefined` for 

The error seems to be coming from `terms: data.categories` in `client/lib/terms/actions.js` line 114 and `terms: data.tags` on line 142 of the same file.

Follow-up notes from @jkudish posted later

Ok, so the issue seems to be that Calypso (Well the REST API, I guess?) thinks that [a WordPress.com site that has a domain that used to be a Jetpack site] is associated with an old/no-longer existent Jetpack site (so the REST API requests to that site are failing), despite [the domain now] being mapped to [the WordPress.com blog]. I [had two separate entries] in my blog picker, so I just got confused between the two.

That being said: we need a better fallback mechanism than js errors when a Jetpack site cannot be reached for whatever reason.

**Comment by kellychoffman** [comment]
_Should_ we allow the user to navigate to this post screen if they can't post anything to their site? Or should they have to make the required changes before they are able to post? We could simply remove the site in question from the list. 

If, however there's a reason we can't do the above, there's two other things that could improve this experience:

1. The site picker dropdown from the Add New Post button should match the site picker in the sidebar. Meaning that the error indicator should show up there as well:

<img width="326" alt="screen shot 2016-01-11 at 2 39 48 pm" src="https://cloud.githubusercontent.com/assets/5835847/12245937/354c106c-b871-11e5-9fcc-64cf1e06ee1b.png">

2. If the user does indeed to step further, we could add an error to the top of the page:

<img width="949" alt="screen shot 2016-01-11 at 2 21 43 pm" src="https://cloud.githubusercontent.com/assets/5835847/12245939/3dfc0438-b871-11e5-89b2-7c9133dc93c4.png">

**Comment by brbrr** [comment]
<img width="1361" alt="plugin browser handsome howler 423 wordpress com 2017-12-29 13-42-21" src="https://user-images.githubusercontent.com/5654161/34431064-20114c5e-ec9e-11e7-85b8-0f4b85f81f00.png">

That is already implemented. Closing this.
