### ISSUE TITLE
Editor: cannot reach sidebar when editing a long post

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#996]
Raised by @jeremeylduvall 

Currently, when you're scrolling on a long post, the post options disappear and you're unable to access them:

![scroll](https://cloud.githubusercontent.com/assets/7240478/9311841/4038063e-44d6-11e5-9022-752e8d71cecf.png)

Then, if I wanted to add a category, for example, I have to scroll all the way back up to the top, which feels inconvenient and overall not fun.

Would it make sense to "attach" the individual modules to the main box as you scroll down? So, for example, as I scroll down past "Categories and Tags", it attaches to the main box. On a long post then, the options would all be available even at the very bottom of the post.

Note from @folletto 

> To add some more details to this thread:
> 
> 1. The sidebar should scroll independently, and that will match the Basic+App Style design we are aiming for.
> 1. A great example of this is the right-column of Keynote. Try it out to get how well it works.

**Comment by aduth** [comment]
Fixed by #2131
