### ISSUE TITLE
Taxonomy Manager: Unknown taxonomy error with long tag string

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/wp-calypso#9964]
When I edit a tag and add a super long tag name, it fails with a console error of `Uncaught (in promise) Error: Unknown taxonomy(…)`. In this case, I used a long lorem ipsum stream. It froze my screen (couldn't cancel either).

Here's the text I used:

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

## To test

1. Add a new tag with a short name.
2. Go back to edit that tag. Replace the short name with the lorem ipsum.
3. Try to save the tag.

I get a console error each time. Here's a GIF:

![testinglong](https://cloud.githubusercontent.com/assets/7240478/21076096/0a72b9a6-bee0-11e6-9cf9-8e7074f0782d.gif)

I don't think tag names should be this long, but right now, the failure is pretty invisible to the user and freezes the screen.

**Comment by youknowriad** [comment]
Proposed a fix in code-D3671

**Comment by jeremeylduvall** [comment]
The original diff D3671-code is still open. @youknowriad do you know if that's likely to get merged or not?

**Comment by youknowriad** [comment]
@jeremeylduvall Just took a look at the patch again and the issue is that this change could have side effects. I don't have enough confidence in this codebase to commit it without a proper review. Do you know who can we ping about this?

**Comment by jeremeylduvall** [comment]
@youknowriad I actually just tested this again (should have done that originally), and the error no longer locks up my screen. It just doesn't update the tag name if I paste in a long snippet, but that's much better than freezing up. For right now, this feels like an edge case, and it's mostly working as expected so I'm going to close.
