### ISSUE TITLE
Site Settings: Press This is hidden for touch-enabled laptops

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#9981]
Press This is disabled for touch devices, because it's not known to be working with them. However, this is also hiding it for touch-enabled laptops.

#### Steps to reproduce
1. Use a touch-enabled laptop.
2. Go to: `https://wordpress.com/settings/writing/$site`, where `$site` is one of your sites.
3. The **Press This** bookmarklet will be hidden.

#### What I expected
**Press This** should be visible for devices that you can use it on.

#### What happened instead
**Press This** is disabled on touch-enabled laptops.

#### Context / Source
Discovered by @johnHackworth while testing #9977 
#manual-testing

**Comment by lancewillett** [comment]
I think this is an OK side effect. Press This is a legacy feature that we don't want to encourage **too much.** Overall, we'd like people to use Calypso directly for posting, or if on a tablet or mobile device, use the native app editor.
