### ISSUE TITLE
Reader: Cards too short on IE11 in some views

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#9989]
<img width="956" alt="ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/14350/21113968/887c98fe-c079-11e6-8591-e84173b4bae3.png">

Only appears on the sub 1040 break and the narrow one column break.

<img width="541" alt="ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/14350/21114006/a69a2df6-c079-11e6-96f8-dd005724cfb7.png">

**Comment by bluefuton** [comment]
Looks like this will help here too: https://github.com/philipwalton/flexbugs/issues/58.

**Comment by jancavan** [comment]
Default and Excerpt-only cards fixed in: https://github.com/Automattic/wp-calypso/pull/9992#issuecomment-266805116

Photo cards fixed in: https://github.com/Automattic/wp-calypso/pull/9992/commits/7396d5c643f6502606b4dd298c96017f0591d164
