### ISSUE TITLE
Editor: removing caption returns image to previous alignment

### ISSUE THREAD

**Issue by designsimply** [Automattic/wp-calypso#999]
Steps to reproduce:
1. Click on an image
2. Click the "Caption" button
3. Click the image again
4. Click on the "Align right" button
5. Click the "Caption" button again

<strong>Result:</strong> if the alignment is changed between two caption changes, the image alignment reverts when the caption is removed.

<strong>Video:</strong> https://cloudup.com/cL1zHFeZqjc
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/9790 using Chrome 46.0.2490.86 on Mac OS X 10.10.5</sup>

/hat tip kriskarkoski for the original report

I could only trigger this issue if I sandwiched an alignment change between two caption changes (add/remove), so this issue seems fairly edge case to me.

**Comment by rachelmcr** [comment]
I believe this is a symptom of a larger problem:

When an image has a caption, setting the alignment only affects the caption alignment, not the image alignment.

Steps to reproduce:

1. Click on an image without a caption
2. Click on the "Align right" button
3. Switch to HTML and confirm that the `img` tag now has an `alignright` class
4. Switch back to Visual
5. Click on the image again
6. Click the "Caption" button
7. Click the "Align center" button
8. Switch to HTML and confirm that the `img` tag still has an `alignright` class and the caption shortcode now has a `align="aligncenter"` argument

I tested different combinations of alignments with and without a caption, and in my testing the alignment only affected the image itself if the image didn't have a caption.

**Comment by rachelmcr** [comment]
Closing as this will be resolved with Gutenberg.

#bug-scrub #pre-gutenburg-bug-purge
